PROGRAM TEST5
!=======================================================================
! [USAGE]:
! USE VPROD_PFF RATHER THAN VPROD
!
! FIND EIGENVALUES AND EIGENVECTORS OF THE LINEARIZED N-S EQUATIONS
! EXPRESSED IN A POLOIDAL-TOROLIDALLY DECOMPOSED FORM
! OPERATOR H CORRESPONDS TO EIGENVECTOR: [PSI,DEL2CHI]^T
!
! [UPDATES]:
! LAST UPDATE ON DEC 3, 2020
!=======================================================================
USE omp_lib
USE MPI
USE MOD_MISC
USE MOD_BANDMAT
USE MOD_EIG
USE MOD_FD
USE MOD_LIN_LEGENDRE
USE MOD_SCALAR3
USE MOD_FFT
USE MOD_LAYOUT
USE MOD_LEGOPS
USE MOD_MARCH
USE MOD_INIT
USE MOD_EVP
USE MOD_DIAGNOSTICS

IMPLICIT NONE
INTEGER     :: II, JJ, KK, K_ind
INTEGER     :: M_BAR, EIG_BAR_IND, M_1
REAL(P8)    :: K_BAR, K_VAL_1_0
COMPLEX(P8), DIMENSION(:), ALLOCATABLE:: M_eig
COMPLEX(P8), DIMENSION(:, :), ALLOCATABLE:: M_mat, EIG_R_mat, EIG_L_mat
COMPLEX(P8), DIMENSION(:), ALLOCATABLE:: RUR_BAR, RUP_BAR, UZ_BAR, EIG_R_BAR
COMPLEX(P8), DIMENSION(:), ALLOCATABLE:: ROR_BAR, ROP_BAR, OZ_BAR, EIG_L_BAR

COMPLEX(P8), DIMENSION(:), ALLOCATABLE:: RUR_BAR2, RUP_BAR2, UZ_BAR2, EIG_R_BAR2
COMPLEX(P8), DIMENSION(:), ALLOCATABLE:: ROR_BAR2, ROP_BAR2, OZ_BAR2, EIG_L_BAR2

! ADD PERTURB:
INTEGER:: IS, NDIM
! SCANNING:
CHARACTER(len=5) :: K_VAL
CHARACTER(LEN=72):: FILENAME
INTEGER:: FID
! RES MASK
LOGICAL,DIMENSION(:),ALLOCATABLE:: MASK1,MASK2
LOGICAL,DIMENSION(:,:),ALLOCATABLE:: MASK2D

! CALL MPI_INIT(IERR)
CALL MPI_INIT_THREAD(MPI_THREAD_SERIALIZED, MPI_THREAD_MODE, IERR)
IF (MPI_THREAD_MODE .LT. MPI_THREAD_SERIALIZED) THEN
    WRITE (*, *) 'The threading support is lesser than that demanded.'
    CALL MPI_ABORT(MPI_COMM_WORLD, 1, IERR)
END IF

CALL MPI_COMM_SIZE(MPI_COMM_WORLD, MPI_GLB_PROCS, IERR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD, MPI_GLB_RANK, IERR)
IF (MPI_GLB_RANK .EQ. 0) THEN
    WRITE (*, *) 'PROGRAM STARTED'
    CALL PRINT_REAL_TIME()   ! @ MOD_MISC
END IF
CALL MPI_Comm_split(MPI_COMM_WORLD, MPI_GLB_RANK, 0, newcomm, IERR) ! DIVIDE NR BY #OF MPI PROCS
CALL READCOM('NOECHO')
CALL READIN(5)

! {M_bar, AK_bar}: BASE FLOW
!=======================================================================
IF (MPI_GLB_RANK .EQ. 0) THEN

    ! ALLOCATE(MASK1(2),MASK2(3))
    ! ALLOCATE(MASK2D(SIZE(MASK1),SIZE(MASK2)))

    ! MASK1 = (/.TRUE.,.FALSE./)
    ! ! T T T
    ! ! F F F    
    ! MASK2 = (/.FALSE.,.TRUE.,.FALSE./)
    ! ! F T F
    ! ! F T F    

    ! MASK2D = RESMASK(SIZE(MASK1),MASK1,SIZE(MASK2),MASK2)
    ! ! F T F
    ! ! F F F

    ! DO II = 1,SIZE(MASK2D,1)
    !     WRITE(*,*) MASK2D(II,:)
    ! ENDDO

    ! CALL MPI_ABORT(MPI_COMM_WORLD,1,IERR)

    FILENAME = 'almostdegen_read.input'
    CALL READIN(FILENAME, M_BAR, K_BAR, EIG_BAR_IND, M_1, K_VAL_1_0)

    write(*,*) SUBCOMM_1,SUBCOMM_2
END IF ! MPI_GLB_RANK.EQ.0

! calculate operator matrix and its corresponding eigenvalues
M_BAR = 1
K_BAR = -10.D0
WRITE(K_VAL,'(F05.2)') K_BAR
WRITE(*,*) K_BAR, ITOA4(-10)

! SUBROUTINE READ_MODE(MREAD, AKREAD, EIG_MAT, EIG_VAL, EIG_VEC_R, EIG_VEC_L)
CALL READ_MODE(M_BAR, K_BAR, M_mat, M_eig, EIG_R_mat, EIG_L_mat )

! CALL EIG_MATRIX(M_BAR, K_BAR, M_mat, M_eig, EIG_VEC_R = EIG_R_mat, EIG_VEC_L = EIG_L_mat, comm_grp=newcomm, print_switch=.true.) 

IF (MPI_GLB_RANK .EQ. 0) THEN

    ! EIG2VEL:
    ALLOCATE(EIG_R_BAR(SIZE(EIG_R_mat,1)))
    DO II = 1,SIZE(M_eig)
        ! II = 688
        EIG_R_BAR = EIG_R_mat(:,II)
        IF (EIGRES(EIG_R_BAR,M_BAR)) THEN
            WRITE(*,*) 'II = ',II,':',M_eig(II)
        ENDIF
    ENDDO

    ! CALL SAVE_MODE(M_BAR, K_BAR, M_mat, M_eig, EIG_R_mat, EIG_L_mat)

    DEALLOCATE(EIG_R_BAR,M_eig)

    ! TEST: MASK2D
    ! ! WRITE(*,*) EIGRES(SIZE(EIG_R_mat,2),EIG_R_mat,M_BAR)
    ! ALLOCATE(MASK2D(SIZE(M_eig),SIZE(M_eig)))
    ! MASK2D = MESHGRID(EIGRES(EIG_R_mat,M_BAR),EIGRES(EIG_R_mat,M_BAR))
    ! DO II = 1,SIZE(MASK2D,1)
    !     DO JJ = 1,SIZE(MASK2D,2)
    !         IF (MASK2D(II,JJ)) WRITE(*,*) II,JJ
    !     ENDDO
    ! ENDDO

ENDIF

IF (ALLOCATED(EIG_R_mat)) DEALLOCATE(EIG_R_mat)
IF (ALLOCATED(EIG_L_mat)) DEALLOCATE(EIG_L_mat)

IF (MPI_GLB_RANK .EQ. 0) THEN
    WRITE (*, *) ''
    WRITE (*, *) 'PROGRAM FINISHED'
    CALL PRINT_REAL_TIME()  ! @ MOD_MISC
END IF

CALL MPI_FINALIZE(IERR)

END PROGRAM TEST5
!=======================================================================
