program test_legops
    ! PROGRAM TO ASSEMBLE LOCAL ARRAYS INTO GLOBAL ARRAYS
        USE OMP_LIB
        USE MPI
        USE MOD_MISC                                                       ! LEVEL 0
        USE MOD_EIG                                                        ! LEVEL 1
        !USE MOD_LIN_LEGENDRE                                               ! LEVEL 1
        USE MOD_SCALAR3                                                    ! LEVEL 2
        USE MOD_FFT
        USE MOD_LEGOPS
        USE MOD_MARCH
        USE MOD_DIAGNOSTICS
        USE MOD_INIT
        !USE MOD_LAYOUT
    implicit none
    
    ! INPUT:
    TYPE(SCALAR):: A,B,C,D,E,F,G,H
    ! OUTPUT:
    COMPLEX(P8),DIMENSION(:,:,:),ALLOCATABLE:: GLOBAL_ARRAY
    CHARACTER(LEN=72) :: A_GLB_FILENAME
    CHARACTER(LEN=1) :: SWITCH
    
    ! TEMPORARY:
    INTEGER:: N1, N2, N3, I, J, K
    REAL:: RANDNUM_RE, RANDNUM_IM, alpha
    
    CALL MPI_INIT(IERR)
    CALL MPI_COMM_RANK(MPI_COMM_WORLD, MPI_RANK, IERR)

    CALL READCOM('NOECHO')
    CALL READIN(5)
    CALL LEGINIT()

    CALL ALLOCATE(A,FFF_SPACE)
    CALL ALLOCATE(B,FFF_SPACE)
    CALL ALLOCATE(C,FFF_SPACE)
    CALL ALLOCATE(D,FFF_SPACE)
    CALL ALLOCATE(E,FFF_SPACE)
    CALL ALLOCATE(F,FFF_SPACE)
    CALL ALLOCATE(G,FFF_SPACE)
    CALL ALLOCATE(H,FFF_SPACE)
    ALLOCATE(GLOBAL_ARRAY(NRCHOPDIM,NTCHOPDIM,NXCHOPDIM))
    !ALLOCATE(GLOBAL_ARRAY(NDIMR,NDIMTH,NDIMX))

    CALL MLOAD('A_loc.dat', A)
    CALL CHOPDO(A)

    ! TESTING:
    alpha = 1/(VISC%NU*0.001)
    SWITCH = 'Y'
    CALL DELSQH(A,B)
    E = A
    F = B
    CALL DIAGNOST(A,B)
    ! CALL RTRAN(A,1)
    ! CALL VERFFT(A,1)
    ! CALL HORFFT(A,1)
    CALL RICH(A,B,C,D)
    ! CALL ADAMSB(A,B,C,D)
    ! CALL MONITOR_EIG(E,F,A,B,0.0,0.0001)
    ! CALL EGROWTH(E,F,A,B,0.0,0.0001)
    ! CALL PRINT_ENERGY_SPECTRUM(A,B,0)
    ! CALL WRITE_ENERGY_DATA_TO_FILE(A,B)
    ! CALL WRITE_MODE_DATA_TO_FILE(A,B)

    ! OUTPUT:
    CALL MASSEMBLE(C%E,GLOBAL_ARRAY,1)
    IF (MPI_RANK.EQ.0) THEN
        WRITE(*,*) A%LN
        ! CALL MCAT(A%E(:,1,:))
        CALL MCAT(GLOBAL_ARRAY(:,64,:5))
        WRITE(*,*) ''
        ! CALL MCAT(GLOBAL_ARRAY(:,13,:))
        ! WRITE(*,*) ''
        WRITE(*,*) SHAPE(GLOBAL_ARRAY)
        WRITE(*,*) NXCHOPDIM
    ENDIF

    CALL DEALLOCATE(A)
    CALL DEALLOCATE(B)
    CALL DEALLOCATE(C)
    CALL DEALLOCATE(D)
    CALL DEALLOCATE(E)
    CALL DEALLOCATE(F)
    CALL DEALLOCATE(G)
    CALL DEALLOCATE(H)
    DEALLOCATE(GLOBAL_ARRAY)

    CALL MPI_FINALIZE(IERR)



end program test_legops