MODULE MOD_MARCH ! LEVEL 4 MODULE
  USE omp_lib
  USE MPI
  USE MOD_MISC, ONLY : P4,P8,PI,IU,SPY,MSAVE,MCAT,CFL               ! LEVEL 0
  USE MOD_EIG                                                        ! LEVEL 1
  USE MOD_SCALAR3                                                    ! LEVEL 2
  USE MOD_FFT                                                        ! LEVEL 2.5
  USE MOD_LEGOPS                                                     ! LEVEL 3
  USE MOD_BOUSSINESQ
  IMPLICIT NONE
  PRIVATE
!=======================================================================
!============================ PARAMETERS ===============================
!=======================================================================
  !0> NUMERICAL SOLVER
  PUBLIC:: SOLVER_T
  TYPE SOLVER_T
    ! --- HISTORY VARIABLES ---
    ! For AB-CN:
    TYPE(SCALAR):: N_PSI, N_CHI
    ! For ETD-CN:
    TYPE(SCALAR):: R_N_R, R_N_P, N_Z
    ! Shared:
    TYPE(SCALAR):: N_B

    ! --- ETD2AB OPERATORS ---
    COMPLEX(P8), ALLOCATABLE, DIMENSION(:,:) :: ETD_E, ETD_NL

    ! --- OUTPUT CONTROL ---
    LOGICAL:: SAVE_VARIABLE = .TRUE.
    REAL(P8):: TIME_START = 0.0D0

    CONTAINS
      PROCEDURE, PASS(THIS):: INITIALIZE
      PROCEDURE, PASS(THIS):: TIME_STEPPING
      PROCEDURE, PASS(THIS):: FINALIZE
  ENDTYPE SOLVER_T
  TYPE(SOLVER_T),PUBLIC:: PT_SOLVER

  !1> TIME ADVANCEMENT INFORMATION
  PUBLIC:: TIMEDATA
  TYPE TIMEDATA
    REAL(P8):: DT,T,LIMIT
    INTEGER:: N
    INTEGER:: SCHEME
  ENDTYPE TIMEDATA
  TYPE(TIMEDATA),PUBLIC:: TIM

  !2> FREESTREAM VELOCITY FIELD INFORMATION
  PUBLIC:: IMPOSED_FIELD
  TYPE IMPOSED_FIELD
    INTEGER:: SW, INT  
    REAL(P8):: UX,UY,UZ
    REAL(P8):: X,Y
    REAL(P8):: T0,X0,Y0,T1,X1,Y1
  ENDTYPE IMPOSED_FIELD
  TYPE(IMPOSED_FIELD),PUBLIC:: ADV

  !3> VORTEX REMOVAL
  PUBLIC:: REMOVAL
  TYPE REMOVAL
    INTEGER:: SW,INT
  ENDTYPE REMOVAL
  TYPE(REMOVAL),PUBLIC:: RMV

  !4> VISCOSITY ADJUSTMENT
  PUBLIC:: VISCOSITY
  TYPE VISCOSITY
    INTEGER:: SW,P,ADJSW,ADJINT
    REAL(P8):: NU,NUP
  ENDTYPE VISCOSITY
  TYPE(VISCOSITY),PUBLIC:: VISC

  !5> FILE INOUT
  PUBLIC:: IOFILES
  TYPE IOFILES
    CHARACTER(LEN=72):: SAVEDIR 
    CHARACTER(LEN=72):: PSI0,CHI0,B0
    CHARACTER(LEN=72):: PSII,CHII,BI
    REAL(P8),DIMENSION(:),POINTER:: T
    CHARACTER(LEN=72),DIMENSION(:),POINTER:: PSI,CHI,B
    INTEGER:: N,NE
  ENDTYPE IOFILES
  TYPE(IOFILES),PUBLIC:: FILES

  !6> DIAGNOSTIC INFOMRATION STORAGE
  PUBLIC:: DIAGDATA
  TYPE DIAGDATA
    LOGICAL:: IS_INITIALIZED=.FALSE.
    INTEGER:: IT1,IT2
    REAL(P8):: VORI,ZMOMI,ENEI,ANGI,HELI,XCEN,YCEN
  ENDTYPE DIAGDATA
  TYPE(DIAGDATA),PUBLIC:: DIAGV

  !7> LINEAR DATA INFORMATION STORAGE (CURRENTLY DUMMY)
  PUBLIC:: LINEARDATA
  TYPE LINEARDATA
    INTEGER:: MM,KK
  ENDTYPE LINEARDATA
  TYPE(LINEARDATA),PUBLIC:: LIN

  !8> POSTPROCESS KIT
  PUBLIC:: POSTPROCESSKIT
  TYPE POSTPROCESSKIT
    INTEGER :: START, FINISH, JOB, SLICEINT
  ENDTYPE POSTPROCESSKIT
  TYPE(POSTPROCESSKIT),PUBLIC:: POSTPROCESS

  !9> EIGENVALUE MONITOR KIT
  PUBLIC:: MONITOREIGENVALUESKIT
  TYPE MONITOREIGENVALUESKIT
    INTEGER :: START, INTERVAL
  ENDTYPE MONITOREIGENVALUESKIT
  TYPE(MONITOREIGENVALUESKIT),PUBLIC:: MONITORDATA

  REAL(P8):: SUMMO,SUMKO,NUPB                                        ! USED IN THE HYPADJ SUBROUTINE
  INTEGER:: FIRST=0                                                  ! USED IN THE HYPADJ SUBROUTINE
  REAL(P8),DIMENSION(:),ALLOCATABLE :: HYPER_R, HYPER_T, HYPER_X     ! USED IN HYPSET AND HYPERV3
  INTEGER, PUBLIC, ALLOCATABLE, DIMENSION(:,:):: MONITOR_MK          ! EIGENVALUE MONITOR FOR DIFFERENT AZIMUTHAL AND AXIAL WAVENUMBERS
!=======================================================================
!======================== PUBLIC DECLARATION ===========================
!=======================================================================
  ! TIME ADVANCEMENT SCHEMES (ADAMS-BASHFORTH, RICHARDSON, EULER)
  PUBLIC:: ADAMSB, RICH, EULER, ETD1FE, ETD_INIT
  ! VISCOSITY & HYPERVISCOSITY IMPOSITION
  PUBLIC:: VISC1,VISC2,HYPERV
  ! DIAGNOSIS OF FIELD
  PUBLIC:: DIAGNOST
  ! ADJUST FREESTREAM VELOCITY
  PUBLIC:: FREEADJ
  ! KILL VORTEX AWAY FROM THE COMPUTATIONAL DOMAIN
  PUBLIC:: REMOVE
  ! COMPUTE ENERGY FOR EACH AZIMUTHAL/AXIAL WAVENUMBER
  PUBLIC:: ENEMON
  ! HYPERVISCOSITY ADJUSTMENT
  PUBLIC:: HYPADJ
  
CONTAINS
!=======================================================================
!======================= SOLVER TYPE PROCEDURES ========================
!=======================================================================
  SUBROUTINE INITIALIZE(THIS, PSI, CHI, B)
!=======================================================================
! [USAGE]: 
! CONFIGURE THE SOLVER FOR TIME STEPPING AND ALLOCATE HISTORY VARIABLES
!=======================================================================
  IMPLICIT NONE
  CLASS(SOLVER_T), INTENT(INOUT) :: THIS
  TYPE(SCALAR), INTENT(INOUT)   :: PSI, CHI, B

  CALL MPRINT('SOLVER: Initializing and performing startup step...')
  THIS%TIME_START = MPI_WTIME()

  IF (BSNSQ%ADAMS) THEN
    CALL MPRINT('SOLVER: bsnsq%adams=T. Configuring AB2-CN scheme.')
    CALL ALLOCATE(THIS%N_B, FFF_SPACE)
    CALL ALLOCATE(THIS%N_PSI, FFF_SPACE)
    CALL ALLOCATE(THIS%N_CHI, FFF_SPACE)
    CALL RICH_AB_KERNEL(THIS, PSI, CHI, B)
  ELSE
    CALL MPRINT('SOLVER: bsnsq%adAMS=F. Configuring ETD2-CN scheme.')
    ALLOCATE(THIS%ETD_E(4,4), THIS%ETD_NL(4,4))
    CALL ETD_INIT(THIS%ETD_E, THIS%ETD_NL, TIM%DT)
    CALL ALLOCATE(THIS%N_B, PPP_SPACE)
    CALL ALLOCATE(THIS%R_N_R, PPP_SPACE)
    CALL ALLOCATE(THIS%R_N_P, PPP_SPACE)
    CALL ALLOCATE(THIS%N_Z, PPP_SPACE)
    CALL RICH_ETD_KERNEL(THIS, PSI, CHI, B)
  ENDIF

  CALL MPRINT('SOLVER: Initialization and Richardson startup complete.')

  RETURN
  END SUBROUTINE INITIALIZE
!=======================================================================

  SUBROUTINE TIME_STEPPING(THIS, PSI, CHI, B)
!=======================================================================
! [USAGE]: 
! PERFORM A SINGLE TIME-STEPPING
!=======================================================================
  IMPLICIT NONE
  CLASS(SOLVER_T), INTENT(INOUT) :: THIS
  TYPE(SCALAR), INTENT(INOUT)   :: PSI, CHI, B

  IF (BSNSQ%ADAMS) THEN
    CALL AB2CN_KERNEL(THIS, PSI, CHI, B)
  ELSE
    CALL ETD2CN(THIS, PSI, CHI, B)
  ENDIF

  CALL HYPERV3(PSI, CHI, B) ! CUSTOMIZED HYPERV (SW > 2)
  CALL DIAGNOST(PSI, CHI)
  CALL CALC_ENERGY(PSI, CHI, B, TIM%T, FILES%SAVEDIR)

  IF ((FILES%T(FILES%N) .LE. TIM%T) .AND. (THIS%SAVE_VARIABLE)) THEN
    CALL MSAVE(PSI, TRIM(ADJUSTL(FILES%SAVEDIR)) // FILES%PSI(FILES%N))
    CALL MSAVE(CHI, TRIM(ADJUSTL(FILES%SAVEDIR)) // FILES%CHI(FILES%N))
    CALL MSAVE(B, TRIM(ADJUSTL(FILES%SAVEDIR)) // FILES%B(FILES%N))
    FILES%N = FILES%N + 1

    ! Stop the simulation once the last file is saved
    ! if(files%n > files%ne) goto 999
    IF (FILES%N > FILES%NE) THIS%SAVE_VARIABLE = .FALSE.
  ENDIF

  RETURN
  END SUBROUTINE TIME_STEPPING
!=======================================================================
  SUBROUTINE FINALIZE(THIS, PSI, CHI, B)
!=======================================================================
  USE MOD_MISC, ONLY: PRINT_REAL_TIME
  IMPLICIT NONE
  CLASS(SOLVER_T), INTENT(INOUT) :: THIS
  TYPE(SCALAR), INTENT(INOUT), OPTIONAL :: PSI, CHI, B
  REAL(P8):: TIME_END

  CALL MPRINT('SOLVER: Deallocating ...')

  ! Free allocated memory
  IF (ALLOCATED(THIS%ETD_E)) DEALLOCATE(THIS%ETD_E,THIS%ETD_NL)
  CALL DEALLOCATE(THIS%N_B)
  IF (BSNSQ%ADAMS) THEN
    CALL DEALLOCATE(THIS%N_PSI)
    CALL DEALLOCATE(THIS%N_CHI)
  ELSE
    CALL DEALLOCATE(THIS%R_N_R)
    CALL DEALLOCATE(THIS%R_N_P)
    CALL DEALLOCATE(THIS%N_Z  )
  ENDIF

  IF (PRESENT(PSI)) CALL DEALLOCATE(PSI)
  IF (PRESENT(CHI)) CALL DEALLOCATE(CHI)
  IF (PRESENT(B)) CALL DEALLOCATE(B)

  CALL MPRINT('SOLVER: ')
  TIME_END = MPI_WTIME()
  IF (MPI_RANK.eq.0) THEN
      WRITE(*,*) 'Finalized after ', TIM%N, 'steps'
      WRITE(*,*) 'Time-stepping total time: ', TIME_END-THIS%TIME_START,'seconds'
      CALL PRINT_REAL_TIME()
  ENDIF
  call MPI_BARRIER(MPI_COMM_IVP,IERR)
  call MPI_FINALIZE(IERR)

  RETURN
  END SUBROUTINE FINALIZE
!=======================================================================
!======================= TIME-STEPPING KERNELS =========================
!=======================================================================
  SUBROUTINE AB2CN_KERNEL(THIS, PSI, CHI, B)
!=======================================================================
  IMPLICIT NONE
  TYPE(SOLVER_T), INTENT(INOUT) :: THIS
  TYPE(SCALAR), INTENT(INOUT)   :: PSI, CHI, B

  TYPE(SCALAR):: PSIN,CHIN,BN
  TYPE(SCALAR):: PSI0,CHI0,B0
  REAL(P8):: DT

  DT = TIM%DT
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE( PSIN )
  CALL ALLOCATE( CHIN )
  CALL ALLOCATE(   BN )

  CALL BOUSSINESQ_FULL(PSI,CHI,B,PSIN,CHIN,BN)

  CALL ALLOCATE( PSI0 )
  CALL ALLOCATE( CHI0 )
  CALL ALLOCATE(   B0 )

  PSI0 = PSI
  CHI0 = CHI
  B0 = B

  PSI%E  = PSI%E  +DT*(1.5D0*PSIN%E -0.5D0*THIS%N_PSI%E)
  CHI%E  = CHI%E  +DT*(1.5D0*CHIN%E -0.5D0*THIS%N_CHI%E)
  CHI%LN = CHI%LN +DT*(1.5D0*CHIN%LN -0.5D0*THIS%N_CHI%LN)
  B%E    = B%E    +DT*(1.5D0*BN%E -0.5D0*THIS%N_B%E)

  THIS%N_PSI = PSIN
  THIS%N_CHI = CHIN
  THIS%N_B   = BN

  CALL DEALLOCATE( PSIN )
  CALL DEALLOCATE( CHIN )
  CALL DEALLOCATE(   BN )

  CALL VISC2(PSI,CHI,B,PSI0,CHI0,B0)
  CALL HYPERV(PSI,CHI,B,DT)

  CALL DEALLOCATE( PSI0 )
  CALL DEALLOCATE( CHI0 )
  CALL DEALLOCATE(   B0 )

  RETURN
  END SUBROUTINE AB2CN_KERNEL
!=======================================================================

  SUBROUTINE RICH_AB_KERNEL(THIS, PSI, CHI, B)
!=======================================================================
  IMPLICIT NONE
  TYPE(SOLVER_T), INTENT(INOUT) :: THIS
  TYPE(SCALAR), INTENT(INOUT)   :: PSI, CHI, B

  TYPE(SCALAR):: PSI2,CHI2,B2
  TYPE(SCALAR):: P_N,C_N,B_N
  REAL(P8):: DT, HDT

  DT = TIM%DT
  HDT = DT*0.5D0
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE(PSI2)
  CALL ALLOCATE(CHI2)
  CALL ALLOCATE(  B2)

  ! FIRST HALF-STEP
  CALL BOUSSINESQ_FULL(PSI,CHI,B,THIS%N_PSI,THIS%N_CHI,THIS%N_B)

  PSI2%E  =PSI%E  + (HDT*THIS%N_PSI%E)
  CHI2%E  =CHI%E  + (HDT*THIS%N_CHI%E)
  CHI2%LN =CHI%LN + (HDT*THIS%N_CHI%LN)
  B2%E    =B%E    + (HDT*THIS%N_B%E)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  CALL ALLOCATE( P_N )
  CALL ALLOCATE( C_N )
  CALL ALLOCATE( B_N )

  ! SECOND HALF-STEP
  CALL BOUSSINESQ_FULL(PSI2,CHI2,B2,P_N,C_N,B_N)

  PSI2%E  =PSI2%E  + (HDT*P_N%E)
  CHI2%E  =CHI2%E  + (HDT*C_N%E)
  CHI2%LN =CHI2%LN + (HDT*C_N%LN)
  B2%E    =B2%E    + (HDT*B_N%E)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  ! FULL STEP
  PSI%E  =PSI%E  + (DT)*THIS%N_PSI%E
  CHI%E  =CHI%E  + (DT)*THIS%N_CHI%E
  CHI%LN =CHI%LN + (DT)*THIS%N_CHI%LN
  B%E    =B%E    + (DT)*THIS%N_B%E

  CALL VISC1(PSI,CHI,B,DT)
  CALL HYPERV(PSI,CHI,B,DT)

  PSI%E  =(2.0D0*PSI2%E)-PSI%E
  CHI%E  =(2.0D0*CHI2%E)-CHI%E
  CHI%LN =(2.0D0*CHI2%LN)-CHI%LN
  B%E    =(2.0D0*B2%E)-B%E

  CALL DEALLOCATE( PSI2 )
  CALL DEALLOCATE( CHI2 )
  CALL DEALLOCATE(   B2 )
  CALL DEALLOCATE( P_N )
  CALL DEALLOCATE( C_N )
  CALL DEALLOCATE( B_N )

  RETURN
  END SUBROUTINE RICH_AB_KERNEL
!=======================================================================

  SUBROUTINE ETD2CN(THIS, PSI, CHI, B)
!=======================================================================
  IMPLICIT NONE
  TYPE(SOLVER_T), INTENT(INOUT) :: THIS
  TYPE(SCALAR), INTENT(INOUT)   :: PSI, CHI, B

  REAL(P8):: DT
  TYPE(SCALAR):: RURN, RUPN, UZN, BN
  TYPE(SCALAR):: RORN, ROPN, OZN
  TYPE(SCALAR):: PSI0, CHI0, B0
  TYPE(SCALAR):: W

  DT = TIM%DT
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE(RURN); CALL ALLOCATE(RUPN); CALL ALLOCATE(UZN)
  CALL ALLOCATE(RORN); CALL ALLOCATE(ROPN); CALL ALLOCATE(OZN)

  CALL CHOPSET(3)
  CALL PC2VEL(PSI,CHI,RURN,RUPN,UZN)
  CALL PC2VOR(PSI,CHI,RORN,ROPN,OZN)
  CALL CHOPSET(-3)

  ! CALCULATE NONLINEAR TERMS: U X W AND -(U.GRAD)B' 
  ! NOTES:
  ! - B REMAIN IN FFF SPACE
  ! - RURN, RUPN, UZN ARE RETURNED IN PPP SPACE
  !   AND UPDATED WITH FREESTREAM ADJUSTMENT
  ! - RORN, ROPN, OZN ARE RETURNED IN PPP SPACE
  CALL BOUSSINESQ_NONLIN(B,RURN,RUPN,UZN,BN,RORN,ROPN,OZN)

  CALL ALLOCATE(B0)
  B0 = B ! FFF SPACE

  ! APPLY ETD UPDATE TO RURN, RUPN, UZN, B
  ! TODO: CHECK HOW FREESTREAM ADJUSTMENT WILL AFFECT RESULTS
  CALL ETD2_SUB(THIS, B, RURN, RUPN, UZN, BN, RORN, ROPN, OZN)
  THIS%N_B = BN
  THIS%R_N_R = RORN
  THIS%R_N_P = ROPN
  THIS%N_Z = OZN
  CALL DEALLOCATE(BN)
  CALL DEALLOCATE(RORN)
  CALL DEALLOCATE(ROPN)
  CALL DEALLOCATE(OZN)

  CALL ALLOCATE(PSI0)
  CALL ALLOCATE(CHI0)
  PSI0 = PSI
  CHI0 = CHI

  CALL ALLOCATE(W)
  CALL PROJECT(RURN, RUPN, UZN, PSI, W)
  ! CALL IDEL2(W, CHI)
  CALL IDEL2LN(W, CHI)
  CALL TOFF(B)

  CALL DEALLOCATE(W)
  CALL DEALLOCATE(RURN)
  CALL DEALLOCATE(RUPN)
  CALL DEALLOCATE(UZN)

  CALL VISC2(PSI,CHI,B,PSI0,CHI0,B0)
  CALL HYPERV(PSI,CHI,B,DT)

  CALL DEALLOCATE(PSI0)
  CALL DEALLOCATE(CHI0)
  CALL DEALLOCATE(B0)

  RETURN
  END SUBROUTINE ETD2CN
!=======================================================================

  SUBROUTINE ETD1FE(PSI, CHI, B, ETD_E, ETD_NL, SOLVER)
!=======================================================================
! [USAGE]:
! Performs a first-order "ETD1-Forward Euler" explicit predictor step.
! This takes the state U_n and calculates the intermediate state U_{n+1/2}
! by solving for the wave and advection physics. The subsequent implicit
! corrector step for diffusion is handled separately.
!
! [PARAMETERS]:
! ETD_E, ETD_NL >> (IN) Pre-computed ETD operators.
! PSI, CHI, B   >> (IN) State at time t_n.
!               >> (OUT) Overwritten with the predicted state at t_{n+1/2}.
! SOLVER (OPTIONAL) >> (INOUT) Solver object to store history variables.
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR), INTENT(INOUT)   :: PSI, CHI, B
  COMPLEX(P8), DIMENSION(4,4), INTENT(IN) :: ETD_E, ETD_NL
  TYPE(SOLVER_T), INTENT(INOUT), OPTIONAL :: SOLVER

  TYPE(SCALAR):: RURN, RUPN, UZN, BN
  TYPE(SCALAR):: RORN, ROPN, OZN
  TYPE(SCALAR):: W

  CALL ALLOCATE(RURN); CALL ALLOCATE(RUPN); CALL ALLOCATE(UZN)
  CALL ALLOCATE(RORN); CALL ALLOCATE(ROPN); CALL ALLOCATE(OZN)

  CALL CHOPSET(3)
  CALL PC2VEL(PSI,CHI,RURN,RUPN,UZN)
  CALL PC2VOR(PSI,CHI,RORN,ROPN,OZN)
  CALL CHOPSET(-3)

  ! CALCULATE NONLINEAR TERMS: U X W AND -(U.GRAD)B' 
  ! NOTES:
  ! - B REMAIN IN FFF SPACE
  ! - RURN, RUPN, UZN ARE RETURNED IN PPP SPACE
  !   AND UPDATED WITH FREESTREAM ADJUSTMENT
  ! - RORN, ROPN, OZN ARE RETURNED IN PPP SPACE
  !   AND UPDATED WITH THE NONLINEAR RESULT
  CALL BOUSSINESQ_NONLIN(B,RURN,RUPN,UZN,BN,RORN,ROPN,OZN)
  CALL ETD1_SUB(ETD_E,ETD_NL,B,RURN,RUPN,UZN,BN,RORN,ROPN,OZN)
  CALL TOFF(B)

  IF (PRESENT(SOLVER)) THEN ! SAVE NONLINEAR STATES TO SOLVER
    SOLVER%N_B = BN
    SOLVER%R_N_R = RORN
    SOLVER%R_N_P = ROPN
    SOLVER%N_Z = OZN
  ENDIF
  CALL DEALLOCATE(BN)
  CALL DEALLOCATE(RORN)
  CALL DEALLOCATE(ROPN)
  CALL DEALLOCATE(OZN)

  CALL ALLOCATE(W)
  CALL PROJECT(RURN,RUPN,UZN,PSI,W)
  ! CALL IDEL2(W, CHI)
  CALL IDEL2LN(W, CHI)

  CALL DEALLOCATE(W)
  CALL DEALLOCATE(RURN)
  CALL DEALLOCATE(RUPN)
  CALL DEALLOCATE(UZN)

  RETURN
  END SUBROUTINE ETD1FE
!=======================================================================

  SUBROUTINE RICH_ETD_KERNEL(THIS, PSI, CHI, B)
!=======================================================================
  IMPLICIT NONE
  TYPE(SOLVER_T), INTENT(INOUT) :: THIS
  TYPE(SCALAR), INTENT(INOUT)   :: PSI, CHI, B

  TYPE(SCALAR):: PSI2, CHI2, B2
  REAL(P8):: DT, HDT
  COMPLEX(P8),DIMENSION(4,4):: HETD_E, HETD_NL

  IF (.NOT.ALLOCATED(THIS%ETD_E)) THEN
    CALL MPRINT('ETD operators not initialized. Call ETD_INIT before using RICH_ETD_KERNEL.')
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SOLVER, IERR)
  ENDIF

  DT = TIM%DT
  HDT = DT*0.5D0
  CALL ETD_INIT(HETD_E, HETD_NL, HDT)

  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE(PSI2); PSI2 = PSI
  CALL ALLOCATE(CHI2); CHI2 = CHI
  CALL ALLOCATE(  B2);   B2 =   B

  ! FIRST HALF-STEP
  CALL ETD1FE(PSI2, CHI2, B2, HETD_E, HETD_NL, THIS)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  ! SECOND HALF-STEP
  CALL ETD1FE(PSI2, CHI2, B2, HETD_E, HETD_NL)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  ! FULL STEP
  CALL ETD1FE(PSI, CHI, B, THIS%ETD_E, THIS%ETD_NL)
  CALL VISC1(PSI,CHI,B,DT)
  CALL HYPERV(PSI,CHI,B,DT)

  PSI%E =(2.0D0*PSI2%E)-PSI%E
  CHI%E =(2.0D0*CHI2%E)-CHI%E
    B%E =(2.0D0*  B2%E)-  B%E

  CALL DEALLOCATE( PSI2 )
  CALL DEALLOCATE( CHI2 )
  CALL DEALLOCATE(   B2 )

  RETURN
  END SUBROUTINE RICH_ETD_KERNEL
!=======================================================================

  SUBROUTINE ETD_INIT(ETD_E, ETD_NL, DT)
!=======================================================================
! [USAGE]: 
! Pre-compute ETD operators for ETD-CN scheme.
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8), INTENT(INOUT), DIMENSION(:,:) :: ETD_E, ETD_NL
  REAL(P8) :: DT

  COMPLEX(P8), DIMENSION(4,4) :: S, J, S_INV, J_EXP, J_PHI1
  INTEGER :: I

  CALL CALC_BOUSS_DIAG(J, S, S_INV, .TRUE.)
  J_EXP  = CMPLX(0.0D0, 0.0D0, P8)
  J_PHI1 = CMPLX(0.0D0, 0.0D0, P8)
  DO I = 1, 4
    J_EXP(I,I) = EXP(J(I,I) * DT)
    IF (ABS(J(I,I)) > 1.0D-14) THEN
      J_PHI1(I,I) = (J_EXP(I,I) - 1.0D0) / J(I,I)
    ELSE
      J_PHI1(I,I) = DT
    ENDIF
  ENDDO
  ETD_E  = MATMUL(S, MATMUL(J_EXP, S_INV))
  ETD_NL = MATMUL(S, MATMUL(J_PHI1, S_INV))

  ! DIAGNOST
  IF (MPI_RANK .EQ. 0) THEN
    WRITE(*,*) 'SOLVER: ETD operators initialized for dt = ', DT
    WRITE(*,*) 'ETD_E:'
    CALL MCAT(ETD_E)
    WRITE(*,*) 'ETD_NL:'
    CALL MCAT(ETD_NL)
  ENDIF

  RETURN
  END SUBROUTINE ETD_INIT
!=======================================================================

  SUBROUTINE ETD1_SUB(ETD_E,ETD_A,B,RUR,RUP,UZ,NB,RNR,RNP,NZ)
!=======================================================================
! [USAGE]:
! APPLY 1ST ORDER EXPONENTIAL TIME DIFFERENCING SCHEME:
! L = S * J * S^-1
! E = S * exp(J*DT) * S^-1
! A = S * J^-1 * (exp(J*DT)-I) * S^-1
! U^(N+1/2) = E*U^(N) + A*N[U^(N)]
! [PARAMETERS]:
! THIS >> SOLVER OBJECT CONTAINING THE NONLINEAR STATE OF PREV STEP
!   B >> ON ENTRY, B OF CURRENT STEP
!        ON EXIT, B^(N+1/2)
! RUR >> ON ENTRY, R*U_R OF CURRENT STEP IN PPP SPACE
!        ON EXIT, R*U^(N+1/2)_R
! RUP >> ON ENTRY, R*U_P OF CURRENT STEP IN PPP SPACE
!        ON EXIT, R*U^(N+1/2)_P
!  UZ >> ON ENTRY, U_Z OF CURRENT STEP IN PPP SPACE
!        ON EXIT, U^(N+1/2)_Z
!  NB >> ON ENTRY, N_B OF CURRENT STEP IN PPP SPACE
! RNR >> ON ENTRY, R*N_R OF CURRENT STEP IN PPP SPACE
! RNP >> ON ENTRY, R*N_P OF CURRENT_STEP IN PPP SPACE
!  NZ >> ON ENTRY, N_Z OF CURRENT STEP IN PPP SPACE
! [NOTES]:
! THE LINEAR OPERATOR (L) STAYS UNCHANGED FOR THE RE-SCALED STATE
! VARIABLE [RUR, RUP, UZ, B]^T, SO E AND A MATRICES REMAIN UNCHANGED
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8), DIMENSION(4,4), INTENT(IN):: ETD_E, ETD_A
  TYPE(SCALAR),INTENT(IN):: RNR,RNP,NZ,NB
  TYPE(SCALAR),INTENT(INOUT):: RUR,RUP,UZ,B

  INTEGER:: NI, NJ, NK, II, JJ, KK
  COMPLEX(P8), DIMENSION(4,1) :: EV, AV, CV

  ! CHECK IF RUR, NB, RNR ARE IN PPP SPACE
  IF ((RUR%SPACE .NE. PPP_SPACE).OR.(NB%SPACE .NE. PPP_SPACE).OR.(RNR%SPACE .NE. PPP_SPACE)) THEN
    CALL MPRINT('ETD2_SUB: RUR, NB, RNR must be in PPP space.')
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%LEGOPERATOR, IERR)
  ENDIF

  IF (B%SPACE .NE. PPP_SPACE) CALL TOFP(B)

  IF ((RUR%LN .NE. 0.D0) .OR. (RUP%LN .NE. 0.D0) .OR. (UZ%LN .NE. 0.D0)) THEN
    WRITE(*,*) 'ETD2_SUB: RUR, RUP, UZ must have no log terms.'
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_LOGTERM, IERR)
  ENDIF

  ! ALL SCALARS ARE IN PPP SPACE AND HAVE NO LOG TERMS:
  DO II = 1,SIZE(B%E,1)
    DO JJ = 1,SIZE(B%E,2)
      DO KK = 1,SIZE(B%E,3)
        ! E*U^(N) + A*N[U^(N)]
        EV(1,1) = RUR%E(II,JJ,KK)
        EV(2,1) = RUP%E(II,JJ,KK)
        EV(3,1) = UZ%E(II,JJ,KK)
        EV(4,1) = B%E(II,JJ,KK)

        AV(1,1) = RNR%E(II,JJ,KK)
        AV(2,1) = RNP%E(II,JJ,KK)
        AV(3,1) = NZ%E(II,JJ,KK)
        AV(4,1) = NB%E(II,JJ,KK)

        CV = MATMUL(ETD_E, EV) + MATMUL(ETD_A, AV)
        RUR%E(II,JJ,KK) = CV(1,1)
        RUP%E(II,JJ,KK) = CV(2,1)
        UZ%E(II,JJ,KK) = CV(3,1)
        B%E(II,JJ,KK) = CV(4,1)
      
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE ETD1_SUB
!=======================================================================

  SUBROUTINE ETD2_SUB(THIS,B,RUR,RUP,UZ,NB,RNR,RNP,NZ)
!=======================================================================
! [USAGE]:
! APPLY EXPONENTIAL TIME DIFFERENCING SCHEME:
! L = S * J * S^-1
! E = S * exp(J*DT) * S^-1
! A = (3/2) * S * J^-1 * (exp(J*DT)-I) * S^-1
! B = (1/2) * S * J^-1 * (exp(J*DT)-I) * S^-1
! U^(N+1/2) = E*U^(N) + A*N[U^(N)] - B*N[U^(N-1)]
! [PARAMETERS]:
! THIS >> SOLVER OBJECT CONTAINING THE NONLINEAR STATE OF PREV STEP
!   B >> ON ENTRY, B OF CURRENT STEP
!        ON EXIT, B^(N+1/2)
! RUR >> ON ENTRY, R*U_R OF CURRENT STEP IN PPP SPACE
!        ON EXIT, R*U^(N+1/2)_R
! RUP >> ON ENTRY, R*U_P OF CURRENT STEP IN PPP SPACE
!        ON EXIT, R*U^(N+1/2)_P
!  UZ >> ON ENTRY, U_Z OF CURRENT STEP IN PPP SPACE
!        ON EXIT, U^(N+1/2)_Z
!  NB >> ON ENTRY, N_B OF CURRENT STEP IN PPP SPACE
! RNR >> ON ENTRY, R*N_R OF CURRENT STEP IN PPP SPACE
! RNP >> ON ENTRY, R*N_P OF CURRENT_STEP IN PPP SPACE
!  NZ >> ON ENTRY, N_Z OF CURRENT STEP IN PPP SPACE
!=======================================================================
  IMPLICIT NONE
  TYPE(SOLVER_T),INTENT(IN):: THIS
  TYPE(SCALAR),INTENT(IN):: RNR,RNP,NZ,NB
  TYPE(SCALAR),INTENT(INOUT):: RUR,RUP,UZ,B

  INTEGER:: NI, NJ, NK, II, JJ, KK
  COMPLEX(P8), DIMENSION(4,1) :: EV, ABV, CV

  ! CHECK IF RUR, NB, RNR ARE IN PPP SPACE
  IF ((RUR%SPACE .NE. PPP_SPACE).OR.(NB%SPACE .NE. PPP_SPACE).OR.(RNR%SPACE .NE. PPP_SPACE)) THEN
    CALL MPRINT('ETD2_SUB: RUR, NB, RNR must be in PPP space.')
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%LEGOPERATOR, IERR)
  ENDIF

  IF (B%SPACE .NE. PPP_SPACE) CALL TOFP(B)

  IF ((RUR%LN .NE. 0.D0) .OR. (RUP%LN .NE. 0.D0) .OR. (UZ%LN .NE. 0.D0)) THEN
    WRITE(*,*) 'ETD2_SUB: RUR, RUP, UZ must have no log terms.'
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_LOGTERM, IERR)
  ENDIF

  ! ALL SCALARS ARE IN PPP SPACE AND HAVE NO LOG TERMS:
  DO II = 1,SIZE(B%E,1)
    DO JJ = 1,SIZE(B%E,2)
      DO KK = 1,SIZE(B%E,3)
        ! E*U^(N) + A*N[U^(N)] - B*N[U^(N-1)]
        EV(1,1) = RUR%E(II,JJ,KK)
        EV(2,1) = RUP%E(II,JJ,KK)
        EV(3,1) = UZ%E(II,JJ,KK)
        EV(4,1) = B%E(II,JJ,KK)

        ABV(1,1) = (3.0D0/2.0D0)*RNR%E(II,JJ,KK) - (1.0D0/2.0D0)*THIS%R_N_R%E(II,JJ,KK)
        ABV(2,1) = (3.0D0/2.0D0)*RNP%E(II,JJ,KK) - (1.0D0/2.0D0)*THIS%R_N_P%E(II,JJ,KK)
        ABV(3,1) = (3.0D0/2.0D0)*NZ%E(II,JJ,KK) - (1.0D0/2.0D0)*THIS%N_Z%E(II,JJ,KK)
        ABV(4,1) = (3.0D0/2.0D0)*NB%E(II,JJ,KK) - (1.0D0/2.0D0)*THIS%N_B%E(II,JJ,KK)

        CV = MATMUL(THIS%ETD_E, EV) + MATMUL(THIS%ETD_NL, ABV)
        RUR%E(II,JJ,KK) = CV(1,1)
        RUP%E(II,JJ,KK) = CV(2,1)
        UZ%E(II,JJ,KK) = CV(3,1)
        B%E(II,JJ,KK) = CV(4,1)
      
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE ETD2_SUB
!=======================================================================
!============================ SUBROUTINES ==============================
!=======================================================================
  SUBROUTINE ADAMSB(PSI,CHI,B,PSINO,CHINO,BNO)
!=======================================================================
! [USAGE]: 
! UPDATE POLOIDAL-TOROIDAL TERMS OF THE VELOCITY FIELD BY 1 TIME STEP
! USING ADAMS-BASHFORTH METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSINO >> NONLINEAR COMPONENT OF THE TOROIDAL TERM IN THE PREVIOUS STEP
! CHINO >> NONLINEAR COMPONENT OF THE POLOIDAL TERM IN THE PREVIOUS STEP
! BNO   >> NONLINEAR COMPONENT OF THE DENSITY  TERM IN THE PREVIOUS STEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. NONLIN(~) @ MOD_LEGOPS
! 3. VISC2(~) @ MOD_MARCH
! 4. HYPERV(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSINO,CHINO,BNO
  TYPE(SCALAR):: PSIN,CHIN,BN

  TYPE(SCALAR):: PSI0,CHI0,B0
  REAL(P8):: DT

  DT = TIM%DT
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE( PSIN )
  CALL ALLOCATE( CHIN )
  CALL ALLOCATE(   BN )

  ! CALL NONLIN(PSI,CHI,PSIN,CHIN)
  CALL BOUSSINESQ_FULL(PSI,CHI,B,PSIN,CHIN,BN)

  CALL ALLOCATE( PSI0 )
  CALL ALLOCATE( CHI0 )
  CALL ALLOCATE(   B0 )

  PSI0 = PSI
  CHI0 = CHI
  B0 = B

  PSI%E = PSI%E +DT*(1.5D0*PSIN%E -0.5D0*PSINO%E)
  CHI%E = CHI%E +DT*(1.5D0*CHIN%E -0.5D0*CHINO%E)
    B%E =   B%E +DT*(1.5D0*  BN%E -0.5D0*  BNO%E)

  PSINO=PSIN
  CHINO=CHIN
    BNO=BN

  CALL DEALLOCATE( PSIN )
  CALL DEALLOCATE( CHIN )
  CALL DEALLOCATE(   BN )

  CALL VISC2(PSI,CHI,B,PSI0,CHI0,B0)
  CALL HYPERV(PSI,CHI,B,DT)

  CALL DEALLOCATE( PSI0 )
  CALL DEALLOCATE( CHI0 )
  CALL DEALLOCATE(   B0 )

  RETURN
  END SUBROUTINE ADAMSB
!=======================================================================

  SUBROUTINE RICH(PSI,CHI,B,PSIN,CHIN,BN)
!=======================================================================
! [USAGE]: 
! UPDATE POLOIDAL-TOROIDAL TERMS OF THE VELOCITY FIELD BY 1 TIME STEP
! USING RICHARDSON EXTRAPOLATION
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSIN >> NONLINEAR COMPONENT OF THE TOROIDAL TERM
! CHIN >> NONLINEAR COMPONENT OF THE POLOIDAL TERM
! BN   >> NONLINEAR COMPONENT OF THE DENSITY TERM
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. NONLIN(~) @ MOD_LEGOPS
! 3. VISC1(~) @ MOD_MARCH
! 4. HYPERV(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSIN,CHIN,BN

  TYPE(SCALAR):: PSI2,CHI2,B2
  TYPE(SCALAR):: P_N,C_N,B_N
  REAL(P8):: DT, HDT

  DT = TIM%DT
  HDT = DT*0.5D0
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE(PSI2)
  CALL ALLOCATE(CHI2)
  CALL ALLOCATE(  B2)

  ! FIRST HALF-STEP
  ! CALL NONLIN(PSI,CHI,PSIN,CHIN)
  ! CALL BOUSSINESQ(PSI,CHI,B,PSIN,CHIN,BN)
  call BOUSSINESQ_FULL(PSI,CHI,B,PSIN,CHIN,BN)

  PSI2%E =PSI%E + (HDT*PSIN%E)
  CHI2%E =CHI%E + (HDT*CHIN%E)
    B2%E =  B%E + (HDT*  BN%E)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  CALL ALLOCATE( P_N )
  CALL ALLOCATE( C_N )
  CALL ALLOCATE( B_N )

  ! SECOND HALF-STEP
  ! CALL NONLIN(PSI2,CHI2,P_N,C_N)
  ! CALL BOUSSINESQ(PSI2,CHI2,B2,P_N,C_N,B_N)
  CALL BOUSSINESQ_FULL(PSI2,CHI2,B2,P_N,C_N,B_N)

  PSI2%E =PSI2%E + (HDT*P_N%E)
  CHI2%E =CHI2%E + (HDT*C_N%E)
    B2%E =  B2%E + (HDT*B_N%E)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  ! FULL STEP
  PSI%E =PSI%E +(DT)*PSIN%E
  CHI%E =CHI%E +(DT)*CHIN%E
    B%E =  B%E +(DT)*  BN%E

  CALL VISC1(PSI,CHI,B,DT)
  CALL HYPERV(PSI,CHI,B,DT)

  PSI%E =(2.0D0*PSI2%E)-PSI%E
  CHI%E =(2.0D0*CHI2%E)-CHI%E
    B%E =(2.0D0*  B2%E)-  B%E

  CALL DEALLOCATE( PSI2 )
  CALL DEALLOCATE( CHI2 )
  CALL DEALLOCATE(   B2 )
  CALL DEALLOCATE( P_N )
  CALL DEALLOCATE( C_N )
  CALL DEALLOCATE( B_N )

  RETURN
  END SUBROUTINE RICH
!=======================================================================

  SUBROUTINE EULER(PSI,CHI,B,PSIN,CHIN,BN)
!=======================================================================
! [USAGE]: 
! UPDATE POLOIDAL-TOROIDAL TERMS OF THE VELOCITY FIELD BY 1 TIME STEP
! USING FORWARD EULER METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSIN >> NONLINEAR COMPONENT OF THE TOROIDAL TERM
! CHIN >> NONLINEAR COMPONENT OF THE POLOIDAL TERM
! BN   >> NONLINEAR COMPONENT OF THE DENSITY TERM
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. NONLIN(~) @ MOD_LEGOPS
! 3. VISC1(~) @ MOD_MARCH
! 4. HYPERV(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSIN,CHIN,BN

  REAL(P8):: DT

  DT = TIM%DT
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  ! CALL NONLIN(PSI,CHI,PSIN,CHIN)
  ! CALL BOUSSINESQ(PSI,CHI,B,PSIN,CHIN,BN)
  CALL BOUSSINESQ_FULL(PSI,CHI,B,PSIN,CHIN,BN)

  PSI%E =PSI%E + (DT*PSIN%E)
  CHI%E =CHI%E + (DT*CHIN%E)
    B%E =  B%E + (DT*  BN%E)

  CALL VISC1(PSI,CHI,B,DT)
  CALL HYPERV(PSI,CHI,B,DT)

  RETURN
  END SUBROUTINE EULER
!=======================================================================

  SUBROUTINE VISC1(PSI,CHI,B,DT)
!=======================================================================
! [USAGE]: 
! UPDATE TOROIDAL TERMS OF THE VELOCITY FIELD WITH REGARD TO VISCOSITY
! USING BACKWARD (IMPLICIT) EULER METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! DT >> TIMESTEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. IHELM(~) @ MOD_LEGOPS
! [NOTES]:
! THE FOLLOWING FORMULA IS UTILIZED TO UPDATE PSI.
!     PSI(1)-PSI(0)
!     ------------- = VISCNU(DEL2)(PSI(1))
!           DT
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B
  REAL(P8):: DT

  TYPE(SCALAR):: WK1
  REAL(P8):: ALP

  IF(VISC%SW.NE.1) RETURN

  IF(VISC%NU.EQ.0.0) THEN
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'VISC: VISC%NU CAN''T BE ZERO'
    STOP
  ENDIF

  CALL ALLOCATE( WK1,FFF_SPACE )
  ALP=1/(VISC%NU*DT)

  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) WK1%LN=-ALP*PSI%LN
  WK1%E =-ALP*PSI%E
  CALL IHELM(WK1,PSI,ALP)

  IF ((CHI%INTH.EQ.0).AND.(CHI%INX.EQ.0)) WK1%LN=-ALP*CHI%LN
  WK1%E =-ALP*CHI%E
  CALL IHELM(WK1,CHI,ALP)

  IF(BSNSQ%KAPPA .NE. 0.D0) THEN
    
    ALP=1/(BSNSQ%KAPPA)

    IF ((B%INTH.EQ.0).AND.(B%INX.EQ.0)) WK1%LN=-ALP*B%LN
    WK1%E =-ALP*B%E
    CALL IHELM(WK1,B,ALP)

  ENDIF

  CALL DEALLOCATE( WK1 )

  RETURN
  END SUBROUTINE VISC1
!=======================================================================

  SUBROUTINE VISC2(PSI,CHI,B,PSIO,CHIO,BO)
!=======================================================================
! [USAGE]: 
! UPDATE TOROIDAL TERMS OF THE VELOCITY FIELD WITH REGARD TO VISCOSITY
! USING CRANK-NICHOLSON (IMPLICIT) METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! PSIO >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A PREVIOUS STEP
! CHIO >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A PREVIOUS STEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. CHOPSET(~) @ MOD_SCALAR3
! 3. CHOPDO(~) @ MOD_SCALAR3
! 4. DEL2(~) @ MOD_LEGOPS
! 5. IHELM(~) @ MOD_LEGOPS
! [NOTES]:
! THE FOLLOWING FORMULA IS UTILIZED TO UPDATE PSI.
!    PSI(1)-PSI(1/2)               PSI(1)+PSI(0)
!    ------------- = VISCNU(DEL2)(--------------)
!          DT                            2
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSIO,CHIO,BO

  TYPE(SCALAR):: WK1
  REAL(P8):: ALP

  IF(VISC%SW.NE.1) RETURN

  IF(VISC%NU .EQ. 0.D0) THEN
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'VISC: VISC%NU CANNOT BE ZERO'
    STOP
  ENDIF

  CALL ALLOCATE( WK1 )

  ALP=2/VISC%NU/TIM%DT

  CALL CHOPSET(2)
  CALL DEL2(PSIO,WK1)
  CALL CHOPSET(-2)
  CALL CHOPDO(WK1)

  WK1%E = -WK1%E-ALP*PSI%E
  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) WK1%LN= -ALP*PSI%LN
  CALL IHELM(WK1,PSI,ALP)

  CALL CHOPSET(2)
  CALL DEL2(CHIO,WK1)
  CALL CHOPSET(-2)
  CALL CHOPDO(WK1)

  WK1%E = -WK1%E-ALP*CHI%E
  IF ((CHI%INTH.EQ.0).AND.(CHI%INX.EQ.0)) WK1%LN= -ALP*CHI%LN
  CALL IHELM(WK1,CHI,ALP)

  IF (BSNSQ%KAPPA .NE. 0.D0) THEN

    ALP=2/BSNSQ%KAPPA/TIM%DT

    CALL CHOPSET(2)
    CALL DEL2(BO,WK1)
    CALL CHOPSET(-2)
    CALL CHOPDO(WK1)

    WK1%E = -WK1%E-ALP*B%E
    IF ((B%INTH.EQ.0).AND.(B%INX.EQ.0)) WK1%LN= -ALP*B%LN
    CALL IHELM(WK1,B,ALP)

  ENDIF

  CALL DEALLOCATE( WK1 )

  RETURN
  END SUBROUTINE VISC2
!=======================================================================
  SUBROUTINE HYPERV(PSI,CHI,B,DT)
!=======================================================================
! [USAGE]: 
! DUMP HYPERVISCOSITY TO THE HIGHER ORDER COEFFICIENTS
! OPERATES ONLY WHEN VISC%SW = 2
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! DT >> TIMESTEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. IHELMP(~) @ MOD_LEGOPS
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B
  REAL(P8):: DT
  
  TYPE(SCALAR):: W
  REAL(P8):: ALP,BET
  INTEGER:: PH

  IF(VISC%SW.EQ.0) THEN
    IF ((MPI_RANK.EQ.0).AND.(MOD(tim%n,diagv%it1).eq.0)) WRITE(6,*) 'HYPERV: WARNING: NO DISSIPATION AT ALL.'
  ELSEIF(VISC%SW.EQ.2) THEN
    CALL ALLOCATE( W )
    PH = VISC%P/2
    ALP = 1/DT/VISC%NUP *(-1)**PH
    BET = -(-1)**PH*VISC%NU/VISC%NUP

    W%E = ALP*PSI%E
    IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) W%LN = ALP*PSI%LN
    CALL IHELMP(VISC%P,W,PSI,-ALP,BET)
    
    W%E = ALP*CHI%E
    IF ((CHI%INTH.EQ.0).AND.(CHI%INX.EQ.0)) W%LN = ALP*CHI%LN
    CALL IHELMP(VISC%P,W,CHI,-ALP,BET)

    ! DENSITY???
    ALP = 1/DT/BSNSQ%KAPPAP *(-1)**PH
    BET = -(-1)**PH*BSNSQ%KAPPA/BSNSQ%KAPPAP

    W%E = ALP*B%E
    IF ((B%INTH.EQ.0).AND.(B%INX.EQ.0)) W%LN = ALP*B%LN
    CALL IHELMP(VISC%P,W,B,-ALP,BET) ! USE THE SAME POWER AS HYPERV'S P

    CALL DEALLOCATE( W )

  ENDIF

  RETURN
  END SUBROUTINE HYPERV
!=======================================================================
  SUBROUTINE DIAGNOST(PSI,CHI)
!=======================================================================
! [USAGE]: 
! PERFORM DIAGNOSIS ON THE POLOIDAL-TOROIDAL TERMS PSI AND CHI
! NOTE THAT BOTH PSI AND CHI MUST BE IN FFF SPACE
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. CHOPSET(~) @ MOD_SCALAR3
! 3. INTEG(~)   @ MOD_SCALAR3
! 4. RTRAN(~)   @ MOD_SCALAR3
! 5. PC2VEL(~)  @ MOD_LEGOPS
! 6. PC2VOR(~)  @ MOD_LEGOPS
! 7. XXDX(~)    @ MOD_LEGOPS
! 8. DELSQH(~)  @ MOD_LEGOPS
! 9. DEL2(~)    @ MOD_LEGOPS
! 10. MULXM(~)  @ MOD_LEGOPS
! 11. CALCXY(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR),INTENT(IN):: PSI,CHI

  TYPE(SCALAR):: RUR,RUP,UZH
  TYPE(SCALAR):: ROR,ROP,OZH
  ! COMPLEX(P8),DIMENSION(NXCHOPDIM):: PSIAT1,CHIAT1
  COMPLEX(P8),DIMENSION(:),ALLOCATABLE:: PSIAT1,CHIAT1
  REAL(P8):: ENE1,ENE2,VALVOR,VALZMO,VALANG,VALENE,HEL1,VALHEL,PSI_CHECK
  REAL(P8):: PAT1MAX,PAT1MIN,CAT1MAX,CAT1MIN
  INTEGER:: NN,MM,KK,NNMAX,MMMAX,KKMAX

  ! --------------------
  ! CHECK INITIALIZATION
  ! --------------------
  IF(TIM%N.NE.0 .AND. (.NOT. DIAGV%IS_INITIALIZED)) THEN
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'DIAG: WARNING:INITIALIZE INCOMPLETE !!'
  ENDIF

  ! ----------
  ! NORM CHECK
  ! ----------
  ! CHECK IF (M = 0, K = 0) MODE HAS PURELY REAL SPECTRAL COEFF (FFF),
  ! WHICH IS NECESSARY FOR PURELY REAL PHYSICAL FIELDS (PSI AND CHI).
  ! NOTE THAT THE 1ST MLEGS IS A CONSTANT, SO WE USE 2ND RADIAL MODES.
  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) THEN
    IF(ABS(AIMAG(PSI%E(2,1,1))+AIMAG(CHI%E(2,1,1))).GT.1E-18) THEN
      WRITE(6,*) 'DIAG: NORM INCOMPLETE !!!'
      WRITE(6,*) '  PSI%E(2,1,1)=',PSI%E(2,1,1)
      WRITE(6,*) '  CHI%E(2,1,1)=',CHI%E(2,1,1)
      WRITE(6,*) ''
    ENDIF
  ENDIF

  ! ----------------
  ! DEALIASING CHECK
  ! ----------------
  ! CHECK IF RADIAL MODES BEYOND NRCHOPS ARE ZERO
  PSI_CHECK = 0.D0
  IF (PSI%INTH .EQ. 0) THEN
    IF (SIZE(PSI%E, 2) .GE. 2) THEN
      PSI_CHECK = MAXVAL(ABS(PSI%E(NRCHOPS(1)+1:, 1, :))) + &
                  MAXVAL(ABS(PSI%E(NRCHOPS(2)+1:, 2, :)))
    ELSE
      PSI_CHECK = MAXVAL(ABS(PSI%E(NRCHOPS(1)+1:, 1, :)))
    END IF
  ELSEIF (PSI%INTH .EQ. 1) THEN
    PSI_CHECK = MAXVAL(ABS(PSI%E(NRCHOPS(2)+1:, 1, :)))
  END IF
  IF (PSI_CHECK .GT. 1.0D-12) THEN
    WRITE(*,*) 'DIAG: DEALIASING INCOMPLETE on rank ', MPI_RANK, ' (PSI_CHECK =', PSI_CHECK, ')'
    CALL SPY(PSI%E(:, 1, :))
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_DEALIASING, IERR)
  END IF

  ! ----------------------------
  ! CALCULATION DIVERGENCE CHECK
  ! ----------------------------
  PSI_CHECK = 0.D0
  IF ((PSI%INTH.LE.6).AND.(PSI%INX.LE.5)) THEN
    KKMAX = MIN(5-PSI%INX,SIZE(PSI%E,3)) !NXCHOPDIM)
    MMMAX = MIN(6-PSI%INTH,SIZE(PSI%E,2)) !NTCHOP)
    NNMAX = MIN(5,NRCHOP)
    DO KK=1,KKMAX
      DO MM=2,MMMAX
        DO NN=1,NNMAX
          IF(ABS(PSI%E(NN,MM,KK)).GT.100.) THEN
            PSI_CHECK = 1.0
            WRITE(6,'(A,1P,E12.5,A,I6,A,I3,A,I3,A,1P,E12.5)') &
              'DIAG: DIVERGENCE @ t=', TIM%T, ' step=', TIM%N, &
              ' (n,m,k)=(', NN, ',', MM + PSI%INTH, ',', KK + PSI%INX, ') val=', PSI%E(NN, MM, KK)
          ENDIF
        ENDDO
      ENDDO
    ENDDO
  ENDIF
  CALL MPI_BARRIER(MPI_COMM_IVP, IERR)
  IF (PSI_CHECK .GT. 0.0) THEN
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_DIVERGENCE, IERR)
  ENDIF

  ! --------------
  ! MAIN DIAGNOSIS 
  ! --------------

  IF(MOD(TIM%N,DIAGV%IT1).EQ.0) THEN
    CALL ALLOCATE( RUR )
    CALL ALLOCATE( RUP )
    CALL ALLOCATE( UZH )
    CALL ALLOCATE( ROR )
    CALL ALLOCATE( ROP )
    CALL ALLOCATE( OZH )

    CALL CHOPSET(3)

    CALL PC2VEL(PSI,CHI,RUR,RUP,UZH,'H') ! RUR, RUP, UZ/(1-X)^2
    CALL PC2VOR(PSI,CHI,ROR,ROP,OZH,'H') ! ROR, ROP, OZ/(1-X)^2

    !> Z-DIR VORTICITY 
    VALVOR= INTEG(OZH)

    !> Z-DIR MOMENTUM 
    VALZMO= INTEG(UZH)

    !> ANGULAR MOMENTUM 
    RUR=PSI
    RUR%LN=0
    CALL XXDX(RUR,RUP)
    VALANG = -INTEG(RUP) ! TODO: THIS IS INCORRECT SINCE IT INTEGRATES (1-X)^2*RDR[PSI]

    !> KINETIC ENERGY P157
    ! NOTE:
    ! PSI AND CHI CONTAINS LOG TERMS, FOR ENE2, THE LOG TERMS ARE FULLY CONSIDERED IN DEL2 AND DELSQH
    ! HOWEVER, FOR ENE1, WHILE DELSQH CONTAINS THE LOG TERM, ITS DOT PRODUCT WITH PSI DID NOT CONSIDER
    ! THE LOG TERM IN PSI, SO WE NEED TO DO IT MANUALLY.
    ! 
    ! WE NOTE THAT INT[DEL2(PSI%E+PSI%LN)*DELSQH(PSI%E+PSI%LN)] 
    ! = INT[DEL2(PSI%E)*DELSQH(PSI%E+PSI%LN)] + INT[DEL2(PSI%LN)*DELSQH(PSI%E+PSI%LN)]
    ! IF WE DID NOT MODIFY THE ORIGINAL LOG TERM, ENE1 WOULD ONLY CONTAIN THE FIRST TERM
    ! 
    ! NOW, BECAUSE PSI%LN IS PURELY RADIAL, THE VOLUME INTEGRAL OF ITS PRODUCT WITH DELSQH(PSI%E+PSI%LN)
    ! WILL ONLY CONTAIN THE RADIAL PART, SO
    ! DEL2(PSI%LN)*DELSQH(PSI%E) 
    ! = DEL2(PSI%LN)*DEL2(PSI%E+PSI%LN)
    ! = DIV[PSI%LN*GRAD(PSI%E+PSI%LN)-(PSI%E+PSI%LN)*GRAD(PSI%LN)] + (PSI%E+PSI%LN)*DEL2(PSI%LN)
    ! THE INTEGRATION OF A DIV TERM IS ZERO, SO WE ONLY NEED TO CONSIDER THE SECOND TERM, SO
    ! = PSI%E*DELSQH(PSI%LN) + PSI%LN*DELSQH(PSI%LN)
    ! THEREFORE, 
    ! INT[DEL2(PSI%E+PSI%LN)*DELSQH(PSI%E+PSI%LN)]
    ! = INT[DEL2(PSI%E)*DELSQH(PSI%E+2*PSI%LN)] + INT[PSI%LN*DELSQH(PSI%LN)]
    ! THE SECOND TERM REPRESENTS THE SELF-ENERGY OF THE LOGARITHMIC TERM. HOWEVER, THE ENERGY OF THE
    ! CORRESPONDING VELOCITY FIELD DIVERGES AS R GOES TO INFTY, AND WE EXCLUDE THIS CONTRIBUTION WHILE
    ! STILL CONSIDERING THE CROSS TERM BETWEEN THE REST OF THE VELOCITY FIELD AND THE LOG TERM.
    RUP=PSI
    IF ((RUP%INTH.EQ.0).AND.(RUP%INX.EQ.0)) RUP%LN=2*RUP%LN
    CALL DELSQH(RUP,RUR) ! RUR = DELSQH(PSI)/(1-X)^2
    CALL RTRAN(RUR,1)
    RUP=PSI
    RUP%LN=0.D0
    CALL RTRAN(RUP,1)
    ENE1= PRODCT(RUR,RUP) ! PRODCT(A,B) CALCULATES THE PRODUCT OF A*B*(1-X)^2 AND INTEGRATES OVER THE DOMAIN

    CALL DEL2(CHI,RUP)
    CALL RTRAN(RUP,1)
    CALL DELSQH(CHI,RUR)
    CALL RTRAN(RUR,1)
    ENE2= PRODCT(RUR,RUP)
    VALENE = -ENE1+ENE2 ! PRODCT uses MPI_ALLREDUCE

    !> HELICITY P157
    CALL DELSQH(PSI,RUR)
    CALL RTRAN(RUR,1)
    HEL1 =PRODCT(RUR,RUP)
    VALHEL = 2*HEL1
    CALL DEALLOCATE( RUR )
    CALL DEALLOCATE( RUP )
    CALL DEALLOCATE( UZH )

    !> STORE THE INITIAL VALUES
    IF(TIM%N .EQ.0) THEN
      DIAGV%IS_INITIALIZED = .TRUE.
      DIAGV%VORI = VALVOR
      DIAGV%ZMOMI = VALZMO
      DIAGV%ENEI = VALENE
      DIAGV%HELI = VALHEL
      DIAGV%ANGI = VALANG
    ENDIF

    IF (MPI_RANK.EQ.0) THEN
      WRITE(*,*) '<<< DIAGNOSTICS >>>'
      WRITE(6,60) TIM%T,TIM%N
60     FORMAT('TIM%T=',E13.4,' TIM%N=',I8)
      WRITE(6,62) ADV%X,ADV%Y
62     FORMAT('ADV%X=',E13.5,'  ADV%Y=',E13.5)
70     FORMAT(A12,'=',E23.15, '  FRACTIONAL CHANGE=',E23.15)
    ENDIF

    IF (PSI%INTH.EQ.0) THEN ! PROCS WITH M=0 MODES
      ALLOCATE(PSIAT1(SIZE(PSI%E,3)),CHIAT1(SIZE(CHI%E,3)))
      PSIAT1= CALCAT1(PSI)
      CHIAT1= CALCAT1(CHI)
      PAT1MAX = MAXVAL(ABS(PSIAT1))
      PAT1MIN = MINVAL(ABS(PSIAT1))
      CAT1MAX = MAXVAL(ABS(CHIAT1))
      CAT1MIN = MINVAL(ABS(CHIAT1))
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,PAT1MAX,1,MPI_DOUBLE_PRECISION,MPI_MAX,SUBCOMM_1,IERR)
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,PAT1MIN,1,MPI_DOUBLE_PRECISION,MPI_MIN,SUBCOMM_1,IERR)
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,CAT1MAX,1,MPI_DOUBLE_PRECISION,MPI_MAX,SUBCOMM_1,IERR)
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,CAT1MIN,1,MPI_DOUBLE_PRECISION,MPI_MIN,SUBCOMM_1,IERR)

      IF (PSI%INX.EQ.0) THEN ! PROC WITH M=0, K=0 MODE
        IF (PAT1MAX-PAT1MIN.GT.1.0E-10 .OR. &
          CAT1MAX-CAT1MIN.GT.1.0E-10) THEN
          WRITE(6,81) 'PSIAT1(KK=1)=',ABS(PSIAT1(1)),PAT1MAX-PAT1MIN
          WRITE(6,81) 'CHIAT1(KK=1)=',ABS(CHIAT1(1)),CAT1MAX-CAT1MIN
81      FORMAT(A,E18.9, ' MAXMIN=',E18.9)              
        ENDIF
      ENDIF
      DEALLOCATE(PSIAT1,CHIAT1)
    ENDIF

    IF (MPI_RANK.EQ.0) THEN
      WRITE(6,*) 'CFL#=',CFL*TIM%DT

      IF(DIAGV%VORI.NE.0.0) THEN
        WRITE(6,70) 'VORTICITY',VALVOR,(VALVOR-DIAGV%VORI)&
                                      /DIAGV%VORI
      ELSE
        WRITE(6,70) 'VORTICITY',VALVOR
      ENDIF

      IF(DIAGV%ZMOMI.NE.0.0) THEN
        WRITE(6,70) 'Z-MOMENTUM',VALZMO,(VALZMO-DIAGV%ZMOMI)&
                                        /DIAGV%ZMOMI
      ELSE
        WRITE(6,70) 'Z-MOMENTUM',VALZMO
      ENDIF

      WRITE(6,70) 'ENERGY',VALENE,-(DIAGV%ENEI-VALENE)/DIAGV%ENEI

      IF(DIAGV%HELI.NE.0.0) THEN
        WRITE(6,70) 'HELICITY',VALHEL,-(DIAGV%HELI-VALHEL)&
                                      /DIAGV%HELI
      ELSE
        WRITE(6,70) 'HELICITY',VALHEL
      ENDIF

      IF(DIAGV%ANGI.NE.0.0) THEN
      WRITE(6,70) 'INTEG_ANGMOM ',VALANG,-(DIAGV%ANGI-VALANG)&
                                          /DIAGV%ANGI
      ELSE
        WRITE(6,70) 'INTEG_ANGMOM ',VALANG
      ENDIF
    ENDIF

    CALL ALLOCATE(RUR)
    CALL MULXM(OZH,RUR)
    CALL MULXM(RUR,OZH)
    CALL DEALLOCATE(RUR)
    CALL CALCXY(ROR,ROP,OZH)
    CALL CHOPSET(-3)
    CALL DEALLOCATE( ROR )
    CALL DEALLOCATE( ROP )
    CALL DEALLOCATE( OZH )
  ENDIF

  RETURN
  END SUBROUTINE DIAGNOST
!=======================================================================
  SUBROUTINE CALCXY(ROR,ROP,OZH)
!=======================================================================
! [USAGE]: 
! COMPUTE THE LOCATION OF THE VORTEX (<X>,<Y>) BY WEIGHTING X AND Y
! WITH ENSTROPHY. THIS ROUTINE IS FOR MONITORING PURPOSE AND DOES NOT
! AFFECT THE NONLINEAR COMPUTATION. 
! [PARAMETERS]:
! ROR >> R*OMEGA_R TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! ROP >> R*OMEGA_P TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! OZH >> OMEGA_Z TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! [DEPENDENCIES]:
! 1. TOFP(~)      @ MOD_SCALAR3
! 2. TOFF(~)      @ MOD_SCALAR3
! 3. INTEG(~)     @ MOD_SCALAR3
! 4. ABSVEC2(~)   @ MOD_MARCH
! 5. MULRCOSTH(~) @ MOD_MARCH
! 6. MULRSINTH(~) @ MOD_MARCH
! 7. MULR2(~)     @ MOD_MARCH
! [NOTE]:
! THIS ROUTINE IS INSERTED HERE TO SAVE THE TIME FOR TRANSFORMS THAT
! WOULD HAPPEN IF THIS ROUTINE WERE CALLED FROM SUBROUTINE DIAG.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: ROR,ROP,OZH

  REAL(P8):: VALENS,VALX,VALY,VALR

  IF (MPI_RANK.EQ.0) OPEN(UNIT=14,FILE=TRIM(ADJUSTL(FILES%SAVEDIR))//'coresize.dat',POSITION='APPEND')

  CALL TOFP(ROR)
  CALL TOFP(ROP)
  CALL TOFP(OZH)
  CALL ABSVEC2(ROR,ROP,OZH,OZH)

  ROR=OZH
  CALL TOFF(ROR)
  VALENS=INTEG(ROR)

  ROR=OZH
  CALL MULRCOSTH(ROR)
  CALL TOFF(ROR)
  VALX=INTEG(ROR)/VALENS

  ROR=OZH
  CALL MULRSINTH(ROR)
  CALL TOFF(ROR)
  VALY=INTEG(ROR)/VALENS

  ROR=OZH
  CALL MULR2(ROR)
  CALL TOFF(ROR)
  VALR=SQRT(INTEG(ROR)/VALENS)

  IF (MPI_RANK.EQ.0) THEN
    WRITE(6,60) TIM%T,VALX,VALY,VALR
    WRITE(14,'(4E14.6)') TIM%T,VALX,VALY,VALR
    CLOSE(14)
60   FORMAT('T= ',E10.3,' <X>= ',E10.3,' <Y>= ',E10.3,' <R>= ',E10.3)
  ENDIF

  IF(TIM%N.EQ.0) THEN
    ADV%T0=TIM%T-TIM%DT
    ADV%X0=VALX
    ADV%Y0=VALY
    ADV%T1=TIM%T
    ADV%X1=ADV%X0
    ADV%Y1=ADV%Y0
  ELSE
    ADV%T0=ADV%T1
    ADV%X0=ADV%X1
    ADV%Y0=ADV%Y1
    ADV%T1=TIM%T
    ADV%X1=VALX
    ADV%Y1=VALY
  ENDIF

  RETURN
  END SUBROUTINE CALCXY
!=======================================================================
  SUBROUTINE ABSVEC2(U,V,W,A)
!=======================================================================
! [USAGE]: 
! COMPUTE THE LOCATION OF THE VORTEX (<X>,<Y>) BY WEIGHTING X AND Y
! WITH ENSTROPHY. THIS ROUTINE IS FOR MONITORING PURPOSE AND DOES NOT
! AFFECT THE NONLINEAR COMPUTATION. 
! [PARAMETERS]:
! U >> R*U_R TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! V >> R*U_PHI TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! W >> U_Z TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! A >> ON ENTRY, STORES THE ADVECTIVE VELOCITY INFORMATION
!      DIVIDED BY (1-X)**2.
!      PREFERABLY CHOOSE ONE OF U, V, AND W
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: U,V,W,A
  INTEGER:: I,MM,KK,NRTMP
  REAL(P8):: AAA,BBB
  REAL(P8):: RUR,RVR,WR
  REAL(P8):: RUI,RVI,WI,R,F

  NRTMP = MIN(SIZE(U%E,1),NR-U%INR)
  DO KK=1,SIZE(U%E,3) !NX
    DO MM=1,NTH
      DO I=1,NRTMP !NR
        R  = TFM%R(I+U%INR)
        F = (1-TFM%X(I+U%INR))**2
        RUR=REAL(U%E(I,MM,KK))
        RUI=AIMAG(U%E(I,MM,KK))
        RVR=REAL(V%E(I,MM,KK))
        RVI=AIMAG(V%E(I,MM,KK))
        WR=REAL(W%E(I,MM,KK))
        WI=AIMAG(W%E(I,MM,KK))
        AAA = ( (RUR**2+RVR**2)/R**2 + WR**2)
        BBB = ( (RUI**2+RVI**2)/R**2 + WI**2)
        A%E(I,MM,KK) = CMPLX(AAA,BBB,P8)/F
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE ABSVEC2
!=======================================================================
  SUBROUTINE MULRCOSTH(A)
!=======================================================================
! [USAGE]: 
! MULTIPLY R*COS(TH) TO A FIELD A; 
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE. ON EXIT, MULTIPLIED BY R*COS(TH)
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: A
  
  REAL(P8):: R,Z,THR,THI,AAA,BBB
  INTEGER:: KK,NN,MM,NRTMP
  
  CALL TOFP(A)

  NRTMP = MIN(SIZE(A%E,1),NR-A%INR)
  DO KK=1,SIZE(A%E,3) !NX
    DO MM=1,NTH
      DO NN=1,NRTMP !NR
        !Z  = TFM%Z(KK+A%INX)
        R  = TFM%R(NN+A%INR)
        THR = TFM%THR(MM)
        THI = TFM%THI(MM)
        AAA = R*COS(THR)*REAL(A%E(NN,MM,KK))
        BBB = R*COS(THI)*AIMAG(A%E(NN,MM,KK))
        A%E(NN,MM,KK)= CMPLX(AAA,BBB,P8)
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE MULRCOSTH
!=======================================================================
  SUBROUTINE MULRSINTH(A)
!=======================================================================
! [USAGE]: 
! MULTIPLY R*SIN(TH) TO A FIELD A IN PPP-SPACE
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE. ON EXIT, MULTIPLIED BY R*SIN(TH)
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: A

  REAL(P8):: R,Z,THR,THI,AAA,BBB
  INTEGER:: KK,NN,MM,NRTMP

  CALL TOFP(A)

  NRTMP = MIN(SIZE(A%E,1),NR-A%INR)
  DO KK=1,SIZE(A%E,3) !NX
    DO MM=1,NTH
      DO NN=1,NRTMP !NR
        !Z  = TFM%Z(KK+A%INX)
        R  = TFM%R(NN+A%INR)
        THR = TFM%THR(MM)
        THI = TFM%THI(MM)
        AAA = R*SIN(THR)*REAL(A%E(NN,MM,KK))
        BBB = R*SIN(THI)*AIMAG(A%E(NN,MM,KK))
        A%E(NN,MM,KK)= CMPLX(AAA,BBB,P8)
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE MULRSINTH
!=======================================================================
  SUBROUTINE MULR2(A)
!=======================================================================
! [USAGE]: 
! MULTIPLY R**2 TO A FIELD A
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE. ON EXIT, MULTIPLIED BY R**2
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: A

  REAL(P8):: R,Z,THR,THI,AAA,BBB
  INTEGER:: KK,NN,MM,NRTMP

  CALL TOFP(A)

  NRTMP = MIN(SIZE(A%E,1),NR-A%INR)
  DO KK=1,SIZE(A%E,3) !NX
    DO MM=1,NTH
      DO NN=1,NRTMP !NR
        !Z  = TFM%Z(KK+A%INX)
        R  = TFM%R(NN+A%INR)
        !THR = TFM%THR(MM)
        !THI = TFM%THI(MM)
        AAA = R**2*REAL(A%E(NN,MM,KK))
        BBB = R**2*AIMAG(A%E(NN,MM,KK))
        A%E(NN,MM,KK)= CMPLX(AAA,BBB,P8)
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE MULR2
!=======================================================================
  SUBROUTINE FREEADJ()
!=======================================================================
! [USAGE]: 
! ADJUST FREESTREAM VELOCITY SUCH THAT THE CENTER OF VORTICITY
! DISTRIBUTION IS AT THE CENTER OF THE COMPUTATIONAL DOMAIN.
! [PARAMETERS]:
! N/A
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  REAL(P8):: FREEDT,VX,VY

  FREEDT = ADV%INT*TIM%DT
  VX = (ADV%X1-ADV%X0)/(ADV%T1-ADV%T0) ! VELOCITY OF THE CENTER OF VORTEX
  VY = (ADV%Y1-ADV%Y0)/(ADV%T1-ADV%T0)
  ADV%UX = ADV%UX - ADV%X1/FREEDT - VX ! CANCEL OUT THE MOTION OF THE VORTEX CENTER
  ADV%UY = ADV%UY - ADV%Y1/FREEDT - VY
  
  NADD%U = SQRT(ADV%UX**2+ADV%UY**2) ! ADVECTIVE VELOCITY IN R-THETA PLANE
  
  IF(NADD%U.EQ.0.0) THEN
    NADD%ANG = 0.0
  ELSE
    IF(ADV%UY >= 0) THEN
      NADD%ANG = ACOS(ADV%UX/NADD%U)
    ELSE 
      NADD%ANG = -1.0*ACOS(ADV%UX/NADD%U)
    ENDIF
  ENDIF

  IF (MPI_RANK.EQ.0) THEN
    WRITE(6,60) TIM%N,TIM%T
60   FORMAT('FREEADJ: TIM%N=',I5,' TIM%T=',F10.6)
    WRITE(6,61) ADV%UX,ADV%UY,ADV%UZ
61   FORMAT('FREEADJ: ADV%UX=',E18.10,'  UY=',E18.10,' UZ=',E18.10)
    WRITE(6,62) NADD%U,NADD%ANG
62   FORMAT('FREEADJ: NADD%U=',E18.10,' ANG=',E18.10)
  ENDIF

  RETURN
  END SUBROUTINE FREEADJ
!=======================================================================
  SUBROUTINE REMOVE(PSI,CHI)
!=======================================================================
! [USAGE]: 
! KILL THE VORTICES WHICH MOVES AWAY FROM THE COMPUTATIONAL DOMAIN
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. RTRAN(~)        @ MOD_SCALAR3
! 3. CHOPSET(~)      @ MOD_SCALAR3
! 4. DELSQH(~)       @ MOD_LEGOPS
! 5. IDELSQH(~)      @ MOD_LEGOPS
! 6. DEL2(~)         @ MOD_LEGOPS
! 7. IDEL2(~)        @ MOD_LEGOPS
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI

  TYPE(SCALAR):: WK
  INTEGER:: NS,NS0,MM,KK,I
  REAL(P8):: LN

  IF(RMV%SW.EQ.1) THEN
    CALL ALLOCATE( WK )
    NS = NR*2/3 ! THE OUTSIDE 1/3 OF THE RADIAL COLLOCATION PTS ARE TOO FAR ARWAY
    NS0 = MIN(NS+4,NR)

    CALL DELSQH(PSI,WK)
    CALL RTRAN(WK,1) ! WK IN PFF SPACE

    ! WK%E(NS0:NR,2:NTCHOP,1:NX)=0
    ! IF (NX>1) WK%E(NS0:NR,1,2:NX)=0
    IF (WK%INTH.EQ.0) THEN
      WK%E(NS0:NR,2:,:)=0
      IF (NX>1) THEN
        ! IF (WK%INX.EQ.0) THEN
        !   WK%E(NS0:NR,1,2:)=0
        ! ELSE
        !   WK%E(NS0:NR,1,:)=0
        ! ENDIF
        WK%E(NS0:NR,1,MAX(2-WK%INX,1):)=0
      ENDIF
    ELSE
      WK%E(NS0:NR,:,:)=0
    ENDIF

    DO KK=1,SIZE(WK%E,3) !NX (old code's PFF contains NX pts in x-dir)
      DO MM=1,SIZE(WK%E,2) !NTCHOP
        ! IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)*TFM%W(NS:NR)
        DO I=1,5
          WK%E(NS:NR,MM,KK)=SMOOTH(WK%E(NS:NR,MM,KK))
        ENDDO
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)/TFM%W(NS:NR)
      ENDDO
    ENDDO

    CALL RTRAN(WK,-1)
    CALL IDELSQH(WK,PSI)

    CALL CHOPSET(2)
    CALL DEL2(CHI,WK)
    CALL RTRAN(WK,1)

    IF (WK%INTH.EQ.0) THEN
      WK%E(NS0:NR,2:,:)=0
      IF (NX>1) WK%E(NS0:NR,1,MAX(2-WK%INX,1):)=0
    ELSE
      WK%E(NS0:NR,:,:)=0
    ENDIF

    DO KK=1,SIZE(WK%E,3) !NX
      DO MM=1,SIZE(WK%E,2) !NTCHOP
        ! IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)*TFM%W(NS:NR) &
                                            /(1-TFM%X(NS:NR))**2
        DO I=1,5
          WK%E(NS:NR,MM,KK)=SMOOTH(WK%E(NS:NR,MM,KK))
        ENDDO
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)/TFM%W(NS:NR) &
                                            *(1-TFM%X(NS:NR))**2
      ENDDO
    ENDDO
    CALL CHOPSET(-2)
    CALL RTRAN(WK,-1)
    LN=CHI%LN
    CALL IDEL2(WK,CHI,LN)

    IF (MPI_RANK.EQ.0) WRITE(6,60) TIM%N,TFM%R(NS)
60     FORMAT('REMOVE: TIM%N=',I5,'  R >=',F6.2)

  CALL DEALLOCATE( WK )
  ELSE
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'REMOVE: RMV%SW IS SET TO 0.'
  ENDIF

  RETURN
  END SUBROUTINE REMOVE
!=======================================================================
  SUBROUTINE ENEMON(PSI,CHI,EM,EK)
!=======================================================================
! [USAGE]: 
! COMPUTE ENERGY FOR EACH AZIMUTHAL AND AXIAL WAVE NUMBER
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! EM >> ENERGY FOR EACH M (AZIMUTHAL WAVENUMBER)
! EK >> ENERGY FOR EACH K (AXIAL WAVENUMBER)
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. RTRAN(~)        @ MOD_SCALAR3
! 3. DELSQH(~)       @ MOD_LEGOPS
! 4. DEL2(~)         @ MOD_LEGOPS
! 5. PRODCT_M(~)      @ MOD_SCALAR3
! 6. PRODCT_K(~)      @ MOD_SCALAR3
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI, W1,W2
  REAL(P8):: EM(NTCHOP)
  REAL(P8),OPTIONAL:: EK(NXCHOP)

  CALL ALLOCATE(W1)
  CALL ALLOCATE(W2)

  !> ENERGY P157
  W1=PSI
  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) W1%LN=2*PSI%LN
  CALL DELSQH(W1,W2)
  CALL RTRAN(W2,1)
  W1=PSI
  W1%LN=0.D0
  CALL RTRAN(W1,1)
  EM= PRODCT_M(W2,W1)
  IF (PRESENT(EK)) THEN
  EK= PRODCT_K(W2,W1)
  END IF
  
  CALL DEL2(CHI,W1)
  CALL RTRAN(W1,1)
  CALL DELSQH(CHI,W2)
  CALL RTRAN(W2,1)
  EM= -EM+PRODCT_M(W2,W1)
  IF (PRESENT(EK)) THEN
  EK= -EK+PRODCT_K(W2,W1)
  END IF

  CALL DEALLOCATE(W1)
  CALL DEALLOCATE(W2)

  RETURN
  END SUBROUTINE ENEMON
!=======================================================================
  SUBROUTINE HYPADJ(PSI,CHI,NUP)
!=======================================================================
! [USAGE]: 
! ADJUST HYPERVISCOSITY FROM M(AZIMUTHAL)-ENERGY SPECTRUM
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! NUP >> HYPERVISCOSITY TO CONFINE THE EFFECT OF DISSIPATION
! [DEPENDENCIES]:
! 1. CHOPSET(~) @ MOD_SCALAR3
! 2. ENEMON(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI
  REAL(P8):: NUP

  REAL(P8),DIMENSION(:),ALLOCATABLE:: EM,EK
  REAL(P8),DIMENSION(:),ALLOCATABLE:: SPM,SPK

  REAL(P8):: SUMM,SUMK,FAC,DX,X,SUM,SUMO
  INTEGER:: IS,IE,NM,NK,I

  ALLOCATE( EM(NTCHOP), EK(NXCHOP) )

  CALL CHOPSET(2)
  CALL ENEMON(PSI,CHI,EM,EK)
  CALL CHOPSET(-2)

  IS = SIZE(EM)/3
  IE = SIZE(EM)-2
  NM = IE-IS+1

  ALLOCATE(SPM(NM))

  SPM = LOG10(EM(IS:IE))
  SUMM = 0
  IS = SIZE(EK)/3
  IE = SIZE(EK)
  NK = IE-IS+1

  ALLOCATE(SPK(NK))

  SPK = LOG10(EK(IS:IE))
  SUMK = 0

  DX = 2.0D0/(NM-1)                                                  ! DOT PRODUCT WITH LEGENDRE POLYNOMIAL P_2(X)
  
  DO I=1,NM
    X  = -1+2.0D0*(I-1)/(NM-1)
    FAC = 1
    IF(I.EQ.1 .OR. I.EQ.NM) FAC=0.5D0
    SUMM=SUMM+ FAC*SPM(I)*DX*SQRT(5.0D0/8)*(3*X**2-1)
  ENDDO

  DX = 2.0D0/(NK-1)

  DO I=1,NK
    X  = -1+2.0D0*(I-1)/(NK-1)
    FAC = 1
    IF(I.EQ.1 .OR. I.EQ.NK) FAC=0.5D0
    SUMK=SUMK+ FAC*SPK(I)*DX*SQRT(5.0D0/8)*(3*X**2-1)
  ENDDO

  IF(FIRST.EQ.0) THEN
    FIRST=1
    SUMMO=SUMM
    SUMKO=SUMK
    NUPB = 0.2/(1.5D0*NRCHOP**2/ELL**2)**(VISC%P/2)
  ENDIF

  IF(SUMM.GT.SUMK) THEN
    SUMO = (3*SUMMO+SUMKO)/4
    SUM  = (3*SUMM+SUMK)/4
  ELSE
    SUMO = (SUMMO+3*SUMKO)/4
    SUM  = (SUMM+3*SUMK)/4
  ENDIF

  SUM = 2*(SUM-SUMO) +SUM + 0.2
  SUM = MIN(3.0D0,MAX(-0.5D0,1.5*SUM))
  NUP = (1+SUM)*NUP
  IF(NUP.LT.NUPB) NUP=NUPB

  IF (MPI_RANK.EQ.0) WRITE(6,60) TIM%T,NUP,SUMM,SUMK
60   FORMAT('HYPADJ:T= ',1PE10.3,' NUP= ',1PE10.3,' SUMM= ', &
            1PE10.3, ' SUMK= ',1PE10.3)
  SUMMO=SUMM
  SUMKO=SUMK

  DEALLOCATE( EM, EK, SPM, SPK )

  RETURN
  END SUBROUTINE HYPADJ
! ======================================================================

SUBROUTINE HYPSET()
! ======================================================================
! CALCULATE THE HYPERVISCOSITY
! EXP[ - NUP * (FILTER * MODE # / FACTOR)^P * DT]
! ======================================================================
  IMPLICIT NONE

  REAL(P8) :: NU_R, NU_T, NU_X
  INTEGER :: NT_UP, NX_UP

  REAL(P8) :: FACTOR_NU
  INTEGER :: II, JJ
  INTEGER :: FACTOR_UP, MONITOR_K(3)
  
  REAL(P8) :: FACTOR_R, FACTOR_T, FACTOR_X
  REAL(P8) :: INDEX_R(NRCHOP), INDEX_T(NTCHOPDIM), INDEX_X(NXCHOPDIM)
  REAL(P8) :: FILTER_R(NRCHOP), FILTER_T(NTCHOPDIM), FILTER_X(NXCHOPDIM)
!  REAL(P8) :: HYPER_R(NRCHOP), HYPER_T(NTCHOPDIM), HYPER_X(NXCHOPDIM)

  FACTOR_NU = 2.D0

  FACTOR_R = 1.D0
  FACTOR_T = 0.8
  FACTOR_X = 1.D0

  ! IF PERTURBATION/DISTURBANCE SIZE IS 0.1, ITS FACTOR_UP-TH HARMONICS
  ! WILL GET BELOW MACHINE ROUND-OFF ERROR
  FACTOR_UP = 24 ! DP
  NT_UP = MIN(FACTOR_UP*MAX(MAXVAL(MONITOR_MK(1:3,1)),1),NTCHOP-1)
  DO II = 1,3
    MONITOR_K(II) = MONITOR_MK(II,2)
    IF (MONITOR_K(II).GT.NXCHOP) MONITOR_K(II) = MONITOR_K(II) + 1 - 2*NXCHOP
    MONITOR_K(II) = ABS(MONITOR_K(II))
  ENDDO
!   NX_UP = MIN(FACTOR_UP*MAX(MAXVAL(ABS(MONITOR_MK(1:3,2))),1),NXCHOP-1)
  NX_UP = MIN(FACTOR_UP*MAX(MAXVAL(MONITOR_K),1),NXCHOP-1)

  ! CREATE TANH FILTERS
  ! R: CENTER AT 1/2*NRCHOP WIDTH NRCHOP/4
  INDEX_R = (/(II, II=1,NRCHOP)/)
  FILTER_R = 0.5*(TANH((INDEX_R/REAL(NRCHOP)-1.D0/2.D0)*4.D0)+1.D0)
  ! T: CENTER AT 2/3*NT_UP WIDTH NT_UP/4
  INDEX_T = (/(II, II=0,NTCHOPDIM-1)/)
  FILTER_T = 0.5*(TANH((INDEX_T/REAL(NT_UP)-1.D0/2.D0)*5.D0)+1.D0)
  ! X: CENTER AT 2/3*NX_UP WIDTH NX_UP/4
  DO II=1,NXCHOPDIM
    INDEX_X(II) = II-1
    IF(II.GT.NXCHOP) THEN
        INDEX_X(II)=ABS(-(NXCHOPDIM-II+1))
    ENDIF
  ENDDO
  FILTER_X = 0.5*(TANH((INDEX_X/REAL(NX_UP)-1.D0/2.D0)*8.D0)+1.D0)

  ! FORCE THE LAST MODE TO DECAY AT EXP(-1*DT) WHILE ALSO USING TANH TO
  ! PREVENT CHANGES TO THE INTERESTED MODES
  NU_R = FACTOR_NU*(FACTOR_R*FILTER_R(NRCHOP))**(-VISC%P) 
  NU_T = FACTOR_NU*(FACTOR_T*FILTER_T(NTCHOPDIM))**(-VISC%P+2)
  NU_X = FACTOR_NU*(FACTOR_X*FILTER_X(NXCHOP))**(-VISC%P+2)

  ! CREATE HYPERV VECTORS
  ALLOCATE(HYPER_R(NRCHOP), HYPER_T(NTCHOPDIM), HYPER_X(NXCHOPDIM))
  HYPER_R = EXP(-(NU_R*TIM%DT)*(FILTER_R*INDEX_R/NRCHOP)**VISC%P)
  HYPER_T = EXP(-(NU_T*TIM%DT)*(FILTER_T*INDEX_T/NTCHOP)**(VISC%P-2))
  HYPER_X = EXP(-(NU_X*TIM%DT)*(FILTER_X*INDEX_X/NXCHOP)**(VISC%P-2))

   ! SAVE HYPER VECTORS
   IF (MPI_RANK.EQ.0) THEN
      open(UNIT=888,FILE='hyperv.dat',STATUS='UNKNOWN',ACTION='WRITE')
      ! write(888,518) NU_R, FILTER_R
      ! write(888,518) NU_T, FILTER_T
      ! write(888,518) NU_X, FILTER_X
      write(888,518) NU_R, HYPER_R
      write(888,518) NU_T, HYPER_T
      write(888,518) NU_X, HYPER_X
      close(888)
   518 FORMAT((E23.16),*(' ,',E23.16))
      ! CALL MPI_ABORT(MPI_COMM_WORLD,1,IERR)
   ENDIF

  RETURN
END SUBROUTINE
! ======================================================================

SUBROUTINE HYPERV3(PSI,CHI,B)
! ======================================================================
! APPLY HYPERVISCOSITY USING EXPONENTIAL SCALING
! ONLY ACTIVE WHEN VISC%SW = 3
! ======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B
  INTEGER:: MM, KK, NN

   IF (VISC%SW.EQ.3) THEN
    
      IF (.NOT.(ALLOCATED(HYPER_R))) CALL HYPSET()

      DO KK = 1,SIZE(PSI%E,3); DO MM = 1,SIZE(PSI%E,2)

         NN = NRCHOPS(MM + PSI%INTH)
         PSI%E(:NN,MM,KK) = PSI%E(:NN,MM,KK)*HYPER_R(:NN)*HYPER_T(MM+PSI%INTH)*HYPER_X(KK+PSI%INX)
         CHI%E(:NN,MM,KK) = CHI%E(:NN,MM,KK)*HYPER_R(:NN)*HYPER_T(MM+PSI%INTH)*HYPER_X(KK+PSI%INX)
           B%E(:NN,MM,KK) =   B%E(:NN,MM,KK)*HYPER_R(:NN)*HYPER_T(MM+PSI%INTH)*HYPER_X(KK+PSI%INX)

      ENDDO; ENDDO
      
   ENDIF

  RETURN
END SUBROUTINE
!=======================================================================
!============================= FUNCTIONS ===============================
!=======================================================================
!   FUNCTION PRODCT_M(A,B)
! !=======================================================================
! ! [USAGE]: 
! ! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! ! FOR EACH AZIMUTHAL WAVENUMBER.
! ! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! ! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! ! [PARAMETERS]:
! ! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! [UPDATES]:
! ! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! !=======================================================================
!   IMPLICIT NONE
!   TYPE(SCALAR):: A,B

!   COMPLEX(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NTCHOP)
!   REAL(P8),DIMENSION(NTCHOP):: PRODCT_M
!   INTEGER:: MM,KK

!   IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
!     IF (MPI_RANK.EQ.0) THEN
!       WRITE(*,*) 'PRODCT:NOT IN PFF_SPACE'
!       WRITE(*,*) 'A%SPACE,B%SPACE=',A%SPACE,B%SPACE
!     ENDIF
!     STOP
!   ENDIF

!   IF(A%LN.NE.0.0 .OR. B%LN.NE.0.0) THEN
!     IF (MPI_RANK.EQ.0) WRITE(*,*) 'PRODCT:LOGTERM NOT ZERO'
!   ENDIF

!   ALLOCATE(PROD(NR,SIZE(A%E,2)))
!   PROD=0

!   DO KK = 1,SIZE(A%E,3) !NX
!     !IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
!     DO MM = 1,SIZE(A%E,2) !NTCHOP
!       ! M = 0
!       IF (MM+A%INTH.EQ.1) THEN
!         PROD(:,1) = PROD(:,1)+A%E(:NR,1,KK)*CONJG(B%E(:NR,1,KK))
!       ! M > 0
!       ELSE
!       PROD(:,MM) = PROD(:,MM)+2*(REAL(A%E(:NR,MM,KK)) &
!                                 *REAL(B%E(:NR,MM,KK)) &
!                                 +AIMAG(A%E(:NR,MM,KK))&
!                                 *AIMAG(B%E(:NR,MM,KK)))
!       ENDIF
!     ENDDO
!   ENDDO

!   PRODCT_M = 0.D0
!   DO MM=1,SIZE(A%E,2) !NTCHOP
!     ! NOTE:
!     ! PRODCT_M IS CALCULATED DIRECTLY USING GAUSS-LEGENDRE QUADRATURE
!     ! THERE IS NO REASON BEHIND *TFM%PF(1,1,1)*TFM%NORM(1,1)
!     ! PRODCT_M(MM+A%INTH) = SUM((PROD(:,MM)*TFM%W)*TFM%PF(1,1,1))
!     ! PRODCT_M(MM+A%INTH) = 4*PI*ZLEN0*ELL2*PRODCT_M(MM+A%INTH)*TFM%NORM(1,1)
!     PRODCT_M(MM+A%INTH) = SUM(PROD(:,MM)*TFM%W)
!     PRODCT_M(MM+A%INTH) = 2*PI*ZLEN0*ELL2*PRODCT_M(MM+A%INTH)
!   ENDDO
!   CALL MPI_ALLREDUCE(MPI_IN_PLACE,PRODCT_M,NTCHOP,MPI_DOUBLE_PRECISION, &
!                   MPI_SUM, MPI_COMM_IVP, IERR)

!   DEALLOCATE(PROD)
!   RETURN
!   END FUNCTION PRODCT_M
! !=======================================================================
!   FUNCTION PRODCT_K(A,B)
! !=======================================================================
! ! [USAGE]: 
! ! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! ! FOR EACH AXIAL WAVENUMBER.
! ! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! ! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! ! [PARAMETERS]:
! ! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! [UPDATES]:
! ! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! !=======================================================================
!   IMPLICIT NONE
!   TYPE(SCALAR):: A,B

!   ! COMPLEX(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NXCHOP)
!   REAL(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NXCHOP)
!   REAL(P8),DIMENSION(NXCHOPDIM):: PRODCTK_TEMP
!   REAL(P8),DIMENSION(NXCHOP):: PRODCT_K
!   INTEGER:: MM,KK,KH,CK,CM

!   IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
!     IF (MPI_RANK.EQ.0) THEN
!       WRITE(*,*) 'PRODCT:NOT IN PFF_SPACE'
!       WRITE(*,*) 'A%SPACE,B%SPACE=',A%SPACE,B%SPACE
!     ENDIF
!     STOP
!   ENDIF

!   IF(A%LN.NE.0.0 .OR. B%LN.NE.0.0) THEN
!     IF (MPI_RANK.EQ.0) WRITE(*,*) 'PRODCT:LOGTERM NOT ZERO'
!   ENDIF

!   ALLOCATE(PROD(NR,SIZE(A%E,3)))
!   PROD=0

!   DO KK = 1,SIZE(A%E,3) !NXCHOP
!     IF(KK+A%INX.EQ.1) THEN
!       CK=2
!       KH=1
!     ELSE
!       CK=1
!       !KH=NX-KK+2
!     ENDIF

!     DO MM = 1,SIZE(A%E,2) !NTCHOP
!       CM=1
!       IF(MM+A%INTH.EQ.1) CM=2
!       ! PROD(:,KK)=PROD(:,KK)+1.0D0/CK/CM* & 
!       !            2*REAL(A%E(:NR,MM,KK)*CONJG(B%E(:NR,MM,KK)) &
!       !                   +B%E(:NR,MM,KH)*CONJG(A%E(:NR,MM,KH)))
!       PROD(:,KK)=PROD(:,KK)+1.0D0/CK/CM* & 
!                   2*REAL(A%E(:NR,MM,KK)*CONJG(B%E(:NR,MM,KK))) 
!                         !+B%E(:NR,MM,KH)*CONJG(A%E(:NR,MM,KH)))
!     ENDDO
!   ENDDO

!   PRODCTK_TEMP = 0.D0
!   DO KK=1,SIZE(A%E,3) !NXCHOP
!     ! NOTE:
!     ! THERE IS NO POINT OF *TFM%PF(1,1,1)*TFM*NORM(1,1)
!     ! PRODCT IS CALCULATED DIRECTLY USING GAUSS-LEGENDRE QUADRATURE
!     ! PRODCTK_TEMP(KK+A%INX) = SUM((PROD(:,KK)*TFM%W)*TFM%PF(1,1,1))
!     ! PRODCTK_TEMP(KK+A%INX) = 4*PI*ZLEN0*ELL2*PRODCTK_TEMP(KK+A%INX)*TFM%NORM(1,1)
!     PRODCTK_TEMP(KK+A%INX) = SUM(PROD(:,KK)*TFM%W)
!     PRODCTK_TEMP(KK+A%INX) = 2*PI*ZLEN0*ELL2*PRODCTK_TEMP(KK+A%INX)
!   ENDDO
!   CALL MPI_ALLREDUCE(MPI_IN_PLACE,PRODCTK_TEMP,NXCHOPDIM,MPI_DOUBLE_PRECISION, &
!                   MPI_SUM, MPI_COMM_IVP, IERR)

!   DO KK = 1,NXCHOP
!     KH = NXCHOPDIM - KK + 2
!     IF (KK.EQ.1) KH = 1
!     PRODCT_K(KK) = PRODCTK_TEMP(KK) + PRODCTK_TEMP(KH)
!   ENDDO

!   DEALLOCATE(PROD)
!   RETURN
!   END FUNCTION PRODCT_K
!=======================================================================
  FUNCTION SMOOTH(A)
!=======================================================================
! [USAGE]: 
! SMOOTHING A SEQUENCE A BY CONVOLUTION
! [INPUTS]:
! A >> A SEQUENCE CONTAINING NOISES
! [OUTPUTS]:
! SMOOTH >> SMOOTHENED SEQUENCE USING CONVOLUTION
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8),DIMENSION(:):: A
  COMPLEX(P8),DIMENSION(SIZE(A)):: SMOOTH

  REAL(P8),DIMENSION(3):: FAE=(/ 0.2D0, 0.3D0, 0.5D0 /)
  REAL(P8):: F
  INTEGER:: NI,I,NB,NE

  NI=SIZE(A)

  IF(NI.LT.3) THEN
    WRITE(*,*) 'SMOOTH: SIZE TOO SMALL'
    STOP
  ENDIF

  SMOOTH=0
  SMOOTH(1)=A(1)
  SMOOTH(NI-2:NI)= SMOOTH(NI-2:NI) +A(NI)*FAE

  DO I=2,NI-1
    F = (1+((NI-I)/(NI-1.0D0)))*0.5D0
    SMOOTH(I-1)= SMOOTH(I-1)+A(I)*(1-F)/2
    SMOOTH(I  )= SMOOTH(I  )+A(I)*F
    SMOOTH(I+1)= SMOOTH(I+1)+A(I)*(1-F)/2
  ENDDO

  RETURN
  END FUNCTION SMOOTH
!=======================================================================
  FUNCTION DDC(R)
!=======================================================================
! [USAGE]: 
! SMOOTHING A SEQUENCE A BY CONVOLUTION
! [INPUTS]:
! A >> A SEQUENCE CONTAINING NOISES
! [OUTPUTS]:
! SMOOTH >> SMOOTHENED SEQUENCE USING CONVOLUTION
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  REAL(P8),DIMENSION(:):: R
  REAL(P8),DIMENSION(SIZE(R),3):: DDC
  REAL(P8):: X0,X1,X2
  INTEGER:: NI,I
  NI = SIZE(R)
  DDC(1,:)=0
  DDC(NI,:)=0
  DO I=2,NI-1
  X0=R(I-1)
  X1=R(I  )
  X2=R(I+1)
  DDC(I,1) = 2/(X0-X1)/(X0-X2)
  DDC(I,2) = 2/(X1-X0)/(X1-X2)
  DDC(I,3) = 2/(X2-X0)/(X2-X1)
  ENDDO

  RETURN
  END FUNCTION DDC
! ======================================================================

END MODULE MOD_MARCH
