MODULE MOD_BOUSSINESQ ! LEVEL 4 MODULE
  USE omp_lib
  USE MPI
  USE MOD_MISC, ONLY : P4,P8,PI,IU,MCAT                              ! LEVEL 0
  USE MOD_EIG                                                        ! LEVEL 1
  USE MOD_SCALAR3                                                    ! LEVEL 2
  USE MOD_FFT                                                        ! LEVEL 2.5
  USE MOD_LEGOPS                                                     ! LEVEL 3
  IMPLICIT NONE
  PRIVATE
!=======================================================================
!============================ PARAMETERS ===============================
!=======================================================================
!1> BOUSSINESQ DATA
PUBLIC:: BOUSS_DATA
TYPE BOUSS_DATA
  ! ANGULAR VELOCITY OF THE ROTATING FRAME
  REAL(P8):: OMEGA
  ! UNPERTURBED BRUNT-VAISALA FREQUENCY (LINEAR STRATIFICATION)  
  REAL(P8):: BV0
  ! HYPERDIFFUSIVITY
  REAL(P8):: KAPPA, KAPPAP
  ! NUMERICAL METHOD FOR LINEAR TERMS
  LOGICAL :: ADAMS   ! = .TRUE.: USE ADAMS-BASHFORTH FOR THE LINEAR TERM
END TYPE
TYPE(BOUSS_DATA),PUBLIC:: BSNSQ   
!=======================================================================
!======================== PUBLIC DECLARATION ===========================
!=======================================================================
  ! TIME ADVANCEMENT SCHEMES RELATED
  PUBLIC:: BOUSSINESQ_FULL, BOUSSINESQ_NONLIN
  ! DIAGNOSTICS RELATED
  PUBLIC:: CALC_ENERGY
  ! LINEAR OPERATOR DIAGONALIZATION
  PUBLIC:: CALC_BOUSS_DIAG
! ======================================================================

CONTAINS
!=======================================================================
!============================ SUBROUTINES ==============================
!=======================================================================
SUBROUTINE CALC_BOUSS_DIAG(J,S,S_INV,ECHO)
!=======================================================================
! [USAGE]:
! CALCULATE THE DIAGONAL ELEMENTS OF THE BOUSSINESQ OPERATOR
! [PARAMETERS]:
! J >> EIGENVALUE OF THE LINEAR BOUSSINESQ OPERATOR
! S >> RIGHT EIGENMATRIX
! S_INV >> LEFT EIGENMATRIX
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8), DIMENSION(4,4), INTENT(INOUT):: J, S, S_INV
  REAL(P8) :: N_FREQ, OMEGA
  LOGICAL, OPTIONAL :: ECHO

  N_FREQ = BSNSQ%BV0
  OMEGA  = BSNSQ%OMEGA

  J = CMPLX(0.0D0, 0.0D0, P8)
  J(1,1) = -IU * N_FREQ
  J(2,2) =  IU * N_FREQ
  J(3,3) = -2.0D0 * IU * OMEGA
  J(4,4) =  2.0D0 * IU * OMEGA

  S = CMPLX(0.0D0, 0.0D0, P8)
  S(1,3) = IU
  S(1,4) = -IU
  S(2,3) = 1.0D0
  S(2,4) = 1.0D0
  S(3,1) = -IU / N_FREQ
  S(3,2) =  IU / N_FREQ
  S(4,1) = 1.0D0
  S(4,2) = 1.0D0

  S_INV = CMPLX(0.0D0, 0.0D0, P8)
  S_INV(1,3) =  IU * N_FREQ / 2.0D0
  S_INV(1,4) = 0.5D0
  S_INV(2,3) = -IU * N_FREQ / 2.0D0
  S_INV(2,4) = 0.5D0
  S_INV(3,1) = -IU / 2.0D0
  S_INV(3,2) = 0.5D0
  S_INV(4,1) =  IU / 2.0D0
  S_INV(4,2) = 0.5D0

  IF (PRESENT(ECHO)) THEN
    IF ((MPI_RANK.EQ.0).AND.(ECHO)) THEN
      WRITE(*,*) 'MOD_BOUSSINESQ: L = SJS^-1'
      WRITE(*,*) 'J:'
      CALL MCAT(J)
      WRITE(*,*) 'S:'
      CALL MCAT(S)
      WRITE(*,*) 'S^-1:'
      CALL MCAT(S_INV)
      WRITE(*,*) 'S*S^-1:'
      CALL MCAT(MATMUL(S, S_INV))
    ENDIF
  ENDIF

  RETURN
END SUBROUTINE CALC_BOUSS_DIAG
!=======================================================================

SUBROUTINE CALC_ENERGY(PSI,CHI,B,TIME,SAVEDIR)
!=======================================================================
! [USAGE]:
! CALCULATE KINETIC AND POTENTIAL ENERGY IN THE SYSTEM
! D(KE)/DT = DKE
! D(PE)/DT = -DKE
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE (FFF SPACE)
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE (FFF SPACE)
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE (FFF SPACE)
! TIME >> CURRENT TIME IN THE SIMULATION
! SAVEDIR >> DIRECTORY TO SAVE THE ENERGY DATA
! [DEPENDENCIES]:
! 1. DELSQH(~) @ MOD_LEGOPS <- REQUIRES CHOPSET
! 2. DEL2(~) @ MOD_LEGOPS
! 3. RTRAN(~) @ MOD_FFT
! 4. PRODCT_MK(~) @ MOD_SCALAR3
! 5. INTEG_MK(~) @ MOD_SCALAR3
!==========================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: PSI,CHI,B
TYPE(SCALAR):: W1,W2,W3
REAL(P8):: PE(NXCHOP),PE2(NXCHOP),KE(NTCHOP,NXCHOP),DKE(NTCHOP,NXCHOP),TIME
COMPLEX(P8):: PE_MK(NTCHOP,NXCHOPDIM), PE_K2(NXCHOPDIM)
INTEGER:: KK,KC,FILESTATUS
CHARACTER(LEN=72):: SAVEDIR

IF (B%LN .NE. 0.D0) THEN
! LN TERM IN B IS NOT PHYSICAL, AS B CAN'T BE IFINITE AT FAR FIELD
  CALL MPRINT('B has non-zero LN, this is not expected in Boussinesq')
  CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_LOGTERM, IERR)
ENDIF

CALL ALLOCATE(W1)
CALL ALLOCATE(W2)
CALL ALLOCATE(W3)
CALL CHOPSET(3)

! KINETIC ENERGY:
! ENERGY IN TOROIDAL COMPONENT
W1 = PSI
IF ((PSI%INX.EQ.0).AND.(PSI%INTH.EQ.0)) W1%LN = 2.0_P8*PSI%LN
CALL DELSQH(W1,W2)
W1%LN = 0.0_P8
W2%LN = 0.0_P8
CALL RTRAN(W1,1)
CALL RTRAN(W2,1)
KE = -PRODCT_MK_HALFK(W1,W2)

! ENERGY IN POLOIDAL COMPONENT
CALL DEL2(CHI,W1)
CALL DELSQH(CHI,W2)
W1%LN = 0.0_P8
W2%LN = 0.0_P8
CALL RTRAN(W1,1)
CALL RTRAN(W2,1)

! TOTAL KINETIC ENERGY
KE = KE + PRODCT_MK_HALFK(W1,W2)

! ENERGY EXCHANGE
W3 = B
W3%LN = 0.0_P8
CALL RTRAN(W3,1) ! Convert to PFF space
DKE = PRODCT_MK_HALFK(W3,W2)  ! W3 = B, W2 = (1-X)^-2*DEL^2_H(CHI) = -(1-X)^-2*UZ

CALL CHOPSET(-3)
CALL DEALLOCATE(W1)
CALL DEALLOCATE(W2)
CALL DEALLOCATE(W3)

! POTENTIAL ENERGY:
CALL ALLOCATE(W3)
CALL DIVXM2(B,W3) ! W3 = (1-X)^-2 * B
! PE_K2 = INTEG_K_FFF(W3)
PE_K2 = INTEG_K_PFF(B)

CALL RTRAN(W3,1) ! Convert to PFF space
PE_MK = INTEG_MK(W3)
CALL DEALLOCATE(W3)

! CHECK SYMMETRY FOR M = 0
DO KK = 1,NXCHOP
  IF (KK.EQ.1) THEN
    IF (ABS(AIMAG(PE_MK(1,1))) .GT. 1E-12) THEN
      CALL MPRINT('CALC_ENERGY: M = 0, K = 0 MODE OF INT[B] IS NOT REAL!')
      CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%CALCULATION, IERR)
    ENDIF
    CYCLE
  ENDIF
  KC = NXCHOPDIM+2-KK
  IF (ABS(PE_MK(1,KK)-CONJG(PE_MK(1,KC))) .GT. 1E-12) THEN
    CALL MPRINT('CALC_ENERGY: M = 0 MODES OF INT[B] DO NOT PRESERVE CONJUGATE SYMMETRY. INT[B] IS NOT REAL!')
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%CALCULATION, IERR)
  ENDIF
ENDDO
! CALCULATE INT[Z*B']
PE = 0.D0
PE(1) = REAL(PE_MK(1,1)) * ZLEN0**2 * PI
! PE_K(2:) = -(PE_MK(1,2:)/AK(1,2:)) * ZLEN0 * 2 * PI * IU
! PE_K(KK) = PE_K(KK) + PE_K(KC)
PE(2:NXCHOP) = AIMAG(PE_MK(1,2:NXCHOP)) / AK(1,2:NXCHOP) * ZLEN0 * 4.0_P8 * PI

! PE2
PE2 = 0.D0
PE2(1) = REAL(PE_K2(1)) * ZLEN0**2 * PI
PE2(2:NXCHOP) = AIMAG(PE_K2(2:NXCHOP)) / AK(1,2:NXCHOP) * ZLEN0 * 4.0_P8 * PI
! DO KK = 2,NXCHOP
!   PE2(KK) = AIMAG(PE_K2(1,KK)) / AK(1,KK) * ZLEN0 *4 *PI
! ENDDO

! Combined PRINTOUT
IF (MPI_RANK.EQ.0) THEN
  OPEN(UNIT=667,FILE=TRIM(ADJUSTL(SAVEDIR))//'especData.dat',STATUS='UNKNOWN',&
    & IOSTAT=FILESTATUS, POSITION='APPEND')
  WRITE(667, '(" KE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(KE(:,KK)),KK=1,NXCHOP)
  WRITE(667, '(" PE:",F24.16,1X,*(E24.16,1X))') TIME, (PE(KK), KK=1,NXCHOP)
  WRITE(667, '("PE2:",F24.16,1X,*(E24.16,1X))') TIME, (PE2(KK), KK=1,NXCHOP)
  WRITE(667, '("DKE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(DKE(:,KK)),KK=1,NXCHOP)
  CLOSE(667)
ENDIF

END SUBROUTINE CALC_ENERGY
!=======================================================================

FUNCTION INTEG_K_FFF(F)
!=======================================================================
! [USAGE]:
! INTEGRATION OF A FUNCTION OVER R FOR EACH K
! CALL IN FFF_SPACE
! INTEGRATED FUNCTION G IS IN THE FORM G = F*(1-MU)^2
! [INPUTS]:
! F >> A FUNTION INPUT FOR INTEGRATION (ACTUAL INTEGRATION IS DONE ON G)
! [OUTPUTS]:
! INTEG_K_FFF >> INTEGRATION EQUAL TO INT(G(R,PHI,Z) RDR)
!========================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: F
COMPLEX(P8),DIMENSION(NXCHOPDIM):: INTEG_K_FFF
INTEGER:: KK,COUNT

IF(F%SPACE.NE.FFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
    WRITE(*,*) 'INTEG_K_FFF: NOT IN FFF_SPACE'
  ENDIF
  STOP
ENDIF

INTEG_K_FFF = CMPLX(0.D0,0.D0)
IF (F%INTH .EQ. 0) THEN
  DO KK = 1,SIZE(F%E,3) !NXCHOP
    INTEG_K_FFF(KK+F%INX) = &
      2.0_P8 * ELL2 * F%E(1,1,KK) * TFM%NORM(1,1)
  ENDDO
ENDIF

COUNT = NXCHOPDIM
CALL MPI_ALLREDUCE(MPI_IN_PLACE, INTEG_K_FFF, COUNT, &
                  MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_IVP, IERR)

RETURN
END FUNCTION INTEG_K_FFF
!=======================================================================

FUNCTION INTEG_K_PFF(F)
!=======================================================================
! [USAGE]:
! INTEGRATION OF A FUNCTION OVER R FOR EACH K
!========================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: F
TYPE(SCALAR):: F_COPY
COMPLEX(P8),DIMENSION(NXCHOPDIM):: INTEG_K_PFF
INTEGER:: KK,COUNT
REAL(P8):: DOT_REAL, DOT_IMAG

IF(F%SPACE.NE.FFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
    WRITE(*,*) 'INTEG_K_PFF: NOT IN FFF_SPACE'
  ENDIF
  STOP
ENDIF

CALL ALLOCATE(F_COPY)
F_COPY = F
CALL RTRAN(F_COPY,1) ! Convert to PFF space

INTEG_K_PFF = CMPLX(0.D0,0.D0)
IF (F_COPY%INTH .EQ. 0) THEN
  DO KK = 1,SIZE(F_COPY%E,3) !NXCHOP
    DOT_REAL = DOT_PRODUCT(REAL(F_COPY%E(:NR,1,KK))/(1.D0-TFM%X)**2,TFM%W)
    DOT_IMAG = DOT_PRODUCT(AIMAG(F_COPY%E(:NR,1,KK))/(1.D0-TFM%X)**2,TFM%W)
    INTEG_K_PFF(KK+F_COPY%INX) = ELL2 * (DOT_REAL + IU * DOT_IMAG)
  ENDDO
ENDIF

CALL DEALLOCATE(F_COPY)
COUNT = NXCHOPDIM
CALL MPI_ALLREDUCE(MPI_IN_PLACE, INTEG_K_PFF, COUNT, &
                  MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_IVP, IERR)

RETURN
END FUNCTION INTEG_K_PFF
!=======================================================================

SUBROUTINE BOUSSINESQ_NONLIN(B, RUR, RUP, UZ, BN, ROR, ROP, OZ)
!=======================================================================
! [USAGE]:
! CALCULATE THE NONLINEAR TERMS IN BOUSSINESQ APPROXIMATION:
! THE ADVECTION TERM (U X OMEGA) AND THE BUOYANCY FORCING -(U.GRAD)B.
!
! [PARAMETERS]:
! B  >> (IN) Density perturbation, must be in FFF space.
! BN >> (OUT) The nonlinear buoyancy tendency -(U.GRAD)B.
! RUR,RUP,UZ >> (INOUT) Velocity components. Updated with freestream.
! ROR,ROP,OZ >> (IN) Vorticity components from PC2VOR.
!            >> (OUT) Overwritten with U x OMEGA
! [NOTES]:
! B REMAINS IN FFF SPACE
! ALL OTHER VARIABLES REMAPPED TO PPP SPACE
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: B
TYPE(SCALAR),INTENT(INOUT):: RUR,RUP,UZ
TYPE(SCALAR),INTENT(INOUT):: ROR,ROP,OZ,BN

TYPE(SCALAR):: RBR,RBP,BZ
INTEGER:: NI,NJ,NK

IF (B%SPACE .NE. FFF_SPACE) THEN
  CALL MPRINT('BOUSSINESQ_NONLIN: B SHOULD BE IN FFF SPACE!')
  CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%LEGOPERATOR, IERR)
ENDIF

CALL ALLOCATE(RBR)
CALL ALLOCATE(RBP)
CALL ALLOCATE(BZ)

CALL CHOPSET(1)
CALL GRAD(B,RBR,RBP,BZ)
CALL CHOPSET(-1)

CALL TOFP(RUR); CALL TOFP(RUP); CALL TOFP(UZ)
CALL TOFP(ROR); CALL TOFP(ROP); CALL TOFP(OZ)
CALL TOFP(RBR); CALL TOFP(RBP); CALL TOFP(BZ)

NI=SIZE(RUR%E,1); NJ=SIZE(RUR%E,2); NK=SIZE(RUR%E,3)

! CALCULATING U X OMEGA
! NOTE: RUR, RUP, UZ UPDATED WITH FREESTREAM VELOCITY IN PPP SPACE
!       ROR, ROP, OZ BECAME U X OMEGA IN PPP SPACE
CALL VPRODSUB(RUR%E,RUP%E,UZ%E,ROR%E,ROP%E,OZ%E,NI,NJ,NK,RUR%INR)

! CALCULATING -(U.GRAD)B
! NOTE: RUR, RUP, UZ ALREADY CONTAINS FREESTREAM DUE TO VPRODSUB
IF (ASSOCIATED(BN%E)) CALL DEALLOCATE(BN)
CALL ALLOCATE(BN,PPP_SPACE); BN%LN=0.d0
BN%E = -VDOTPSUB(RUR%E,RUP%E,UZ%E,RBR%E,RBP%E,BZ%E,NI,NJ,NK,RUR%INR,.FALSE.)

CALL DEALLOCATE(RBR)
CALL DEALLOCATE(RBP)
CALL DEALLOCATE(BZ)

RETURN
END SUBROUTINE BOUSSINESQ_NONLIN
! ======================================================================

SUBROUTINE BOUSSINESQ_FULL(PSI,CHI,B,PSIN,CHIN,BN)
!=======================================================================
! [USAGE]: 
! CALCULATE THE NONLINEAR AND LINEAR TERMS
! INCLUDING ROTATION, STRATIFICATION, AND NONLINEAR ADVECTION
! [PARAMETERS]:
! PSI  >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI  >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B    >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSIN >> ON EXIT, TOROIDAL TERM FOR TIME ADVANCEMENT
! CHIN >> ON EXIT, POLOIDAL TERM FOR TIME ADVANCEMENT
! BN   >> ON EXIT, DENSITY TERM FOR TIME ADVANCEMENT
! [DEPENDENCIES]:
! 1. GRAD(~), PC2VEL(~), PC2VOR(~) @ MOD_LEGOPS
! 2. VPRODSUB(~), VDOTPSUB(~) @ MOD_LEGOPS
! 3. PROJECT(~), IDEL2(~) @ MOD_LEGOPS
! 4. TOFP(~), TOFF(~) @ MOD_FFT
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: PSI,CHI,B
TYPE(SCALAR),INTENT(INOUT):: PSIN,CHIN,BN

TYPE(SCALAR):: RUR,RUP,UZ
TYPE(SCALAR):: ROR,ROP,OZ
TYPE(SCALAR):: RBR,RBP,BZ
TYPE(SCALAR):: W
INTEGER:: NI,NJ,NK

CALL ALLOCATE( RUR ); CALL ALLOCATE( RUP ); CALL ALLOCATE(  UZ )
CALL ALLOCATE( ROR ); CALL ALLOCATE( ROP ); CALL ALLOCATE(  OZ )
CALL ALLOCATE( RBR ); CALL ALLOCATE( RBP ); CALL ALLOCATE(  BZ )

! DEALIASING
CALL CHOPSET(3)

! OBTAINING GRAD(B)
CALL GRAD(B,RBR,RBP,BZ)                                            ! NOTE: INPUT AND OUTPUTS ARE STILL IN FFF SPACE

! OBTAINING VELOCITY AND VORTICITY
CALL PC2VEL(PSI,CHI,RUR,RUP,UZ)                                    ! NOTE: INPUT AND OUTPUTS ARE STILL IN FFF SPACE
CALL PC2VOR(PSI,CHI,ROR,ROP,OZ)                                    ! NOTE: INPUT AND OUTPUTS ARE STILL IN FFF SPACE

! FFF -> PPP SPACE
CALL TOFP(RUR); CALL TOFP(RUP); CALL TOFP(UZ)
CALL TOFP(ROR); CALL TOFP(ROP); CALL TOFP(OZ)
CALL TOFP(RBR); CALL TOFP(RBP); CALL TOFP(BZ)

! CALCULATE NONLINEAR TERMS
NI=SIZE(RUR%E,1); NJ=SIZE(RUR%E,2); NK=SIZE(RUR%E,3)
!> CALCULATING U X OMEGA
!> NOTE: RUR, RUP, UZ UPDATED WITH FREESTREAM VELOCITY IN PPP SPACE
!>       ROR, ROP, OZ BECAME U X OMEGA IN PPP SPACE
CALL VPRODSUB(RUR%E,RUP%E,UZ%E,ROR%E,ROP%E,OZ%E,NI,NJ,NK,RUR%INR)
!> CALCULATING -(U.GRAD)B
!> NOTE: RUR, RUP, UZ ALREADY CONTAINS FREESTREAM DUE TO VPRODSUB
IF (ASSOCIATED(BN%E)) CALL DEALLOCATE(BN)
CALL ALLOCATE(BN,PPP_SPACE); BN%LN=0
BN%E = -VDOTPSUB(RUR%E,RUP%E,UZ%E,RBR%E,RBP%E,BZ%E,NI,NJ,NK,RUR%INR,.FALSE.)

! END DEALIASING
CALL CHOPSET(-3)

! ADD LINEAR TERMS TO NONLINEAR TERMS
CALL ALLOCATE(W); W = B
CALL TOFP(W)
!> 2OMEGA Z_HAT X U - B Z_HAT
ROR%E = ROR%E + 2*BSNSQ%OMEGA*RUP%E
ROP%E = ROP%E - 2*BSNSQ%OMEGA*RUR%E

OZ%E  = OZ%E - W%E
CALL DEALLOCATE(W)
!> N_BAR^2 * UZ
BN%E = BN%E + BSNSQ%BV0**2*UZ%E

CALL DEALLOCATE( RUR ); CALL DEALLOCATE( RUP ); CALL DEALLOCATE( UZ  )
CALL DEALLOCATE( RBR ); CALL DEALLOCATE( RBP ); CALL DEALLOCATE( BZ  )

!> CALCULATING FINAL TERMS PSIN, CHIN, BN IN FFF SPACE
CALL ALLOCATE(W)
CALL PROJECT(ROR,ROP,OZ,PSIN,W)                                    ! NOW PSIN = PSI_NONLINEAR AND W = DELSQ(CHI_NONLINEAR)
CALL IDEL2(W,CHIN)                                                 ! NOW CHIN = CHI_NONLINEAR
CALL CHOPSET(-1)
CALL TOFF(BN)
CALL CHOPSET(1)

CALL DEALLOCATE( ROR )
CALL DEALLOCATE( ROP )
CALL DEALLOCATE( OZ  )
CALL DEALLOCATE( W   )

CALL MPI_BARRIER(MPI_COMM_IVP,IERR)
RETURN
END SUBROUTINE BOUSSINESQ_FULL
! ======================================================================

END MODULE