MODULE MOD_MARCH ! LEVEL 4 MODULE
  USE omp_lib
  USE MPI
  USE MOD_MISC, ONLY : P4,P8,PI,IU,SPY,MSAVE,MLOAD,CFL               ! LEVEL 0
  USE MOD_EIG                                                        ! LEVEL 1
  USE MOD_SCALAR3                                                    ! LEVEL 2
  USE MOD_FFT                                                        ! LEVEL 2.5
  USE MOD_LEGOPS                                                     ! LEVEL 3
  USE MOD_BOUSSINESQ
  IMPLICIT NONE
  PRIVATE
!=======================================================================
!============================ PARAMETERS ===============================
!=======================================================================
  !1> TIME ADVANCEMENT INFORMATION
  PUBLIC:: TIMEDATA
  TYPE TIMEDATA
    REAL(P8):: DT,T,LIMIT
    INTEGER:: N
    INTEGER:: SCHEME
  ENDTYPE TIMEDATA
  TYPE(TIMEDATA),PUBLIC:: TIM

  !2> FREESTREAM VELOCITY FIELD INFORMATION
  PUBLIC:: IMPOSED_FIELD
  TYPE IMPOSED_FIELD
    INTEGER:: SW, INT  
    REAL(P8):: UX,UY,UZ
    REAL(P8):: X,Y
    REAL(P8):: T0,X0,Y0,T1,X1,Y1
  ENDTYPE IMPOSED_FIELD
  TYPE(IMPOSED_FIELD),PUBLIC:: ADV

  !3> VORTEX REMOVAL
  PUBLIC:: REMOVAL
  TYPE REMOVAL
    INTEGER:: SW,INT
  ENDTYPE REMOVAL
  TYPE(REMOVAL),PUBLIC:: RMV

  !4> VISCOSITY ADJUSTMENT
  PUBLIC:: VISCOSITY
  TYPE VISCOSITY
    INTEGER:: SW,P,ADJSW,ADJINT
    REAL(P8):: NU,NUP
  ENDTYPE VISCOSITY
  TYPE(VISCOSITY),PUBLIC:: VISC

  !5> FILE INOUT
  PUBLIC:: IOFILES
  TYPE IOFILES
    CHARACTER(LEN=72):: SAVEDIR 
    CHARACTER(LEN=72):: PSI0,CHI0,B0
    CHARACTER(LEN=72):: PSII,CHII,BI
    REAL(P8),DIMENSION(:),POINTER:: T
    CHARACTER(LEN=72),DIMENSION(:),POINTER:: PSI,CHI,B
    INTEGER:: N,NE
  ENDTYPE IOFILES
  TYPE(IOFILES),PUBLIC:: FILES

  !6> DIAGNOSTIC INFOMRATION STORAGE
  PUBLIC:: DIAGDATA
  TYPE DIAGDATA
    LOGICAL:: IS_INITIALIZED=.FALSE.
    INTEGER:: IT1,IT2
    REAL(P8):: VORI,ZMOMI,ENEI,ANGI,HELI,XCEN,YCEN
  ENDTYPE DIAGDATA
  TYPE(DIAGDATA),PUBLIC:: DIAGV

  !7> LINEAR DATA INFORMATION STORAGE
  PUBLIC:: LINEARDATA
  TYPE LINEARDATA
    INTEGER:: MM,KK
  ENDTYPE LINEARDATA
  TYPE(LINEARDATA),PUBLIC:: LIN

  !8> POSTPROCESS KIT
  PUBLIC:: POSTPROCESSKIT
  TYPE POSTPROCESSKIT
    INTEGER :: START, FINISH, JOB, SLICEINT
  ENDTYPE POSTPROCESSKIT
  TYPE(POSTPROCESSKIT),PUBLIC:: POSTPROCESS

  !9> EIGENVALUE MONITOR KIT
  PUBLIC:: MONITOREIGENVALUESKIT
  TYPE MONITOREIGENVALUESKIT
    INTEGER :: START, INTERVAL
  ENDTYPE MONITOREIGENVALUESKIT
  TYPE(MONITOREIGENVALUESKIT),PUBLIC:: MONITORDATA

  REAL(P8):: SUMMO,SUMKO,NUPB                                        ! USED IN THE HYPADJ SUBROUTINE
  INTEGER:: FIRST=0                                                  ! USED IN THE HYPADJ SUBROUTINE
!=======================================================================
!======================== PUBLIC DECLARATION ===========================
!=======================================================================
  ! TIME ADVANCEMENT SCHEMES (ADAMS-BASHFORTH, RICHARDSON, EULER)
  PUBLIC:: ADAMSB, RICH, EULER, KRYLOV2, KRYLOV_INIT
  ! VISCOSITY & HYPERVISCOSITY IMPOSITION
  PUBLIC:: VISC1,VISC2,HYPERV
  ! DIAGNOSIS OF FIELD
  PUBLIC:: DIAGNOST
  ! ADJUST FREESTREAM VELOCITY
  PUBLIC:: FREEADJ
  ! KILL VORTEX AWAY FROM THE COMPUTATIONAL DOMAIN
  PUBLIC:: REMOVE
  ! COMPUTE INTEGRATION OF TWO FUNCTION FOR EACH AZIMUTHAL/AXIAL WVN
  PUBLIC:: PRODCTM, PRODCTK
  ! COMPUTE ENERGY FOR EACH AZIMUTHAL/AXIAL WAVENUMBER
  PUBLIC:: ENEMON
  ! HYPERVISCOSITY ADJUSTMENT
  PUBLIC:: HYPADJ
  
CONTAINS
!=======================================================================
!============================ SUBROUTINES ==============================
!=======================================================================
  SUBROUTINE ADAMSB(PSI,CHI,B,PSINO,CHINO,BNO)
!=======================================================================
! [USAGE]: 
! UPDATE POLOIDAL-TOROIDAL TERMS OF THE VELOCITY FIELD BY 1 TIME STEP
! USING ADAMS-BASHFORTH METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSINO >> NONLINEAR COMPONENT OF THE TOROIDAL TERM IN THE PREVIOUS STEP
! CHINO >> NONLINEAR COMPONENT OF THE POLOIDAL TERM IN THE PREVIOUS STEP
! BNO   >> NONLINEAR COMPONENT OF THE DENSITY  TERM IN THE PREVIOUS STEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. NONLIN(~) @ MOD_LEGOPS
! 3. VISC2(~) @ MOD_MARCH
! 4. HYPERV(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSINO,CHINO,BNO
  TYPE(SCALAR):: PSIN,CHIN,BN

  TYPE(SCALAR):: PSI0,CHI0,B0
  REAL(P8):: DT

  DT = TIM%DT
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE( PSIN )
  CALL ALLOCATE( CHIN )
  CALL ALLOCATE(   BN )

  ! CALL NONLIN(PSI,CHI,PSIN,CHIN)
  CALL BOUSSINESQ_AB(PSI,CHI,B,PSIN,CHIN,BN)

  CALL ALLOCATE( PSI0 )
  CALL ALLOCATE( CHI0 )
  CALL ALLOCATE(   B0 )

  PSI0 = PSI
  CHI0 = CHI
  B0 = B

  PSI%E = PSI%E +DT*(1.5D0*PSIN%E -0.5D0*PSINO%E)
  CHI%E = CHI%E +DT*(1.5D0*CHIN%E -0.5D0*CHINO%E)
    B%E =   B%E +DT*(1.5D0*  BN%E -0.5D0*  BNO%E)

  PSINO=PSIN
  CHINO=CHIN
    BNO=BN

  CALL DEALLOCATE( PSIN )
  CALL DEALLOCATE( CHIN )
  CALL DEALLOCATE(   BN )

  CALL VISC2(PSI,CHI,B,PSI0,CHI0,B0)
  CALL HYPERV(PSI,CHI,B,DT)

  CALL DEALLOCATE( PSI0 )
  CALL DEALLOCATE( CHI0 )
  CALL DEALLOCATE(   B0 )

  RETURN
  END SUBROUTINE ADAMSB
!=======================================================================

  SUBROUTINE RICH(PSI,CHI,B,PSIN,CHIN,BN)
!=======================================================================
! [USAGE]: 
! UPDATE POLOIDAL-TOROIDAL TERMS OF THE VELOCITY FIELD BY 1 TIME STEP
! USING RICHARDSON EXTRAPOLATION
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSIN >> NONLINEAR COMPONENT OF THE TOROIDAL TERM
! CHIN >> NONLINEAR COMPONENT OF THE POLOIDAL TERM
! BN   >> NONLINEAR COMPONENT OF THE DENSITY TERM
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. NONLIN(~) @ MOD_LEGOPS
! 3. VISC1(~) @ MOD_MARCH
! 4. HYPERV(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSIN,CHIN,BN

  TYPE(SCALAR):: PSI2,CHI2,B2
  TYPE(SCALAR):: P_N,C_N,B_N
  REAL(P8):: DT, HDT

  CALL KRYLOV_INIT()

  DT = TIM%DT
  HDT = DT*0.5D0
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE(PSI2)
  CALL ALLOCATE(CHI2)
  CALL ALLOCATE(  B2)

  ! FIRST HALF-STEP
  ! CALL NONLIN(PSI,CHI,PSIN,CHIN)
  ! CALL BOUSSINESQ(PSI,CHI,B,PSIN,CHIN,BN)
  call BOUSSINESQ_AB(PSI,CHI,B,PSIN,CHIN,BN)

  PSI2%E =PSI%E + (HDT*PSIN%E)
  CHI2%E =CHI%E + (HDT*CHIN%E)
    B2%E =  B%E + (HDT*  BN%E)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  CALL ALLOCATE( P_N )
  CALL ALLOCATE( C_N )
  CALL ALLOCATE( B_N )

  ! SECOND HALF-STEP
  ! CALL NONLIN(PSI2,CHI2,P_N,C_N)
  ! CALL BOUSSINESQ(PSI2,CHI2,B2,P_N,C_N,B_N)
  CALL BOUSSINESQ_AB(PSI2,CHI2,B2,P_N,C_N,B_N)

  PSI2%E =PSI2%E + (HDT*P_N%E)
  CHI2%E =CHI2%E + (HDT*C_N%E)
    B2%E =  B2%E + (HDT*B_N%E)
  CALL VISC1(PSI2,CHI2,B2,HDT)
  CALL HYPERV(PSI2,CHI2,B2,HDT)

  ! FULL STEP
  PSI%E =PSI%E +(DT)*PSIN%E
  CHI%E =CHI%E +(DT)*CHIN%E
    B%E =  B%E +(DT)*  BN%E

  CALL VISC1(PSI,CHI,B,DT)
  CALL HYPERV(PSI,CHI,B,DT)

  PSI%E =(2.0D0*PSI2%E)-PSI%E
  CHI%E =(2.0D0*CHI2%E)-CHI%E
    B%E =(2.0D0*  B2%E)-  B%E

  CALL DEALLOCATE( PSI2 )
  CALL DEALLOCATE( CHI2 )
  CALL DEALLOCATE(   B2 )
  CALL DEALLOCATE( P_N )
  CALL DEALLOCATE( C_N )
  CALL DEALLOCATE( B_N )

  RETURN
  END SUBROUTINE RICH
!=======================================================================

  SUBROUTINE KRYLOV_INIT()
!=======================================================================
! [USAGE]: 
! INITIALIZE KRYLOV SUBSPACE FOR NONLINEAR SOLVER
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8),DIMENSION(4,4):: S_L, J, S_R, J_EXP, J_INV, IDEN
  INTEGER:: I
  REAL(P8):: N, OMEGA, DT

  ! Check if Adams-Bashforth method is used for linear terms
  IF (BSNSQ%ADAMS) RETURN
  
  ! Get parameters from BSNSQ
  N = BSNSQ%BV0
  OMEGA = BSNSQ%OMEGA
  DT = TIM%DT
  
  ! Initialize matrices to zero
  J = CMPLX(0.0D0, 0.0D0, P8)
  S_L = CMPLX(0.0D0, 0.0D0, P8)
  S_R = CMPLX(0.0D0, 0.0D0, P8)
  IDEN = CMPLX(0.0D0, 0.0D0, P8)
  
  ! Identity matrix
  DO I = 1, 4
    IDEN(I,I) = CMPLX(1.0D0, 0.0D0, P8)
  ENDDO
  
  ! Initialize the J diagonal matrix
  J(1,1) = -IU * N
  J(2,2) = IU * N
  J(3,3) = -2.0D0 * IU * OMEGA
  J(4,4) = 2.0D0 * IU * OMEGA
  
  ! Initialize the S_L matrix
  S_L(1,3) = IU
  S_L(1,4) = -IU
  S_L(2,3) = 1.0D0
  S_L(2,4) = 1.0D0
  S_L(3,1) = -IU / N
  S_L(3,2) = IU / N
  S_L(4,1) = 1.0D0
  S_L(4,2) = 1.0D0
  
  ! Initialize the S_R matrix
  S_R(1,3) = IU * N / 2.0D0
  S_R(1,4) = 0.5D0
  S_R(2,3) = -IU * N / 2.0D0
  S_R(2,4) = 0.5D0
  S_R(3,1) = -IU / 2.0D0
  S_R(3,2) = 0.5D0
  S_R(4,1) = IU / 2.0D0
  S_R(4,2) = 0.5D0
  
  ! Compute matrix exponential for diagonal J
  J_EXP = IDEN
  DO I = 1, 4
    J_EXP(I,I) = EXP(J(I,I) * DT)
  ENDDO
  
  ! Compute J inverse
  J_INV = IDEN
  DO I = 1, 4
    IF (ABS(J(I,I)) > 1.0D-14) THEN
      J_INV(I,I) = 1.0D0 / J(I,I)
    ELSE
      J_INV(I,I) = CMPLX(0.0D0, 0.0D0, P8)
    ENDIF
  ENDDO
  
  ! Calculate S_0 = S_R * e^{J*DT} * S_L
  BSNSQ%S_0 = MATMUL(S_R, MATMUL(J_EXP, S_L))
  
  ! Calculate S_N = S_R * J^-1 * (e^{J*DT} - I) * S_L
  BSNSQ%S_N = MATMUL(S_R, MATMUL(J_INV, MATMUL(J_EXP - IDEN, S_L)))
  
  IF (MPI_RANK.EQ.0) THEN
    WRITE(*,*) 'Krylov subspace initialized for linear part'
  ENDIF

  RETURN
  END SUBROUTINE KRYLOV_INIT
!=======================================================================

  SUBROUTINE KRYLOV2(PSI,CHI,B,PSINO,CHINO,BNO)
!=======================================================================
! [USAGE]: 
! UPDATE POLOIDAL-TOROIDAL TERMS OF THE VELOCITY FIELD BY 1 TIME STEP
! USING ADAMS-BASHFORTH METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSINO >> NONLINEAR COMPONENT OF THE TOROIDAL TERM IN THE PREVIOUS STEP
! CHINO >> NONLINEAR COMPONENT OF THE POLOIDAL TERM IN THE PREVIOUS STEP
! BNO   >> NONLINEAR COMPONENT OF THE DENSITY  TERM IN THE PREVIOUS STEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. NONLIN(~) @ MOD_LEGOPS
! 3. VISC2(~) @ MOD_MARCH
! 4. HYPERV(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSINO,CHINO,BNO
  TYPE(SCALAR):: PSIN,CHIN,BN

  TYPE(SCALAR):: PSI0,CHI0,B0
  REAL(P8):: DT

  DT = TIM%DT
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  CALL ALLOCATE( PSIN )
  CALL ALLOCATE( CHIN )
  CALL ALLOCATE(   BN )

  ! NONLINEAR TERMS FOR CURRENT TIME STEP
  CALL BOUSSINESQ_NONLIN(PSI,CHI,B,PSIN,CHIN,BN)

  CALL ALLOCATE( PSI0 )
  CALL ALLOCATE( CHI0 )
  CALL ALLOCATE(   B0 )

  PSI0 = PSI
  CHI0 = CHI
  B0 = B

  PSI%E = PSI%E +DT*(1.5D0*PSIN%E -0.5D0*PSINO%E)
  CHI%E = CHI%E +DT*(1.5D0*CHIN%E -0.5D0*CHINO%E)
    B%E =   B%E +DT*(1.5D0*  BN%E -0.5D0*  BNO%E)

  PSINO=PSIN
  CHINO=CHIN
    BNO=  BN

  CALL DEALLOCATE( PSIN )
  CALL DEALLOCATE( CHIN )
  CALL DEALLOCATE(   BN )

  CALL VISC2(PSI,CHI,B,PSI0,CHI0,B0)
  CALL HYPERV(PSI,CHI,B,DT)

  CALL DEALLOCATE( PSI0 )
  CALL DEALLOCATE( CHI0 )
  CALL DEALLOCATE(   B0 )

  RETURN
  END SUBROUTINE KRYLOV2
!=======================================================================

  SUBROUTINE EULER(PSI,CHI,B,PSIN,CHIN,BN)
!=======================================================================
! [USAGE]: 
! UPDATE POLOIDAL-TOROIDAL TERMS OF THE VELOCITY FIELD BY 1 TIME STEP
! USING FORWARD EULER METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSIN >> NONLINEAR COMPONENT OF THE TOROIDAL TERM
! CHIN >> NONLINEAR COMPONENT OF THE POLOIDAL TERM
! BN   >> NONLINEAR COMPONENT OF THE DENSITY TERM
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. NONLIN(~) @ MOD_LEGOPS
! 3. VISC1(~) @ MOD_MARCH
! 4. HYPERV(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSIN,CHIN,BN

  REAL(P8):: DT

  DT = TIM%DT
  TIM%T = TIM%T + DT
  TIM%N = TIM%N + 1
  ADV%X = ADV%X + ADV%UX*DT
  ADV%Y = ADV%Y + ADV%UY*DT

  ! CALL NONLIN(PSI,CHI,PSIN,CHIN)
  ! CALL BOUSSINESQ(PSI,CHI,B,PSIN,CHIN,BN)
  CALL BOUSSINESQ_AB(PSI,CHI,B,PSIN,CHIN,BN)

  PSI%E =PSI%E + (DT*PSIN%E)
  CHI%E =CHI%E + (DT*CHIN%E)
    B%E =  B%E + (DT*  BN%E)

  CALL VISC1(PSI,CHI,B,DT)
  CALL HYPERV(PSI,CHI,B,DT)

  RETURN
  END SUBROUTINE EULER
!=======================================================================

  SUBROUTINE VISC1(PSI,CHI,B,DT)
!=======================================================================
! [USAGE]: 
! UPDATE TOROIDAL TERMS OF THE VELOCITY FIELD WITH REGARD TO VISCOSITY
! USING BACKWARD (IMPLICIT) EULER METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! DT >> TIMESTEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. IHELM(~) @ MOD_LEGOPS
! [NOTES]:
! THE FOLLOWING FORMULA IS UTILIZED TO UPDATE PSI.
!     PSI(1)-PSI(0)
!     ------------- = VISCNU(DEL2)(PSI(1))
!           DT
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B
  REAL(P8):: DT

  TYPE(SCALAR):: WK1
  REAL(P8):: ALP

  IF(VISC%SW.NE.1) RETURN

  IF(VISC%NU.EQ.0.0) THEN
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'VISC: VISC%NU CAN''T BE ZERO'
    STOP
  ENDIF

  CALL ALLOCATE( WK1,FFF_SPACE )
  ALP=1/(VISC%NU*DT)

  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) WK1%LN=-ALP*PSI%LN
  WK1%E =-ALP*PSI%E
  CALL IHELM(WK1,PSI,ALP)

  IF ((CHI%INTH.EQ.0).AND.(CHI%INX.EQ.0)) WK1%LN=-ALP*CHI%LN
  WK1%E =-ALP*CHI%E
  CALL IHELM(WK1,CHI,ALP)

  IF(BSNSQ%KAPPA .NE. 0.D0) THEN
    
    ALP=1/(BSNSQ%KAPPA)

    IF ((B%INTH.EQ.0).AND.(B%INX.EQ.0)) WK1%LN=-ALP*B%LN
    WK1%E =-ALP*B%E
    CALL IHELM(WK1,B,ALP)

  ENDIF

  CALL DEALLOCATE( WK1 )

  RETURN
  END SUBROUTINE VISC1
!=======================================================================

  SUBROUTINE VISC2(PSI,CHI,B,PSIO,CHIO,BO)
!=======================================================================
! [USAGE]: 
! UPDATE TOROIDAL TERMS OF THE VELOCITY FIELD WITH REGARD TO VISCOSITY
! USING CRANK-NICHOLSON (IMPLICIT) METHOD
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! PSIO >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A PREVIOUS STEP
! CHIO >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A PREVIOUS STEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. CHOPSET(~) @ MOD_SCALAR3
! 3. CHOPDO(~) @ MOD_SCALAR3
! 4. DEL2(~) @ MOD_LEGOPS
! 5. IHELM(~) @ MOD_LEGOPS
! [NOTES]:
! THE FOLLOWING FORMULA IS UTILIZED TO UPDATE PSI.
!    PSI(1)-PSI(1/2)               PSI(1)+PSI(0)
!    ------------- = VISCNU(DEL2)(--------------)
!          DT                            2
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B,PSIO,CHIO,BO

  TYPE(SCALAR):: WK1
  REAL(P8):: ALP

  IF(VISC%SW.NE.1) RETURN

  IF(VISC%NU .EQ. 0.D0) THEN
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'VISC: VISC%NU CANNOT BE ZERO'
    STOP
  ENDIF

  CALL ALLOCATE( WK1 )

  ALP=2/VISC%NU/TIM%DT

  CALL CHOPSET(2)
  CALL DEL2(PSIO,WK1)
  CALL CHOPSET(-2)
  CALL CHOPDO(WK1)

  WK1%E = -WK1%E-ALP*PSI%E
  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) WK1%LN= -ALP*PSI%LN
  CALL IHELM(WK1,PSI,ALP)

  CALL CHOPSET(2)
  CALL DEL2(CHIO,WK1)
  CALL CHOPSET(-2)
  CALL CHOPDO(WK1)

  WK1%E = -WK1%E-ALP*CHI%E
  IF ((CHI%INTH.EQ.0).AND.(CHI%INX.EQ.0)) WK1%LN= -ALP*CHI%LN
  CALL IHELM(WK1,CHI,ALP)

  IF (BSNSQ%KAPPA .NE. 0.D0) THEN

    ALP=2/BSNSQ%KAPPA/TIM%DT

    CALL CHOPSET(2)
    CALL DEL2(BO,WK1)
    CALL CHOPSET(-2)
    CALL CHOPDO(WK1)

    WK1%E = -WK1%E-ALP*B%E
    IF ((B%INTH.EQ.0).AND.(B%INX.EQ.0)) WK1%LN= -ALP*B%LN
    CALL IHELM(WK1,B,ALP)

  ENDIF

  CALL DEALLOCATE( WK1 )

  RETURN
  END SUBROUTINE VISC2
!=======================================================================
  SUBROUTINE HYPERV(PSI,CHI,B,DT)
!=======================================================================
! [USAGE]: 
! DUMP HYPERVISCOSITY TO THE HIGHER ORDER COEFFICIENTS
! OPERATES ONLY WHEN VISC%SW = 2
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! DT >> TIMESTEP
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. IHELMP(~) @ MOD_LEGOPS
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI,B
  REAL(P8):: DT
  
  TYPE(SCALAR):: W
  REAL(P8):: ALP,BET
  INTEGER:: PH

  IF(VISC%SW.EQ.0) THEN
    IF ((MPI_RANK.EQ.0).AND.(MOD(tim%n,diagv%it1).eq.0)) WRITE(6,*) 'HYPERV: WARNING: NO DISSIPATION AT ALL.'
  ELSEIF(VISC%SW.EQ.2) THEN
    CALL ALLOCATE( W )
    PH = VISC%P/2
    ALP = 1/DT/VISC%NUP *(-1)**PH
    BET = -(-1)**PH*VISC%NU/VISC%NUP

    W%E = ALP*PSI%E
    IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) W%LN = ALP*PSI%LN
    CALL IHELMP(VISC%P,W,PSI,-ALP,BET)
    
    W%E = ALP*CHI%E
    IF ((CHI%INTH.EQ.0).AND.(CHI%INX.EQ.0)) W%LN = ALP*CHI%LN
    CALL IHELMP(VISC%P,W,CHI,-ALP,BET)

    ! DENSITY???
    ALP = 1/DT/BSNSQ%KAPPAP *(-1)**PH
    BET = -(-1)**PH*BSNSQ%KAPPA/BSNSQ%KAPPAP

    W%E = ALP*B%E
    IF ((B%INTH.EQ.0).AND.(B%INX.EQ.0)) W%LN = ALP*B%LN
    CALL IHELMP(VISC%P,W,B,-ALP,BET) ! USE THE SAME POWER AS HYPERV'S P

    CALL DEALLOCATE( W )

  ENDIF

  RETURN
  END SUBROUTINE HYPERV
!=======================================================================
  SUBROUTINE DIAGNOST(PSI,CHI)
!=======================================================================
! [USAGE]: 
! PERFORM DIAGNOSIS ON THE POLOIDAL-TOROIDAL TERMS PSI AND CHI
! NOTE THAT BOTH PSI AND CHI MUST BE IN FFF SPACE
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. CHOPSET(~) @ MOD_SCALAR3
! 3. INTEG(~)   @ MOD_SCALAR3
! 4. RTRAN(~)   @ MOD_SCALAR3
! 5. PC2VEL(~)  @ MOD_LEGOPS
! 6. PC2VOR(~)  @ MOD_LEGOPS
! 7. XXDX(~)    @ MOD_LEGOPS
! 8. DELSQH(~)  @ MOD_LEGOPS
! 9. DEL2(~)    @ MOD_LEGOPS
! 10. MULXM(~)  @ MOD_LEGOPS
! 11. CALCXY(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI

  TYPE(SCALAR):: RUR,RUP,UZH
  TYPE(SCALAR):: ROR,ROP,OZH
  ! COMPLEX(P8),DIMENSION(NXCHOPDIM):: PSIAT1,CHIAT1
  COMPLEX(P8),DIMENSION(:),ALLOCATABLE:: PSIAT1,CHIAT1
  REAL(P8):: ENE1,ENE2,VALVOR,VALZMO,VALANG,VALENE,HEL1,VALHEL,PSI_CHECK
  REAL(P8):: PAT1MAX,PAT1MIN,CAT1MAX,CAT1MIN
  INTEGER:: NN,MM,KK,NNMAX,MMMAX,KKMAX

  ! --------------------
  ! CHECK INITIALIZATION
  ! --------------------
  IF(TIM%N.NE.0 .AND. (.NOT. DIAGV%IS_INITIALIZED)) THEN
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'DIAG: WARNING:INITIALIZE INCOMPLETE !!'
  ENDIF

  ! ----------
  ! NORM CHECK
  ! ----------
  ! CHECK IF (M = 0, K = 0) MODE HAS PURELY REAL SPECTRAL COEFF (FFF),
  ! WHICH IS NECESSARY FOR PURELY REAL PHYSICAL FIELDS (PSI AND CHI).
  ! NOTE THAT THE 1ST MLEGS IS A CONSTANT, SO WE USE 2ND RADIAL MODES.
  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) THEN
    IF(ABS(AIMAG(PSI%E(2,1,1))+AIMAG(CHI%E(2,1,1))).GT.1E-18) THEN
      WRITE(6,*) 'DIAG: NORM INCOMPLETE !!!'
      WRITE(6,*) '  PSI%E(2,1,1)=',PSI%E(2,1,1)
      WRITE(6,*) '  CHI%E(2,1,1)=',CHI%E(2,1,1)
      WRITE(6,*) ''
    ENDIF
  ENDIF

  ! ----------------
  ! DEALIASING CHECK
  ! ----------------
  ! CHECK IF RADIAL MODES BEYOND NRCHOPS ARE ZERO
  PSI_CHECK = 0.D0
  IF (PSI%INTH .EQ. 0) THEN
    IF (SIZE(PSI%E, 2) .GE. 2) THEN
      PSI_CHECK = MAXVAL(ABS(PSI%E(NRCHOPS(1)+1:, 1, :))) + &
                  MAXVAL(ABS(PSI%E(NRCHOPS(2)+1:, 2, :)))
    ELSE
      PSI_CHECK = MAXVAL(ABS(PSI%E(NRCHOPS(1)+1:, 1, :)))
    END IF
  ELSEIF (PSI%INTH .EQ. 1) THEN
    PSI_CHECK = MAXVAL(ABS(PSI%E(NRCHOPS(2)+1:, 1, :)))
  END IF
  IF (PSI_CHECK .GT. 1.0D-12) THEN
    WRITE(*,*) 'DIAG: DEALIASING INCOMPLETE on rank ', MPI_RANK, ' (PSI_CHECK =', PSI_CHECK, ')'
    CALL SPY(PSI%E(:, 1, :))
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_DEALIASING, IERR)
  END IF

  ! ----------------------------
  ! CALCULATION DIVERGENCE CHECK
  ! ----------------------------
  PSI_CHECK = 0.D0
  IF ((PSI%INTH.LE.6).AND.(PSI%INX.LE.5)) THEN
    KKMAX = MIN(5-PSI%INX,SIZE(PSI%E,3)) !NXCHOPDIM)
    MMMAX = MIN(6-PSI%INTH,SIZE(PSI%E,2)) !NTCHOP)
    NNMAX = MIN(5,NRCHOP)
    DO KK=1,KKMAX
      DO MM=2,MMMAX
        DO NN=1,NNMAX
          IF(ABS(PSI%E(NN,MM,KK)).GT.100.) THEN
            PSI_CHECK = 1.0
            WRITE(6,'(A,1P,E12.5,A,I6,A,I3,A,I3,A,1P,E12.5)') &
              'DIAG: DIVERGENCE @ t=', TIM%T, ' step=', TIM%N, &
              ' (n,m,k)=(', NN, ',', MM + PSI%INTH, ',', KK + PSI%INX, ') val=', PSI%E(NN, MM, KK)
          ENDIF
        ENDDO
      ENDDO
    ENDDO
  ENDIF
  CALL MPI_BARRIER(MPI_COMM_IVP, IERR)
  IF (PSI_CHECK .GT. 0.0) THEN
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_DIVERGENCE, IERR)
  ENDIF

  ! --------------
  ! MAIN DIAGNOSIS 
  ! --------------

  IF(MOD(TIM%N,DIAGV%IT1).EQ.0) THEN
    CALL ALLOCATE( RUR )
    CALL ALLOCATE( RUP )
    CALL ALLOCATE( UZH )
    CALL ALLOCATE( ROR )
    CALL ALLOCATE( ROP )
    CALL ALLOCATE( OZH )

    CALL CHOPSET(3)

    CALL PC2VEL(PSI,CHI,RUR,RUP,UZH,'H') ! RUR, RUP, UZ/(1-X)^2
    CALL PC2VOR(PSI,CHI,ROR,ROP,OZH,'H') ! ROR, ROP, OZ/(1-X)^2

    !> Z-DIR VORTICITY 
    VALVOR= INTEG(OZH)

    !> Z-DIR MOMENTUM 
    VALZMO= INTEG(UZH)

    !> ANGULAR MOMENTUM 
    RUR=PSI
    RUR%LN=0
    CALL XXDX(RUR,RUP)
    VALANG = -INTEG(RUP)

    !> KINETIC ENERGY P157
    ! NOTE:
    ! PSI AND CHI CONTAINS LOG TERMS, FOR ENE2, THE LOG TERMS ARE FULLY CONSIDERED IN DEL2 AND DELSQH
    ! HOWEVER, FOR ENE1, WHILE DELSQH CONTAINS THE LOG TERM, ITS DOT PRODUCT WITH PSI DID NOT CONSIDER
    ! THE LOG TERM IN PSI, SO WE NEED TO DO IT MANUALLY.
    ! 
    ! WE NOTE THAT INT[DEL2(PSI%E+PSI%LN)*DELSQH(PSI%E+PSI%LN)] 
    ! = INT[DEL2(PSI%E)*DELSQH(PSI%E+PSI%LN)] + INT[DEL2(PSI%LN)*DELSQH(PSI%E+PSI%LN)]
    ! IF WE DID NOT MODIFY THE ORIGINAL LOG TERM, ENE1 WOULD ONLY CONTAIN THE FIRST TERM
    ! 
    ! NOW, BECAUSE PSI%LN IS PURELY RADIAL, THE VOLUME INTEGRAL OF ITS PRODUCT WITH DELSQH(PSI%E+PSI%LN)
    ! WILL ONLY CONTAIN THE RADIAL PART, SO
    ! DEL2(PSI%LN)*DELSQH(PSI%E) 
    ! = DEL2(PSI%LN)*DEL2(PSI%E+PSI%LN)
    ! = DIV[PSI%LN*GRAD(PSI%E+PSI%LN)-(PSI%E+PSI%LN)*GRAD(PSI%LN)] + (PSI%E+PSI%LN)*DEL2(PSI%LN)
    ! THE INTEGRATION OF A DIV TERM IS ZERO, SO WE ONLY NEED TO CONSIDER THE SECOND TERM, SO
    ! = PSI%E*DELSQH(PSI%LN) + PSI%LN*DELSQH(PSI%LN)
    ! THEREFORE, 
    ! INT[DEL2(PSI%E+PSI%LN)*DELSQH(PSI%E+PSI%LN)]
    ! = INT[DEL2(PSI%E)*DELSQH(PSI%E+2*PSI%LN)] + INT[PSI%LN*DELSQH(PSI%LN)]
    ! THE SECOND TERM REPRESENTS THE SELF-ENERGY OF THE LOGARITHMIC TERM. HOWEVER, THE ENERGY OF THE
    ! CORRESPONDING VELOCITY FIELD DIVERGES AS R GOES TO INFTY, AND WE EXCLUDE THIS CONTRIBUTION WHILE
    ! STILL CONSIDERING THE CROSS TERM BETWEEN THE REST OF THE VELOCITY FIELD AND THE LOG TERM.
    RUP=PSI
    IF ((RUP%INTH.EQ.0).AND.(RUP%INX.EQ.0)) RUP%LN=2*RUP%LN
    CALL DELSQH(RUP,RUR) ! RUR = DELSQH(PSI)/(1-X)^2
    CALL RTRAN(RUR,1)
    RUP=PSI
    RUP%LN=0
    CALL RTRAN(RUP,1)
    ENE1= PRODCT(RUR,RUP) ! PRODCT(A,B) CALCULATES THE PRODUCT OF A*B*(1-X)^2 AND INTEGRATES OVER THE DOMAIN

    CALL DEL2(CHI,RUP)
    CALL RTRAN(RUP,1)
    CALL DELSQH(CHI,RUR)
    CALL RTRAN(RUR,1)
    ENE2= PRODCT(RUR,RUP)
    VALENE = -ENE1+ENE2 ! PRODCT uses MPI_ALLREDUCE

    !> HELICITY P157
    CALL DELSQH(PSI,RUR)
    CALL RTRAN(RUR,1)
    HEL1 =PRODCT(RUR,RUP)
    VALHEL = 2*HEL1
    CALL DEALLOCATE( RUR )
    CALL DEALLOCATE( RUP )
    CALL DEALLOCATE( UZH )

    !> STORE THE INITIAL VALUES
    IF(TIM%N .EQ.0) THEN
      DIAGV%IS_INITIALIZED = .TRUE.
      DIAGV%VORI = VALVOR
      DIAGV%ZMOMI = VALZMO
      DIAGV%ENEI = VALENE
      DIAGV%HELI = VALHEL
      DIAGV%ANGI = VALANG
    ENDIF

    IF (MPI_RANK.EQ.0) THEN
      WRITE(*,*) '<<< DIAGNOSTICS >>>'
      WRITE(6,60) TIM%T,TIM%N
60     FORMAT('TIM%T=',E13.4,' TIM%N=',I8)
      WRITE(6,62) ADV%X,ADV%Y
62     FORMAT('ADV%X=',E13.5,'  ADV%Y=',E13.5)
70     FORMAT(A12,'=',E23.15, '  FRACTIONAL CHANGE=',E23.15)
    ENDIF

    IF (PSI%INTH.EQ.0) THEN ! PROCS WITH M=0 MODES
      ALLOCATE(PSIAT1(SIZE(PSI%E,3)),CHIAT1(SIZE(CHI%E,3)))
      PSIAT1= CALCAT1(PSI)
      CHIAT1= CALCAT1(CHI)
      PAT1MAX = MAXVAL(ABS(PSIAT1))
      PAT1MIN = MINVAL(ABS(PSIAT1))
      CAT1MAX = MAXVAL(ABS(CHIAT1))
      CAT1MIN = MINVAL(ABS(CHIAT1))
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,PAT1MAX,1,MPI_DOUBLE_PRECISION,MPI_MAX,SUBCOMM_1,IERR)
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,PAT1MIN,1,MPI_DOUBLE_PRECISION,MPI_MIN,SUBCOMM_1,IERR)
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,CAT1MAX,1,MPI_DOUBLE_PRECISION,MPI_MAX,SUBCOMM_1,IERR)
      CALL MPI_ALLREDUCE(MPI_IN_PLACE,CAT1MIN,1,MPI_DOUBLE_PRECISION,MPI_MIN,SUBCOMM_1,IERR)

      IF (PSI%INX.EQ.0) THEN ! PROC WITH M=0, K=0 MODE
        IF (PAT1MAX-PAT1MIN.GT.1.0E-10 .OR. &
          CAT1MAX-CAT1MIN.GT.1.0E-10) THEN
          WRITE(6,81) 'PSIAT1(KK=1)=',ABS(PSIAT1(1)),PAT1MAX-PAT1MIN
          WRITE(6,81) 'CHIAT1(KK=1)=',ABS(CHIAT1(1)),CAT1MAX-CAT1MIN
81      FORMAT(A,E18.9, ' MAXMIN=',E18.9)              
        ENDIF
      ENDIF
      DEALLOCATE(PSIAT1,CHIAT1)
    ENDIF

    IF (MPI_RANK.EQ.0) THEN
      WRITE(6,*) 'CFL#=',CFL*TIM%DT

      IF(DIAGV%VORI.NE.0.0) THEN
        WRITE(6,70) 'VORTICITY',VALVOR,(VALVOR-DIAGV%VORI)&
                                      /DIAGV%VORI
      ELSE
        WRITE(6,70) 'VORTICITY',VALVOR
      ENDIF

      IF(DIAGV%ZMOMI.NE.0.0) THEN
        WRITE(6,70) 'Z-MOMENTUM',VALZMO,(VALZMO-DIAGV%ZMOMI)&
                                        /DIAGV%ZMOMI
      ELSE
        WRITE(6,70) 'Z-MOMENTUM',VALZMO
      ENDIF

      WRITE(6,70) 'ENERGY',VALENE,-(DIAGV%ENEI-VALENE)/DIAGV%ENEI

      IF(DIAGV%HELI.NE.0.0) THEN
        WRITE(6,70) 'HELICITY',VALHEL,-(DIAGV%HELI-VALHEL)&
                                      /DIAGV%HELI
      ELSE
        WRITE(6,70) 'HELICITY',VALHEL
      ENDIF

      IF(DIAGV%ANGI.NE.0.0) THEN
      WRITE(6,70) 'INTEG_ANGMOM ',VALANG,-(DIAGV%ANGI-VALANG)&
                                          /DIAGV%ANGI
      ELSE
        WRITE(6,70) 'INTEG_ANGMOM ',VALANG
      ENDIF
    ENDIF

    CALL ALLOCATE(RUR)
    CALL MULXM(OZH,RUR)
    CALL MULXM(RUR,OZH)
    CALL DEALLOCATE(RUR)
    CALL CALCXY(ROR,ROP,OZH)
    CALL CHOPSET(-3)
    CALL DEALLOCATE( ROR )
    CALL DEALLOCATE( ROP )
    CALL DEALLOCATE( OZH )
  ENDIF

  RETURN
  END SUBROUTINE DIAGNOST
!=======================================================================
  SUBROUTINE CALCXY(ROR,ROP,OZH)
!=======================================================================
! [USAGE]: 
! COMPUTE THE LOCATION OF THE VORTEX (<X>,<Y>) BY WEIGHTING X AND Y
! WITH ENSTROPHY. THIS ROUTINE IS FOR MONITORING PURPOSE AND DOES NOT
! AFFECT THE NONLINEAR COMPUTATION. 
! [PARAMETERS]:
! ROR >> R*OMEGA_R TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! ROP >> R*OMEGA_P TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! OZH >> OMEGA_Z TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! [DEPENDENCIES]:
! 1. TOFP(~)      @ MOD_SCALAR3
! 2. TOFF(~)      @ MOD_SCALAR3
! 3. INTEG(~)     @ MOD_SCALAR3
! 4. ABSVEC2(~)   @ MOD_MARCH
! 5. MULRCOSTH(~) @ MOD_MARCH
! 6. MULRSINTH(~) @ MOD_MARCH
! 7. MULR2(~)     @ MOD_MARCH
! [NOTE]:
! THIS ROUTINE IS INSERTED HERE TO SAVE THE TIME FOR TRANSFORMS THAT
! WOULD HAPPEN IF THIS ROUTINE WERE CALLED FROM SUBROUTINE DIAG.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: ROR,ROP,OZH

  REAL(P8):: VALENS,VALX,VALY,VALR

  IF (MPI_RANK.EQ.0) OPEN(UNIT=14,FILE=TRIM(ADJUSTL(FILES%SAVEDIR))//'coresize.dat',POSITION='APPEND')

  CALL TOFP(ROR)
  CALL TOFP(ROP)
  CALL TOFP(OZH)
  CALL ABSVEC2(ROR,ROP,OZH,OZH)

  ROR=OZH
  CALL TOFF(ROR)
  VALENS=INTEG(ROR)

  ROR=OZH
  CALL MULRCOSTH(ROR)
  CALL TOFF(ROR)
  VALX=INTEG(ROR)/VALENS

  ROR=OZH
  CALL MULRSINTH(ROR)
  CALL TOFF(ROR)
  VALY=INTEG(ROR)/VALENS

  ROR=OZH
  CALL MULR2(ROR)
  CALL TOFF(ROR)
  VALR=SQRT(INTEG(ROR)/VALENS)

  IF (MPI_RANK.EQ.0) THEN
    WRITE(6,60) TIM%T,VALX,VALY,VALR
    WRITE(14,'(4E14.6)') TIM%T,VALX,VALY,VALR
    CLOSE(14)
60   FORMAT('T= ',E10.3,' <X>= ',E10.3,' <Y>= ',E10.3,' <R>= ',E10.3)
  ENDIF

  IF(TIM%N.EQ.0) THEN
    ADV%T0=TIM%T-TIM%DT
    ADV%X0=VALX
    ADV%Y0=VALY
    ADV%T1=TIM%T
    ADV%X1=ADV%X0
    ADV%Y1=ADV%Y0
  ELSE
    ADV%T0=ADV%T1
    ADV%X0=ADV%X1
    ADV%Y0=ADV%Y1
    ADV%T1=TIM%T
    ADV%X1=VALX
    ADV%Y1=VALY
  ENDIF

  RETURN
  END SUBROUTINE CALCXY
!=======================================================================
  SUBROUTINE ABSVEC2(U,V,W,A)
!=======================================================================
! [USAGE]: 
! COMPUTE THE LOCATION OF THE VORTEX (<X>,<Y>) BY WEIGHTING X AND Y
! WITH ENSTROPHY. THIS ROUTINE IS FOR MONITORING PURPOSE AND DOES NOT
! AFFECT THE NONLINEAR COMPUTATION. 
! [PARAMETERS]:
! U >> R*U_R TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! V >> R*U_PHI TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! W >> U_Z TERM IN A SCALAR-TYPE VARIABLE IN A PPP SPACE
! A >> ON ENTRY, STORES THE ADVECTIVE VELOCITY INFORMATION
!      DIVIDED BY (1-X)**2.
!      PREFERABLY CHOOSE ONE OF U, V, AND W
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: U,V,W,A
  INTEGER:: I,MM,KK,NRTMP
  REAL(P8):: AAA,BBB
  REAL(P8):: RUR,RVR,WR
  REAL(P8):: RUI,RVI,WI,R,F

  NRTMP = MIN(SIZE(U%E,1),NR-U%INR)
  DO KK=1,SIZE(U%E,3) !NX
    DO MM=1,NTH
      DO I=1,NRTMP !NR
        R  = TFM%R(I+U%INR)
        F = (1-TFM%X(I+U%INR))**2
        RUR=REAL(U%E(I,MM,KK))
        RUI=AIMAG(U%E(I,MM,KK))
        RVR=REAL(V%E(I,MM,KK))
        RVI=AIMAG(V%E(I,MM,KK))
        WR=REAL(W%E(I,MM,KK))
        WI=AIMAG(W%E(I,MM,KK))
        AAA = ( (RUR**2+RVR**2)/R**2 + WR**2)
        BBB = ( (RUI**2+RVI**2)/R**2 + WI**2)
        A%E(I,MM,KK) = CMPLX(AAA,BBB,P8)/F
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE ABSVEC2
!=======================================================================
  SUBROUTINE MULRCOSTH(A)
!=======================================================================
! [USAGE]: 
! MULTIPLY R*COS(TH) TO A FIELD A; 
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE. ON EXIT, MULTIPLIED BY R*COS(TH)
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: A
  
  REAL(P8):: R,Z,THR,THI,AAA,BBB
  INTEGER:: KK,NN,MM,NRTMP
  
  CALL TOFP(A)

  NRTMP = MIN(SIZE(A%E,1),NR-A%INR)
  DO KK=1,SIZE(A%E,3) !NX
    DO MM=1,NTH
      DO NN=1,NRTMP !NR
        !Z  = TFM%Z(KK+A%INX)
        R  = TFM%R(NN+A%INR)
        THR = TFM%THR(MM)
        THI = TFM%THI(MM)
        AAA = R*COS(THR)*REAL(A%E(NN,MM,KK))
        BBB = R*COS(THI)*AIMAG(A%E(NN,MM,KK))
        A%E(NN,MM,KK)= CMPLX(AAA,BBB,P8)
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE MULRCOSTH
!=======================================================================
  SUBROUTINE MULRSINTH(A)
!=======================================================================
! [USAGE]: 
! MULTIPLY R*SIN(TH) TO A FIELD A IN PPP-SPACE
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE. ON EXIT, MULTIPLIED BY R*SIN(TH)
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: A

  REAL(P8):: R,Z,THR,THI,AAA,BBB
  INTEGER:: KK,NN,MM,NRTMP

  CALL TOFP(A)

  NRTMP = MIN(SIZE(A%E,1),NR-A%INR)
  DO KK=1,SIZE(A%E,3) !NX
    DO MM=1,NTH
      DO NN=1,NRTMP !NR
        !Z  = TFM%Z(KK+A%INX)
        R  = TFM%R(NN+A%INR)
        THR = TFM%THR(MM)
        THI = TFM%THI(MM)
        AAA = R*SIN(THR)*REAL(A%E(NN,MM,KK))
        BBB = R*SIN(THI)*AIMAG(A%E(NN,MM,KK))
        A%E(NN,MM,KK)= CMPLX(AAA,BBB,P8)
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE MULRSINTH
!=======================================================================
  SUBROUTINE MULR2(A)
!=======================================================================
! [USAGE]: 
! MULTIPLY R**2 TO A FIELD A
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE. ON EXIT, MULTIPLIED BY R**2
! [NOTE]:
! THIS IS A CUSTOM ROUTINE FOR CALCXY.
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: A

  REAL(P8):: R,Z,THR,THI,AAA,BBB
  INTEGER:: KK,NN,MM,NRTMP

  CALL TOFP(A)

  NRTMP = MIN(SIZE(A%E,1),NR-A%INR)
  DO KK=1,SIZE(A%E,3) !NX
    DO MM=1,NTH
      DO NN=1,NRTMP !NR
        !Z  = TFM%Z(KK+A%INX)
        R  = TFM%R(NN+A%INR)
        !THR = TFM%THR(MM)
        !THI = TFM%THI(MM)
        AAA = R**2*REAL(A%E(NN,MM,KK))
        BBB = R**2*AIMAG(A%E(NN,MM,KK))
        A%E(NN,MM,KK)= CMPLX(AAA,BBB,P8)
      ENDDO
    ENDDO
  ENDDO

  RETURN
  END SUBROUTINE MULR2
!=======================================================================
  SUBROUTINE FREEADJ()
!=======================================================================
! [USAGE]: 
! ADJUST FREESTREAM VELOCITY SUCH THAT THE CENTER OF VORTICITY
! DISTRIBUTION IS AT THE CENTER OF THE COMPUTATIONAL DOMAIN.
! [PARAMETERS]:
! N/A
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
  REAL(P8):: FREEDT,VX,VY

  FREEDT = ADV%INT*TIM%DT
  VX = (ADV%X1-ADV%X0)/(ADV%T1-ADV%T0) ! VELOCITY OF THE CENTER OF VORTEX
  VY = (ADV%Y1-ADV%Y0)/(ADV%T1-ADV%T0)
  ADV%UX = ADV%UX - ADV%X1/FREEDT - VX ! CANCEL OUT THE MOTION OF THE VORTEX CENTER
  ADV%UY = ADV%UY - ADV%Y1/FREEDT - VY
  
  NADD%U = SQRT(ADV%UX**2+ADV%UY**2) ! ADVECTIVE VELOCITY IN R-THETA PLANE
  
  IF(NADD%U.EQ.0.0) THEN
    NADD%ANG = 0.0
  ELSE
    IF(ADV%UY >= 0) THEN
      NADD%ANG = ACOS(ADV%UX/NADD%U)
    ELSE 
      NADD%ANG = -1.0*ACOS(ADV%UX/NADD%U)
    ENDIF
  ENDIF

  IF (MPI_RANK.EQ.0) THEN
    WRITE(6,60) TIM%N,TIM%T
60   FORMAT('FREEADJ: TIM%N=',I5,' TIM%T=',F10.6)
    WRITE(6,61) ADV%UX,ADV%UY,ADV%UZ
61   FORMAT('FREEADJ: ADV%UX=',E18.10,'  UY=',E18.10,' UZ=',E18.10)
    WRITE(6,62) NADD%U,NADD%ANG
62   FORMAT('FREEADJ: NADD%U=',E18.10,' ANG=',E18.10)
  ENDIF

  RETURN
  END SUBROUTINE FREEADJ
!=======================================================================
  SUBROUTINE REMOVE(PSI,CHI)
!=======================================================================
! [USAGE]: 
! KILL THE VORTICES WHICH MOVES AWAY FROM THE COMPUTATIONAL DOMAIN
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. RTRAN(~)        @ MOD_SCALAR3
! 3. CHOPSET(~)      @ MOD_SCALAR3
! 4. DELSQH(~)       @ MOD_LEGOPS
! 5. IDELSQH(~)      @ MOD_LEGOPS
! 6. DEL2(~)         @ MOD_LEGOPS
! 7. IDEL2(~)        @ MOD_LEGOPS
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI

  TYPE(SCALAR):: WK
  INTEGER:: NS,NS0,MM,KK,I
  REAL(P8):: LN

  IF(RMV%SW.EQ.1) THEN
    CALL ALLOCATE( WK )
    NS = NR*2/3 ! THE OUTSIDE 1/3 OF THE RADIAL COLLOCATION PTS ARE TOO FAR ARWAY
    NS0 = MIN(NS+4,NR)

    CALL DELSQH(PSI,WK)
    CALL RTRAN(WK,1) ! WK IN PFF SPACE

    ! WK%E(NS0:NR,2:NTCHOP,1:NX)=0
    ! IF (NX>1) WK%E(NS0:NR,1,2:NX)=0
    IF (WK%INTH.EQ.0) THEN
      WK%E(NS0:NR,2:,:)=0
      IF (NX>1) THEN
        ! IF (WK%INX.EQ.0) THEN
        !   WK%E(NS0:NR,1,2:)=0
        ! ELSE
        !   WK%E(NS0:NR,1,:)=0
        ! ENDIF
        WK%E(NS0:NR,1,MAX(2-WK%INX,1):)=0
      ENDIF
    ELSE
      WK%E(NS0:NR,:,:)=0
    ENDIF

    DO KK=1,SIZE(WK%E,3) !NX (old code's PFF contains NX pts in x-dir)
      DO MM=1,SIZE(WK%E,2) !NTCHOP
        ! IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)*TFM%W(NS:NR)
        DO I=1,5
          WK%E(NS:NR,MM,KK)=SMOOTH(WK%E(NS:NR,MM,KK))
        ENDDO
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)/TFM%W(NS:NR)
      ENDDO
    ENDDO

    CALL RTRAN(WK,-1)
    CALL IDELSQH(WK,PSI)

    CALL CHOPSET(2)
    CALL DEL2(CHI,WK)
    CALL RTRAN(WK,1)

    IF (WK%INTH.EQ.0) THEN
      WK%E(NS0:NR,2:,:)=0
      IF (NX>1) WK%E(NS0:NR,1,MAX(2-WK%INX,1):)=0
    ELSE
      WK%E(NS0:NR,:,:)=0
    ENDIF

    DO KK=1,SIZE(WK%E,3) !NX
      DO MM=1,SIZE(WK%E,2) !NTCHOP
        ! IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)*TFM%W(NS:NR) &
                                            /(1-TFM%X(NS:NR))**2
        DO I=1,5
          WK%E(NS:NR,MM,KK)=SMOOTH(WK%E(NS:NR,MM,KK))
        ENDDO
        WK%E(NS:NR,MM,KK)= WK%E(NS:NR,MM,KK)/TFM%W(NS:NR) &
                                            *(1-TFM%X(NS:NR))**2
      ENDDO
    ENDDO
    CALL CHOPSET(-2)
    CALL RTRAN(WK,-1)
    LN=CHI%LN
    CALL IDEL2(WK,CHI,LN)

    IF (MPI_RANK.EQ.0) WRITE(6,60) TIM%N,TFM%R(NS)
60     FORMAT('REMOVE: TIM%N=',I5,'  R >=',F6.2)

  CALL DEALLOCATE( WK )
  ELSE
    IF (MPI_RANK.EQ.0) WRITE(*,*) 'REMOVE: RMV%SW IS SET TO 0.'
  ENDIF

  RETURN
  END SUBROUTINE REMOVE
!=======================================================================
  SUBROUTINE ENEMON(PSI,CHI,EM,EK)
!=======================================================================
! [USAGE]: 
! COMPUTE ENERGY FOR EACH AZIMUTHAL AND AXIAL WAVE NUMBER
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! EM >> ENERGY FOR EACH M (AZIMUTHAL WAVENUMBER)
! EK >> ENERGY FOR EACH K (AXIAL WAVENUMBER)
! [DEPENDENCIES]:
! 1. (DE)ALLOCATE(~) @ MOD_SCALAR3
! 2. RTRAN(~)        @ MOD_SCALAR3
! 3. DELSQH(~)       @ MOD_LEGOPS
! 4. DEL2(~)         @ MOD_LEGOPS
! 5. PRODCTM(~)      @ MOD_MARCH
! 6. PRODCTK(~)      @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI, W1,W2
  REAL(P8):: EM(NTCHOP)
  REAL(P8),OPTIONAL:: EK(NXCHOP)

  CALL ALLOCATE(W1)
  CALL ALLOCATE(W2)

  !> ENERGY P157
  W1=PSI
  IF ((PSI%INTH.EQ.0).AND.(PSI%INX.EQ.0)) W1%LN=2*PSI%LN
  CALL DELSQH(W1,W2)
  CALL RTRAN(W2,1)
  W1=PSI
  W1%LN=0
  CALL RTRAN(W1,1)
  EM= PRODCTM(W2,W1)
  IF (PRESENT(EK)) THEN
  EK= PRODCTK(W2,W1)
  END IF
  
  CALL DEL2(CHI,W1)
  CALL RTRAN(W1,1)
  CALL DELSQH(CHI,W2)
  CALL RTRAN(W2,1)
  EM= -EM+PRODCTM(W2,W1)
  IF (PRESENT(EK)) THEN
  EK= -EK+PRODCTK(W2,W1)
  END IF

  CALL DEALLOCATE(W1)
  CALL DEALLOCATE(W2)

  RETURN
  END SUBROUTINE ENEMON
!=======================================================================
  SUBROUTINE HYPADJ(PSI,CHI,NUP)
!=======================================================================
! [USAGE]: 
! ADJUST HYPERVISCOSITY FROM M(AZIMUTHAL)-ENERGY SPECTRUM
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE IN A FFF SPACE
! NUP >> HYPERVISCOSITY TO CONFINE THE EFFECT OF DISSIPATION
! [DEPENDENCIES]:
! 1. CHOPSET(~) @ MOD_SCALAR3
! 2. ENEMON(~) @ MOD_MARCH
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR):: PSI,CHI
  REAL(P8):: NUP

  REAL(P8),DIMENSION(:),ALLOCATABLE:: EM,EK
  REAL(P8),DIMENSION(:),ALLOCATABLE:: SPM,SPK

  REAL(P8):: SUMM,SUMK,FAC,DX,X,SUM,SUMO
  INTEGER:: IS,IE,NM,NK,I

  ALLOCATE( EM(NTCHOP), EK(NXCHOP) )

  CALL CHOPSET(2)
  CALL ENEMON(PSI,CHI,EM,EK)
  CALL CHOPSET(-2)

  IS = SIZE(EM)/3
  IE = SIZE(EM)-2
  NM = IE-IS+1

  ALLOCATE(SPM(NM))

  SPM = LOG10(EM(IS:IE))
  SUMM = 0
  IS = SIZE(EK)/3
  IE = SIZE(EK)
  NK = IE-IS+1

  ALLOCATE(SPK(NK))

  SPK = LOG10(EK(IS:IE))
  SUMK = 0

  DX = 2.0D0/(NM-1)                                                  ! DOT PRODUCT WITH LEGENDRE POLYNOMIAL P_2(X)
  
  DO I=1,NM
    X  = -1+2.0D0*(I-1)/(NM-1)
    FAC = 1
    IF(I.EQ.1 .OR. I.EQ.NM) FAC=0.5D0
    SUMM=SUMM+ FAC*SPM(I)*DX*SQRT(5.0D0/8)*(3*X**2-1)
  ENDDO

  DX = 2.0D0/(NK-1)

  DO I=1,NK
    X  = -1+2.0D0*(I-1)/(NK-1)
    FAC = 1
    IF(I.EQ.1 .OR. I.EQ.NK) FAC=0.5D0
    SUMK=SUMK+ FAC*SPK(I)*DX*SQRT(5.0D0/8)*(3*X**2-1)
  ENDDO

  IF(FIRST.EQ.0) THEN
    FIRST=1
    SUMMO=SUMM
    SUMKO=SUMK
    NUPB = 0.2/(1.5D0*NRCHOP**2/ELL**2)**(VISC%P/2)
  ENDIF

  IF(SUMM.GT.SUMK) THEN
    SUMO = (3*SUMMO+SUMKO)/4
    SUM  = (3*SUMM+SUMK)/4
  ELSE
    SUMO = (SUMMO+3*SUMKO)/4
    SUM  = (SUMM+3*SUMK)/4
  ENDIF

  SUM = 2*(SUM-SUMO) +SUM + 0.2
  SUM = MIN(3.0D0,MAX(-0.5D0,1.5*SUM))
  NUP = (1+SUM)*NUP
  IF(NUP.LT.NUPB) NUP=NUPB

  IF (MPI_RANK.EQ.0) WRITE(6,60) TIM%T,NUP,SUMM,SUMK
60   FORMAT('HYPADJ:T= ',1PE10.3,' NUP= ',1PE10.3,' SUMM= ', &
            1PE10.3, ' SUMK= ',1PE10.3)
  SUMMO=SUMM
  SUMKO=SUMK

  DEALLOCATE( EM, EK, SPM, SPK )

  RETURN
  END SUBROUTINE HYPADJ
! ======================================================================

!=======================================================================
!============================= FUNCTIONS ===============================
!=======================================================================
!   FUNCTION PRODCTM(A,B)
! !=======================================================================
! ! [USAGE]: 
! ! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! ! FOR EACH AZIMUTHAL WAVENUMBER.
! ! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! ! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! ! [PARAMETERS]:
! ! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! [UPDATES]:
! ! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! !=======================================================================
!   IMPLICIT NONE
!   TYPE(SCALAR):: A,B

!   COMPLEX(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NTCHOP)
!   REAL(P8),DIMENSION(NTCHOP):: PRODCTM
!   INTEGER:: MM,KK

!   IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
!     IF (MPI_RANK.EQ.0) THEN
!       WRITE(*,*) 'PRODCT:NOT IN PFF_SPACE'
!       WRITE(*,*) 'A%SPACE,B%SPACE=',A%SPACE,B%SPACE
!     ENDIF
!     STOP
!   ENDIF

!   IF(A%LN.NE.0.0 .OR. B%LN.NE.0.0) THEN
!     IF (MPI_RANK.EQ.0) WRITE(*,*) 'PRODCT:LOGTERM NOT ZERO'
!   ENDIF

!   ALLOCATE(PROD(NR,SIZE(A%E,2)))
!   PROD=0

!   DO KK = 1,SIZE(A%E,3) !NX
!     !IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
!     DO MM = 1,SIZE(A%E,2) !NTCHOP
!       ! M = 0
!       IF (MM+A%INTH.EQ.1) THEN
!         PROD(:,1) = PROD(:,1)+A%E(:NR,1,KK)*CONJG(B%E(:NR,1,KK))
!       ! M > 0
!       ELSE
!       PROD(:,MM) = PROD(:,MM)+2*(REAL(A%E(:NR,MM,KK)) &
!                                 *REAL(B%E(:NR,MM,KK)) &
!                                 +AIMAG(A%E(:NR,MM,KK))&
!                                 *AIMAG(B%E(:NR,MM,KK)))
!       ENDIF
!     ENDDO
!   ENDDO

!   PRODCTM = 0.D0
!   DO MM=1,SIZE(A%E,2) !NTCHOP
!     ! NOTE:
!     ! PRODCTM IS CALCULATED DIRECTLY USING GAUSS-LEGENDRE QUADRATURE
!     ! THERE IS NO REASON BEHIND *TFM%PF(1,1,1)*TFM%NORM(1,1)
!     ! PRODCTM(MM+A%INTH) = SUM((PROD(:,MM)*TFM%W)*TFM%PF(1,1,1))
!     ! PRODCTM(MM+A%INTH) = 4*PI*ZLEN0*ELL2*PRODCTM(MM+A%INTH)*TFM%NORM(1,1)
!     PRODCTM(MM+A%INTH) = SUM(PROD(:,MM)*TFM%W)
!     PRODCTM(MM+A%INTH) = 2*PI*ZLEN0*ELL2*PRODCTM(MM+A%INTH)
!   ENDDO
!   CALL MPI_ALLREDUCE(MPI_IN_PLACE,PRODCTM,NTCHOP,MPI_DOUBLE_PRECISION, &
!                   MPI_SUM, MPI_COMM_IVP, IERR)

!   DEALLOCATE(PROD)
!   RETURN
!   END FUNCTION PRODCTM
! !=======================================================================
!   FUNCTION PRODCTK(A,B)
! !=======================================================================
! ! [USAGE]: 
! ! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! ! FOR EACH AXIAL WAVENUMBER.
! ! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! ! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! ! [PARAMETERS]:
! ! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! [UPDATES]:
! ! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! !=======================================================================
!   IMPLICIT NONE
!   TYPE(SCALAR):: A,B

!   ! COMPLEX(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NXCHOP)
!   REAL(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NXCHOP)
!   REAL(P8),DIMENSION(NXCHOPDIM):: PRODCTK_TEMP
!   REAL(P8),DIMENSION(NXCHOP):: PRODCTK
!   INTEGER:: MM,KK,KH,CK,CM

!   IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
!     IF (MPI_RANK.EQ.0) THEN
!       WRITE(*,*) 'PRODCT:NOT IN PFF_SPACE'
!       WRITE(*,*) 'A%SPACE,B%SPACE=',A%SPACE,B%SPACE
!     ENDIF
!     STOP
!   ENDIF

!   IF(A%LN.NE.0.0 .OR. B%LN.NE.0.0) THEN
!     IF (MPI_RANK.EQ.0) WRITE(*,*) 'PRODCT:LOGTERM NOT ZERO'
!   ENDIF

!   ALLOCATE(PROD(NR,SIZE(A%E,3)))
!   PROD=0

!   DO KK = 1,SIZE(A%E,3) !NXCHOP
!     IF(KK+A%INX.EQ.1) THEN
!       CK=2
!       KH=1
!     ELSE
!       CK=1
!       !KH=NX-KK+2
!     ENDIF

!     DO MM = 1,SIZE(A%E,2) !NTCHOP
!       CM=1
!       IF(MM+A%INTH.EQ.1) CM=2
!       ! PROD(:,KK)=PROD(:,KK)+1.0D0/CK/CM* & 
!       !            2*REAL(A%E(:NR,MM,KK)*CONJG(B%E(:NR,MM,KK)) &
!       !                   +B%E(:NR,MM,KH)*CONJG(A%E(:NR,MM,KH)))
!       PROD(:,KK)=PROD(:,KK)+1.0D0/CK/CM* & 
!                   2*REAL(A%E(:NR,MM,KK)*CONJG(B%E(:NR,MM,KK))) 
!                         !+B%E(:NR,MM,KH)*CONJG(A%E(:NR,MM,KH)))
!     ENDDO
!   ENDDO

!   PRODCTK_TEMP = 0.D0
!   DO KK=1,SIZE(A%E,3) !NXCHOP
!     ! NOTE:
!     ! THERE IS NO POINT OF *TFM%PF(1,1,1)*TFM*NORM(1,1)
!     ! PRODCT IS CALCULATED DIRECTLY USING GAUSS-LEGENDRE QUADRATURE
!     ! PRODCTK_TEMP(KK+A%INX) = SUM((PROD(:,KK)*TFM%W)*TFM%PF(1,1,1))
!     ! PRODCTK_TEMP(KK+A%INX) = 4*PI*ZLEN0*ELL2*PRODCTK_TEMP(KK+A%INX)*TFM%NORM(1,1)
!     PRODCTK_TEMP(KK+A%INX) = SUM(PROD(:,KK)*TFM%W)
!     PRODCTK_TEMP(KK+A%INX) = 2*PI*ZLEN0*ELL2*PRODCTK_TEMP(KK+A%INX)
!   ENDDO
!   CALL MPI_ALLREDUCE(MPI_IN_PLACE,PRODCTK_TEMP,NXCHOPDIM,MPI_DOUBLE_PRECISION, &
!                   MPI_SUM, MPI_COMM_IVP, IERR)

!   DO KK = 1,NXCHOP
!     KH = NXCHOPDIM - KK + 2
!     IF (KK.EQ.1) KH = 1
!     PRODCTK(KK) = PRODCTK_TEMP(KK) + PRODCTK_TEMP(KH)
!   ENDDO

!   DEALLOCATE(PROD)
!   RETURN
!   END FUNCTION PRODCTK
!=======================================================================
  FUNCTION PRODCTM(A,B)
!=======================================================================
! [USAGE]: 
! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! FOR EACH AZIMUTHAL WAVENUMBER.
! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! [PARAMETERS]:
! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR), INTENT(IN):: A,B
  REAL(P8):: PRODCTM(NTCHOP),PRODCTMK(NTCHOP,NXCHOP)
  INTEGER:: MM,KK

  PRODCTMK = PRODCT_MK_HALFK(A,B)
  PRODCTM = 0.D0
  PRODCTM = SUM(PRODCTMK, DIM=2)

  RETURN
  END FUNCTION PRODCTM
!=======================================================================
  FUNCTION PRODCTK(A,B)
!=======================================================================
! [USAGE]: 
! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! FOR EACH AXIAL WAVENUMBER.
! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! [PARAMETERS]:
! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR), INTENT(IN):: A,B
  REAL(P8):: PRODCTK(NXCHOP),PRODCTMK(NTCHOP,NXCHOP)

  PRODCTMK = PRODCT_MK_HALFK(A,B)
  PRODCTK = 0.D0
  PRODCTK = SUM(PRODCTMK, DIM=1)

  RETURN
  END FUNCTION PRODCTK
!=======================================================================
  FUNCTION SMOOTH(A)
!=======================================================================
! [USAGE]: 
! SMOOTHING A SEQUENCE A BY CONVOLUTION
! [INPUTS]:
! A >> A SEQUENCE CONTAINING NOISES
! [OUTPUTS]:
! SMOOTH >> SMOOTHENED SEQUENCE USING CONVOLUTION
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8),DIMENSION(:):: A
  COMPLEX(P8),DIMENSION(SIZE(A)):: SMOOTH

  REAL(P8),DIMENSION(3):: FAE=(/ 0.2D0, 0.3D0, 0.5D0 /)
  REAL(P8):: F
  INTEGER:: NI,I,NB,NE

  NI=SIZE(A)

  IF(NI.LT.3) THEN
    WRITE(*,*) 'SMOOTH: SIZE TOO SMALL'
    STOP
  ENDIF

  SMOOTH=0
  SMOOTH(1)=A(1)
  SMOOTH(NI-2:NI)= SMOOTH(NI-2:NI) +A(NI)*FAE

  DO I=2,NI-1
    F = (1+((NI-I)/(NI-1.0D0)))*0.5D0
    SMOOTH(I-1)= SMOOTH(I-1)+A(I)*(1-F)/2
    SMOOTH(I  )= SMOOTH(I  )+A(I)*F
    SMOOTH(I+1)= SMOOTH(I+1)+A(I)*(1-F)/2
  ENDDO

  RETURN
  END FUNCTION SMOOTH
!=======================================================================
  FUNCTION DDC(R)
!=======================================================================
! [USAGE]: 
! SMOOTHING A SEQUENCE A BY CONVOLUTION
! [INPUTS]:
! A >> A SEQUENCE CONTAINING NOISES
! [OUTPUTS]:
! SMOOTH >> SMOOTHENED SEQUENCE USING CONVOLUTION
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
  REAL(P8),DIMENSION(:):: R
  REAL(P8),DIMENSION(SIZE(R),3):: DDC
  REAL(P8):: X0,X1,X2
  INTEGER:: NI,I
  NI = SIZE(R)
  DDC(1,:)=0
  DDC(NI,:)=0
  DO I=2,NI-1
  X0=R(I-1)
  X1=R(I  )
  X2=R(I+1)
  DDC(I,1) = 2/(X0-X1)/(X0-X2)
  DDC(I,2) = 2/(X1-X0)/(X1-X2)
  DDC(I,3) = 2/(X2-X0)/(X2-X1)
  ENDDO

  RETURN
  END FUNCTION DDC
! ======================================================================

END MODULE MOD_MARCH
