!=======================================================================
! MODULE: MOD_INIT
!=======================================================================
!
!> @author Jinge Wang
!> @brief This module handles the initialization of the simulation.
!> It reads the input parameters and initializes the environment.
!=======================================================================
!
! DEPENDENCIES:
!
!-----------------------------------------------------------------------
! Standard Libraries:
!-----------------------------------------------------------------------
! - OMP_LIB: OpenMP library for parallel processing.
! - MPI: Message Passing Interface for distributed memory parallelism.
!-----------------------------------------------------------------------
! Project-Specific Modules:
!-----------------------------------------------------------------------
! - MOD_MISC:
!   - P4, P8, PI, IU, SPY, MSAVE, MLOAD, ATOF, ITOA3, PRINT_REAL_TIME
! - MOD_SCALAR3:
!   - NR, NTH, NX, NRCHOP, NTCHOP, NXCHOP, ZLEN, ZLEN0, ELL, MKLINK,
!     MINC
! - MOD_LEGOPS:
!   - NADD (derived type)
! - MOD_LAYOUT:
!   - QPAIR (derived type)
! - MOD_BOUSSINESQ:
!   - BSNSQ (derived type)
! - MOD_MARCH:
!   - DIAGV, ADV, RMV, VISC, TIM, FILES, LIN, VELMON, MONITORDATA,
!     POSTPROCESS (derived types)
! - MOD_DIAGNOSTICS:
!   - MONITORDATA%MK (array)
!=======================================================================
MODULE MOD_INIT ! LEVEL 6 MODULE
USE OMP_LIB
USE MPI
USE MOD_MISC                                                       ! LEVEL 0
USE MOD_SCALAR3                                                    ! LEVEL 2
USE MOD_FFT                                                        ! LEVEL 2.5
USE MOD_LEGOPS                                                     ! LEVEL 3
USE MOD_LAYOUT                                                     ! LEVEL 3
USE MOD_BOUSSINESQ
USE MOD_MARCH                                                      ! LEVEL 4
USE MOD_DIAGNOSTICS                                                ! LEVEL 5
IMPLICIT NONE
PRIVATE
!=======================================================================
!============================ PARAMETERS ===============================
!=======================================================================
INTEGER:: LNUMBER = 0                                              ! USED IN READCOM
INTEGER:: IECHO = 0                                                ! USED IN READCOM
INTEGER:: IEXEC = 0                                                ! USED IN READCOM
INTEGER:: IESAV,IREAD                                              ! USED IN READCOM
!=======================================================================
!======================== PUBLIC DECLARATION ===========================
!=======================================================================
PUBLIC :: SETUP_ENVIRONMENT
! READ COMMANDS
PRIVATE :: READCOM
! SHIFT THE CONTENTS OF AN INPUT ARRAY BY OPEN
PRIVATE :: SHIFTCOM
! READ INITIAL VALS FROM KEYBOARD OR INPUT FILE (ENTER %FILENAME)
PRIVATE :: READIN
! SYNC READIN INFO FROM MASTER MODE
PRIVATE :: READ_SYNC
! SAVE THE INPUTS USED
PUBLIC :: SAVEDIN
!=======================================================================
!============================ INTERFACES ===============================
!=======================================================================
INTERFACE READCOM
  MODULE PROCEDURE READCOM0
  MODULE PROCEDURE READCOM1
  MODULE PROCEDURE ECHO
END INTERFACE

INTERFACE READIN
  MODULE PROCEDURE READIN0
END INTERFACE 
CONTAINS
!=======================================================================
!============================ SUBROUTINES ==============================
!=======================================================================
SUBROUTINE SETUP_ENVIRONMENT(ECHO_MODE)
!=======================================================================
! [USAGE]:
! SETS UP THE EXECUTION ENVIRONMENT.
! [PARAMETERS]:
! ECHO_MODE >> (OPTIONAL) ECHO MODE ('ECHO' OR 'NOECHO')
!=======================================================================
IMPLICIT NONE
CHARACTER(LEN=*),OPTIONAL:: ECHO_MODE

CALL MPI_INIT_THREAD(MPI_THREAD_SERIALIZED,MPI_THREAD_MODE,IERR)
IF (MPI_THREAD_MODE.LT.MPI_THREAD_SERIALIZED) THEN
   WRITE(*,*) 'The threading support is lesser than that demanded.'
   CALL MPI_ABORT(MPI_COMM_WORLD,1,IERR)
ENDIF
CALL MPI_COMM_RANK(MPI_COMM_WORLD, MPI_RANK, IERR)

IF (MPI_RANK .EQ. 0) THEN
  WRITE(*,*) 'PARALLEL PROGRAM STARTED'
  CALL PRINT_REAL_TIME()
ENDIF

IF (PRESENT(ECHO_MODE)) THEN
  CALL READCOM(ECHO_MODE)
ELSE
  CALL READCOM('NOECHO')
ENDIF

CALL READIN(5)
IF (MPI_RANK .EQ. 0) THEN
  WRITE(*,*) 'PARAMETERS READ COMPLETED'
  CALL SAVEDIN()
ENDIF

RETURN
END SUBROUTINE SETUP_ENVIRONMENT
!=======================================================================
SUBROUTINE ECHO(C) ! FAMILY OF READCOM
!=======================================================================
! [USAGE]: 
! TOGGLES THE ECHO MODE (ON/OFF).
! [PARAMETERS]:
! C >> (OPTIONAL) 'ECHO' TO TURN ON THE ECHO MODE
!      IF BLANK, TOGGLES THE MODE BETWEEN ON AND OFF 
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
CHARACTER(LEN=*),OPTIONAL:: C

IF(PRESENT(C)) THEN
  IF((C .EQ. 'echo') .OR. (C .EQ. 'ECHO')) THEN 
    IECHO = 1
  ELSE
    IECHO = 0
  ENDIF
ELSE
  IECHO = 1-IECHO
ENDIF

RETURN
END SUBROUTINE ECHO
!=======================================================================
SUBROUTINE READCOM0(I) ! FAMILY OF READCOM
!=======================================================================
! [USAGE]: 
! RESET THE LINE NUMBER TO READ TO I
! [PARAMETERS]:
! I >> RESET LINE NUMBER
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 20 2020
!=======================================================================
INTEGER :: I

LNUMBER = I

RETURN
END SUBROUTINE READCOM0
!=======================================================================
SUBROUTINE READCOM1(IR,CMD,LNO) ! FAMILY OF REACOM
!=======================================================================
! [USAGE]: 
! READ COMMANDS FROM UNIT IR
! [PARAMETERS]:
! IR >> UNIT NUMBER
! CMD >> COMMAND STRINGS
! LNO >> (OPTIONAL) ON EXIT, RETURNS THE CURRENT LINE NUMBER
! [NOTES]:
! READCOM(IR,COM) READS COMMANDS FROM UNIT IR.  IR=5 MEANS KEYBOARD.
!               IR: INTEGER, COM(:): CHARACTERS.
!               IF THE LINE READ FROM IR IS
!
!                    A 'B CD' E,F 
!
!                THEN THE RESULT IS
!
!                COM(1) = 'A'
!                COM(2) = 'B CD'
!                COM(3) = 'E'
!                COM(4) = 'F'
!                COM(5) = ' ' ...
!
!                - IF THE LINE BEGINS WITH '#', THEN THE LINE IS SKIPPED.
!                - IF THE LINE IS, FOR EXAMPLE, '%AUTO', THEN 
!                  THE CONTENT OF FILE AUTO IS READ AS IF IT IS INPUT FROM 
!                  UNIT IR. THIS FACILITY CAN'T BE NESTED.
!                - A LINE WHICH BEGINS WITH '!' IS A SHELL ESCAPE.
!
! READCOM(IR,COM,LNUMBER), WHERE INTEGER LNUMBER, RETURNS THE CURRENT LINE
!                  NUMBER.
!
! READCOM(I)     RESETS THE LINE NUMBER TO I.
!
! READCOM('ECHO')    SETS THE ECHO MODE ON.
! READCOM('NOECHO')  RESETS THE ECHO MODE ON.
! CALL READCOM       TOGGLES THE ECHO MODE.
!
! READING FORMAT  
!  (2)COMMAND [LNO] / COMMENT
!    CHARACTERS (',) ARE REPLACED WITH A SPACE BEFORE ANY ANALYZING
! [UPDATES]:
! PROC#0 WILL TAKE KEYBOARD INPUT AND BROADCAST IT TO ALL PROCS
!=======================================================================
IMPLICIT NONE
EXTERNAL UNIXCOM, TABTOSP
INTEGER :: IR
CHARACTER(LEN=*),DIMENSION(:):: CMD
INTEGER,OPTIONAL:: LNO

INTEGER,PARAMETER:: NLEN=200!200
CHARACTER(LEN=NLEN):: C
LOGICAL:: OPEN
INTEGER:: I,III,N,NDIM

CALL MPI_COMM_RANK(MPI_COMM_WORLD, MPI_RANK, IERR)

NDIM = SIZE(CMD,1)

DO  I=1,NDIM
  CMD(I)=' '
ENDDO

! COMMENT OUT THIS IF STATEMENT TO ALLOW KEYBOARD PROMPT
IF(IEXEC.EQ.0) THEN
  IREAD = 18
  DO 
    INQUIRE(UNIT=IREAD,OPENED=OPEN)
    IF(.NOT.OPEN) EXIT
    IREAD=IREAD+1
  ENDDO
  OPEN(UNIT=IREAD,FILE='read.input',STATUS='OLD')
  IEXEC=1
  IESAV=IECHO
  IECHO=0
ENDIF

1    CONTINUE

IF(IEXEC.NE.1) THEN
  IF (MPI_RANK.EQ.0) THEN
    WRITE(6,*) 'START READIN'
    READ(IR,10) C ! Read input
  ENDIF
  CALL MPI_BCAST(C,NLEN,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR) ! MUST BE MUTED IF USING READ_SYNC
  
ELSE
  READ(IREAD,10,ERR=9) C
  IF(C.EQ.'%END') GOTO 9 ! Reach the end
  GOTO 19 ! Move to next line

9    CONTINUE

  CLOSE(IREAD)
  IEXEC=0
  IECHO=IESAV
  GOTO 1
ENDIF

IF(C(1:1).EQ.'%') THEN ! read filename
  IREAD=18
  DO
    INQUIRE(UNIT=IREAD,OPENED=OPEN)
    IF(.NOT.OPEN) EXIT
    IREAD=IREAD+1
  ENDDO

  OPEN(UNIT=IREAD,FILE=C(2:NLEN),STATUS='OLD',ACTION='READ')
  IEXEC=1
  IESAV=IECHO
  ! IECHO=1
  IF (MPI_RANK.EQ.0) THEN
    IECHO=1
  ELSE
    IECHO=0
  ENDIF
  GOTO 1
ENDIF

19   CONTINUE

LNUMBER=LNUMBER + 1

IF(IECHO.EQ.1) THEN
  I=201

11   CONTINUE

  I=I-1
  IF((C(I:I).EQ.' '.OR.C(I:I).EQ.'\0').AND.I.GT.1) GOTO 11
  WRITE(*,*) C(1:I)
ENDIF

10   FORMAT(A200)

IF(C(1:1).EQ.'#') THEN
  GOTO 1
ENDIF

IF(C(1:1).EQ.'!') THEN
  CALL EXECUTE_COMMAND_LINE(C(2:72))
  GOTO 1
ENDIF

3    CONTINUE

III=INDEX(C,',')

IF(III.NE.0) THEN
  C=C(1:III-1)//' '//C(III+1:NLEN)
  GOTO 3
ENDIF

5    CONTINUE

III=INDEX(C,CHAR(9))

IF(III.NE.0) THEN
  C=C(1:III-1)//' '//C(III+1:NLEN)
  GOTO 5
ENDIF

N = 1

2    CONTINUE

IF(C.NE.' ') THEN
  IF(C(1:1).EQ.' '.OR.C(1:1).EQ.',') THEN
    C=C(2:NLEN)
    GOTO 2
  ENDIF
ENDIF

IF(C(1:1).EQ.'"') THEN
  C=C(2:NLEN)
  CMD(N)=C(1:INDEX(C,'"')-1)
  C=C(INDEX(C,'"')+1:NLEN)
ELSEIF(C(1:1).EQ.'''') THEN
  C=C(2:NLEN)
  CMD(N)=C(1:INDEX(C,'''')-1)
  C=C(INDEX(C,'''')+1:NLEN)
ELSEIF(C(1:1).EQ.'(') THEN
  C=C(2:NLEN)
  CMD(N)=C(1:INDEX(C,')')-1)
  C=C(INDEX(C,')')+1:NLEN)
ELSE
  CMD(N)=C(1:INDEX(C,' '))
  C=C(INDEX(C,' ')+1:NLEN)
ENDIF

N=N+1

IF(N.GT.NDIM) THEN
  WRITE(*,*) 'READCOM: TOO MANY FIELDS'
  WRITE(*,*) 'UNPROCESSED FIELD=',C
  GOTO 999
ENDIF

IF(C.NE.' ') GOTO 2

999  CONTINUE

IF(PRESENT(LNO)) THEN
  LNO=LNUMBER
ENDIF

RETURN
END SUBROUTINE READCOM1
!=======================================================================
SUBROUTINE SHIFTCOM(COM)
!=======================================================================
! [USAGE]:
! SHIFTS THE CONTENTS OF ARRAY BY ONE. THE COM(1) IS 
! REPLACED BY COM(2), COM(2) BY COM(3) AND SO ON. 
! THE LAST ELEMENT IS FILLED BY ' '.
! [PARAMETERS]:
! CMD >> COMMAND STRINGS
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 10 2020
!======================================================================= 
IMPLICIT NONE
CHARACTER(LEN=*),DIMENSION(:)::  COM

INTEGER :: I,NDIM

NDIM=SIZE(COM,1)

DO I=1,NDIM-1
  COM(I)=COM(I+1)
ENDDO

COM(NDIM)=' '

RETURN
END SUBROUTINE SHIFTCOM
!======================================================================= 
SUBROUTINE READIN0(IR)
!=======================================================================
! [USAGE]:
! READ COMMANDS AND ASSIGN INITIAL VALUES INTO THE VARIABLES
! [PARAMETERS]:
! IR >> IF 5, READ COMMAND FROM KEYBOARD
!       IF 5 AND ENTER '%FILENAME', START READING COMMANDS FROM FILE
! [DEPENDENCIES]:
! 1. READCOM(~) @ MOD_INIT
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 10 2020
!======================================================================= 
IMPLICIT NONE
INTEGER,INTENT(IN):: IR

CHARACTER(LEN=72),DIMENSION(20):: COM
INTEGER :: NRIN, NTHIN, NXIN, I, NUM
INTEGER :: NRCHOPIN, NTCHOPIN, NXCHOPIN
REAL(P8):: ZLENIN,ELLIN

INTEGER :: MINCIN = 1
INTEGER :: MKLINKIN = 0
INTEGER :: IDEBUG = 0
INTEGER :: CHECKER = 0

!INTEGER :: LNUMBER = 0 !Initilization
LNUMBER = 0

! mod_march:
DIAGV%IT1=40
DIAGV%IT2=40

ADV%SW = 0
ADV%INT = 10000
ADV%UX = 0
ADV%UY = 0
ADV%UZ = 0

NADD%ANG = 0
NADD%U = 0
NADD%UZ = 0
NADD%STRAIN=0

RMV%SW=0
RMV%INT=10000

VISC%ADJSW=0
! end mod_march

CALL READCOM(LNUMBER)
! WRITE(6,*) 'START READIN'
DO WHILE (CHECKER .LT. 1000)
  CHECKER = CHECKER + 1
  CALL READCOM(IR,COM,LNUMBER)
  IF(IDEBUG.EQ.1) WRITE(*,'(6A16)') 'DEBUG MODE: ',(COM(I),I=1,5)

  ! 1> SCALAR3 - DIMENSIONS
  IF(COM(1).EQ.'DIMENSION') THEN
    CALL READCOM(IR,COM)
    NRIN = ATOF(COM(1)) 
    NTHIN= ATOF(COM(2))
    NXIN = ATOF(COM(3))
  ELSEIF(COM(1).EQ.'CHOPS') THEN
    CALL READCOM(IR,COM)
    NRCHOPIN = ATOF(COM(1)) 
    NTCHOPIN = ATOF(COM(2)) 
    NXCHOPIN = ATOF(COM(3))
  ELSEIF(COM(1).EQ.'ELL') THEN
    CALL READCOM(IR,COM)
    ELLIN = ATOF(COM(1))
    ELL = ELLIN
  ELSEIF(COM(1).EQ.'ZLEN') THEN
    CALL READCOM(IR,COM)
    IF (ATOF(COM(1)).GT.1.) THEN
      ZLENIN = ATOF(COM(1))
    ELSE ! If ZLENIN <= 1, assumes it's the wavenumber
      ZLENIN = 2.*PI/ATOF(COM(1))
    ENDIF
  ELSEIF(COM(1).EQ.'MINC') THEN
    CALL READCOM(IR,COM)
    MINCIN = ATOF(COM(1))
  ELSEIF(COM(1).EQ.'MKLINK') THEN
    CALL READCOM(IR,COM)
    MKLINKIN = ATOF(COM(1))

  ! 2> LAYOUT - VORTEX PAIR(QPAIR)
  ELSEIF(COM(1).EQ.'VORTEXPAIR') THEN
    CALL READCOM(IR,COM)
    QPAIR%N = ATOF(COM(1))
    DO I=1,QPAIR%N
      CALL READCOM(IR,COM)
      QPAIR%X(I) = ATOF(COM(1))
      QPAIR%Y(I) = ATOF(COM(2))
      QPAIR%Q(I) = ATOF(COM(3))
      QPAIR%H(I) = ATOF(COM(4))
      QPAIR%B(I) = ATOF(COM(5))
    ENDDO
    QPAIR%NOISE = 0
    QPAIR%DX = 0
    QPAIR%DY = 0
    QPAIR%DP = 0
    QPAIR%K  = 1
    QPAIR%R  = 1
    QPAIR%DR = 0
    QPAIR%RP = 0
    QPAIR%RK = 0
  ELSEIF(COM(1).EQ.'VORTEXPAIR_NOISE') THEN
    CALL READCOM(IR,COM)
    QPAIR%NOISE=ATOF(COM(1))
  ELSEIF(COM(1).EQ.'VORTEXPAIR_CROW') THEN
    DO I=1,QPAIR%N
      CALL READCOM(IR,COM)
      QPAIR%DX(I)=ATOF(COM(1))
      QPAIR%DY(I)=ATOF(COM(2))
      QPAIR%DP(I)=ATOF(COM(3))
      QPAIR%K(I) =ATOF(COM(4))
    ENDDO
  ELSEIF(COM(1).EQ.'VORTEXPAIR_SECTION') THEN
    DO I=1,QPAIR%N
      CALL READCOM(IR,COM)
      QPAIR%R(I) =ATOF(COM(1))
      QPAIR%DR(I)=ATOF(COM(2))
      QPAIR%RP(I)=ATOF(COM(3))
      QPAIR%RK(I)=ATOF(COM(4))
    ENDDO

  ! 3> MARCH - TIME DATA
  ELSEIF(COM(1).EQ.'DT') THEN
    CALL READCOM(IR,COM)
    TIM%DT   =ATOF(COM(1))
    TIM%LIMIT=ATOF(COM(2))
    TIM%N    = 0
    TIM%T    = 0
  ELSEIF(COM(1).EQ.'TIME_INTEG') THEN
    CALL READCOM(IR,COM)
    TIM%SCHEME = ATOF(COM(1))

  ! 4> MARCH - VISCOSITY DATA
  ELSEIF(COM(1).EQ.'VISCOSITY') THEN
    CALL READCOM(IR,COM)
    VISC%SW  = ATOF(COM(1))
    VISC%NU  = ATOF(COM(2))
    IF (VISC%NU .GE. 1.D0) THEN
      VISC%NU = VISC%NU**(-1.D0)
    ENDIF
    VISC%NUP = ATOF(COM(3))
    IF (VISC%NUP .GE. 1.D0) THEN
      VISC%NUP = VISC%NUP**(-1.D0)
    ENDIF
    VISC%P   = ATOF(COM(4))
  ELSEIF(COM(1).EQ.'NUP_ADJUST') THEN
    CALL READCOM(IR,COM)
    VISC%ADJSW  = ATOF(COM(1))
    VISC%ADJINT = ATOF(COM(2))

  ! 4> MARCH - BOUSSINESQ DATA
  ELSEIF(COM(1).EQ.'BOUSSINESQ') THEN
    CALL READCOM(IR,COM)
    BSNSQ%BV0 = ATOF(COM(1))
    BSNSQ%OMEGA = ATOF(COM(2))
    BSNSQ%KAPPA = ATOF(COM(3))
    BSNSQ%KAPPAP = ATOF(COM(4))
    BSNSQ%ADAMS = ATOF(COM(5)) > 0

  ! 4> MARCH - FREESTREAM DATA & LEGOPS - NONLINADD
  ELSEIF(COM(1).EQ.'FREESTREAM') THEN
    CALL READCOM(IR,COM)
    ADV%SW = ATOF(COM(1))
    ADV%UX = ATOF(COM(2))
    ADV%UY = ATOF(COM(3))
    ADV%UZ = ATOF(COM(4))
    ADV%INT = ATOF(COM(5))
    NADD%U = SQRT(ADV%UX**2+ADV%UY**2)
    NADD%UZ= ADV%UZ
    IF(NADD%U.EQ.0.0) THEN
      NADD%ANG = 0.0
    ELSEIF(ADV%UY >= 0) THEN
      NADD%ANG = ACOS(ADV%UX/NADD%U)
    ELSE 
      NADD%ANG = -1.0*ACOS(ADV%UX/NADD%U)
    ENDIF
  ELSEIF(COM(1).EQ.'STRAIN') THEN
    CALL READCOM(IR,COM)
    NADD%STRAIN = ATOF(COM(1))

  ! 5> MARCH - REMOVAL (RMV)
  ELSEIF(COM(1).EQ.'REMOVE') THEN
    CALL READCOM(IR,COM)
    RMV%SW = ATOF(COM(1))
    RMV%INT = ATOF(COM(2))

  !6> MARCH - FILE INOUT
  ELSEIF(COM(1).EQ.'SAVEDIR') THEN
    CALL READCOM(IR,COM)
    FILES%SAVEDIR=COM(1)
  ELSEIF(COM(1).EQ.'PSI0') THEN
    CALL READCOM(IR,COM)
    FILES%PSI0=COM(1)
  ELSEIF(COM(1).EQ.'CHI0') THEN
    CALL READCOM(IR,COM)
    FILES%CHI0=COM(1)
  ELSEIF(COM(1).EQ.'B0') THEN
    CALL READCOM(IR,COM)
    FILES%B0=COM(1)
  ELSEIF(COM(1).EQ.'PSII') THEN
    CALL READCOM(IR,COM)
    FILES%PSII=COM(1)
  ELSEIF(COM(1).EQ.'CHII') THEN
    CALL READCOM(IR,COM)
    FILES%CHII=COM(1)
  ELSEIF(COM(1).EQ.'BI') THEN
    CALL READCOM(IR,COM)
    FILES%BI=COM(1)
  ELSEIF(COM(1).EQ.'OUTPUTS') THEN
    CALL READCOM(IR,COM)
    FILES%NE = ATOF(COM(1))
    ALLOCATE( FILES%T(FILES%NE) )
    ALLOCATE( FILES%PSI(FILES%NE) )
    ALLOCATE( FILES%CHI(FILES%NE) )
    ALLOCATE( FILES%B(FILES%NE) )
    DO I=1,FILES%NE
      CALL READCOM(IR,COM)
      FILES%T(I)   = ATOF(COM(1))
      FILES%PSI(I) = COM(2)
      FILES%CHI(I) = COM(3)
      IF (SIZE(COM,1) > 3) THEN
        FILES%B(I) = COM(4)
      ELSE
        FILES%B(I) = ' '
      ENDIF
    ENDDO

  !7> MARCH - DIAGNOST & VELMON
  ELSEIF(COM(1).EQ.'DIAGNOST') THEN
    CALL READCOM(IR,COM)
    DIAGV%IT1  = ATOF(COM(1))
    DIAGV%IT2  = ATOF(COM(2))
    VELMON%INT = DIAGV%IT1
    VELMON%N   = 0

  !8> MARCH - LINEAR
  ELSEIF(COM(1).EQ.'LINEAR') THEN
    CALL READCOM(IR,COM)
    LIN%MM=ATOF(COM(1))
    LIN%KK=ATOF(COM(2))

  !9> MARCH - EIGENVALUE MONITOR KIT & DIAGNOSTICS - MONITOR_MK
  ELSEIF(COM(1).EQ.'MONITOR_MK') THEN
    CALL READCOM(IR,COM)
    NUM = ATOF(COM(1))
    ALLOCATE(MONITORDATA%MK(NUM,2))
    DO I=1,NUM
      CALL READCOM(IR,COM)
      MONITORDATA%MK(I,1) = ATOF(COM(1))
      MONITORDATA%MK(I,2) = ATOF(COM(2))
    ENDDO
    CALL READCOM(IR,COM)
    MONITORDATA%START = ATOF(COM(1))
    MONITORDATA%INTERVAL = ATOF(COM(2))

  !10> MARCH - POSTPROCESS KIT
  ELSEIF(COM(1).EQ.'POSTPROCESS') THEN
    CALL READCOM(IR,COM)
    NUM = ATOF(COM(1))
    ALLOCATE(POSTPROCESS%START(NUM), POSTPROCESS%FINISH(NUM), &
             POSTPROCESS%JOB(NUM), POSTPROCESS%SLICEINT(NUM))
    DO I=1,NUM
      CALL READCOM(IR,COM)
      POSTPROCESS%START(I)  = ATOF(COM(1))
      POSTPROCESS%FINISH(I)  = ATOF(COM(2))
      POSTPROCESS%JOB(I)     = ATOF(COM(3))
      POSTPROCESS%SLICEINT(I)= ATOF(COM(4))
    ENDDO 

  !11> MISCELLANOUS
  ELSEIF(COM(1).EQ.'DEBUG') THEN
    CALL READCOM(IR,COM)
    IDEBUG = ATOF(COM(1))
  ELSEIF(COM(1).EQ.' ') THEN
    CONTINUE
  ELSEIF(COM(1).EQ.'END') THEN
    EXIT
  ELSE 
    WRITE(*,*) 'READIN: UNKNOWN COMMAND IN LINE ',LNUMBER
  ENDIF
ENDDO       

IF (CHECKER .GE. 1000) THEN
  WRITE(*,*) 'READIN: COMMAND TOO LONG (MAX. OF 1000 LINES' //&
              ' EXPECTED)'
  STOP
ENDIF

NR = NRIN
NTH = NTHIN
NX = NXIN
NRCHOP = NRCHOPIN
NTCHOP = NTCHOPIN
NXCHOP = NXCHOPIN
ZLEN = ZLENIN
ZLEN0 = ZLEN
ELL = ELLIN
MKLINK = MKLINKIN
MINC = MINCIN

IF(LIN%KK.LT.0) LIN%KK = 2*NXCHOP+LIN%KK

RETURN
END SUBROUTINE READIN0
!======================================================================= 
SUBROUTINE READ_SYNC()
!=======================================================================
! [USAGE]:
! SYNC ALL READIN INFO THROUGH ALL PROCESSORS. MUST MUTE MPI_BCAST IN RE
! ADCOM
!======================================================================= 
IMPLICIT NONE

INTEGER :: NUM, I

INTEGER :: MINCIN = 1
INTEGER :: MKLINKIN = 0
INTEGER :: IDEBUG = 0
INTEGER :: CHECKER = 0

CALL MPI_COMM_RANK(MPI_COMM_WORLD, MPI_RANK, IERR)
! IF (MPI_RANK.NE.0) THEN
!   WRITE(*,*) 'NOT IN MASTER PROC. ABORTED'
!   RETURN
! ENDIF

CALL MPI_BCAST(NR,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(NTH,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(NX,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(NRCHOP,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(NTCHOP,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(NXCHOP,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(ELL,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(ZLEN,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(MINC,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(MKLINK,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(QPAIR%N,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(QPAIR%NOISE,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
DO I=1,QPAIR%N
  CALL MPI_BCAST(QPAIR%X(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%Y(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%Q(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%H(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%B(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%DX(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%DY(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%DP(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%K(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%R(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%DR(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%RK(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(QPAIR%RP(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
ENDDO

CALL MPI_BCAST(TIM%DT,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(TIM%LIMIT,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(TIM%N,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(TIM%T,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(TIM%SCHEME,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(VISC%SW,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(VISC%NU,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(VISC%NUP,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(VISC%P,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(VISC%ADJSW,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(VISC%ADJINT,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(ADV%SW,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(ADV%UX,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(ADV%UY,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(ADV%UZ,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(ADV%INT,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(NADD%U,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(NADD%UZ,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(NADD%ANG,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(NADD%STRAIN,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(RMV%SW,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(RMV%INT,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(FILES%SAVEDIR,72,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(FILES%PSI0,72,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(FILES%CHI0,72,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(FILES%PSII,72,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(FILES%CHII,72,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(FILES%NE,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
IF (MPI_RANK.NE.0) THEN
ALLOCATE( FILES%T(FILES%NE) )
ALLOCATE( FILES%PSI(FILES%NE) )
ALLOCATE( FILES%CHI(FILES%NE) )
ENDIF
DO I=1,FILES%NE
  CALL MPI_BCAST(FILES%T(I),1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(FILES%PSI(I),72,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(FILES%CHI(I),72,MPI_CHARACTER,0,MPI_COMM_WORLD,IERR)
ENDDO

CALL MPI_BCAST(DIAGV%IT1,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(DIAGV%IT2,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(VELMON%INT,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(VELMON%N,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(LIN%MM,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(LIN%KK,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

CALL MPI_BCAST(DIAGV%IT1,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

IF (MPI_RANK.EQ.0) THEN
  NUM = SIZE(MONITORDATA%MK,1)
ENDIF
CALL MPI_BCAST(NUM,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
IF (MPI_RANK.NE.0) ALLOCATE(MONITORDATA%MK(NUM,2))
DO I=1,NUM
  CALL MPI_BCAST(MONITORDATA%MK(I,1),1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(MONITORDATA%MK(I,2),1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
ENDDO

CALL MPI_BCAST(MONITORDATA%START,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
CALL MPI_BCAST(MONITORDATA%INTERVAL,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)

IF (MPI_RANK.EQ.0) THEN
  NUM = SIZE(POSTPROCESS%START)
ENDIF
CALL MPI_BCAST(NUM,1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
IF (MPI_RANK.NE.0) THEN
  ALLOCATE(POSTPROCESS%START(NUM), POSTPROCESS%FINISH(NUM), &
           POSTPROCESS%JOB(NUM), POSTPROCESS%SLICEINT(NUM))
ENDIF
DO I=1,NUM
  CALL MPI_BCAST(POSTPROCESS%START(I),1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(POSTPROCESS%FINISH(I),1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(POSTPROCESS%JOB(I),1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
  CALL MPI_BCAST(POSTPROCESS%SLICEINT(I),1,MPI_INTEGER,0,MPI_COMM_WORLD,IERR)
ENDDO

RETURN
END SUBROUTINE READ_SYNC
!=======================================================================

SUBROUTINE SAVEDIN(OUTFILE)
!=======================================================================
! [USAGE]:
! SAVE CURRENT PARAMETERS TO AN OUTPUT FILE IN THE SAME FORMAT AS read.input
! [PARAMETERS]:
! OUTFILE >> NAME OF THE OUTPUT FILE (DEFAULT: 'params_used.input')
! [DEPENDENCIES]:
! NONE - Uses parameters that were loaded by READIN0
! [UPDATES]:
! CODED BY JINGE WANG @ JULY 25 2025
!=======================================================================
IMPLICIT NONE
CHARACTER(LEN=*),INTENT(IN),OPTIONAL:: OUTFILE
CHARACTER(LEN=100):: FILENAME
INTEGER:: FUNIT, I
LOGICAL:: IS_OPENED

! Set default filename if not provided
IF (PRESENT(OUTFILE)) THEN
  FILENAME = OUTFILE
ELSE
  FILENAME = TRIM(FILES%SAVEDIR)//'read.temp'
ENDIF

! Only rank 0 writes the file in MPI mode
IF (MPI_RANK /= 0) RETURN

! Find an available file unit
FUNIT = 30
DO
  INQUIRE(UNIT=FUNIT, OPENED=IS_OPENED)
  IF (.NOT. IS_OPENED) EXIT
  FUNIT = FUNIT + 1
ENDDO

! Open the output file
OPEN(UNIT=FUNIT, FILE=TRIM(FILENAME), STATUS='REPLACE')

! Write parameters in the same format as read.input
WRITE(FUNIT,'(A)') 'DIMENSION '
WRITE(FUNIT,'(A)') '#     NR     NTH      NX ----------------------------------(POWER OF 2)'
WRITE(FUNIT,'(3I8)') NR, NTH, NX
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'CHOPS'
WRITE(FUNIT,'(A)') '# NRCHOP  NTCHOP  NXCHOP --(NXCHOP<=NX/2 UNLESS NXCHOP=NX=1,NRCHOP<=NR)'
WRITE(FUNIT,'(3I8)') NRCHOP, NTCHOP, NXCHOP
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'ELL'
WRITE(FUNIT,'(A)') '#    ELL -----------------------------------------------(MAP PARAMETER)'
WRITE(FUNIT,'(F10.3)') ELL
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'ZLEN'
WRITE(FUNIT,'(A)') '#   ZLEN ------------------------(PERIOD LENGTH IN THE AXIAL DIRECTION)'
WRITE(FUNIT,'(F25.20)') ZLEN
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'MINC'
WRITE(FUNIT,'(A)') '#   MINC ----------(# OF SYMMETRY OCCURRING IN THE AXIMUTHAL DIRECTION)'
WRITE(FUNIT,'(I8)') MINC
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'MKLINK'
WRITE(FUNIT,'(A)') '# MKLINK --------(1 OR -1 IF M AND K ARE LINKED TOGETHER. DEFAULT IS 0)'
WRITE(FUNIT,'(I8)') MKLINK
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'VORTEXPAIR'
WRITE(FUNIT,'(A)') '#      N ------------------------------------------(NUMBER OF VORTICES)'
WRITE(FUNIT,'(I8)') QPAIR%N
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'
WRITE(FUNIT,'(A)') '#      X       Y       Q       H       B -(X, Y, Q, B AND H FOR VORTEX)'

DO I=1,QPAIR%N
  WRITE(FUNIT,'(5F8.3)') QPAIR%X(I), QPAIR%Y(I), QPAIR%Q(I), QPAIR%H(I), QPAIR%B(I)
ENDDO
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'VORTEXPAIR_NOISE'
WRITE(FUNIT,'(A)') '#  NOISE -----------------(1: RANDOM NOISE CREATED INTO INITIAL VORTEX)'
WRITE(FUNIT,'(I8)') QPAIR%NOISE
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

IF (ANY(QPAIR%DX /= 0.0_P8) .OR. ANY(QPAIR%DY /= 0.0_P8) .OR. &
    ANY(QPAIR%DP /= 0.0_P8) .OR. ANY(QPAIR%K /= 1.0_P8)) THEN
  WRITE(FUNIT,'(A)') 'VORTEXPAIR_CROW'
  WRITE(FUNIT,'(A)') '#     DX      DY      DP       K -(DELTAX, DELTAY, DELTAPHASE & WAVE #)'
  DO I=1,QPAIR%N
    WRITE(FUNIT,'(4F8.3)') QPAIR%DX(I), QPAIR%DY(I), QPAIR%DP(I), QPAIR%K(I)
  ENDDO
  WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'
ENDIF

IF (ANY(QPAIR%R /= 1.0_P8) .OR. ANY(QPAIR%DR /= 0.0_P8) .OR. &
    ANY(QPAIR%RP /= 0.0_P8) .OR. ANY(QPAIR%RK /= 1.0_P8)) THEN
  WRITE(FUNIT,'(A)') 'VORTEXPAIR_SECTION'
  WRITE(FUNIT,'(A)') '#      R      DR      RP      RK ---(CORER, DELTAR, DELTAPHASE & WAVE#)'
  DO I=1,QPAIR%N
    WRITE(FUNIT,'(4F8.3)') QPAIR%R(I), QPAIR%DR(I), QPAIR%RP(I), QPAIR%RK(I)
  ENDDO
ENDIF
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'DT'
WRITE(FUNIT,'(A)') '#     DT   LIMIT ------------------------------------(DELTAT & ENDTIME)'
WRITE(FUNIT,'(F9.6,F8.1)') TIM%DT, TIM%LIMIT
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'TIME_INTEG'
WRITE(FUNIT,'(A)') '# SCHEME -----------------(TIME ADVANCEMENT SCHEME !!CURRENTLY DUMMY!!)'
WRITE(FUNIT,'(I8)') TIM%SCHEME
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'VISCOSITY'
WRITE(FUNIT,'(A)') '#     SW       NU      NUP      P -(SWITCH, VISCOSITY, HYPERV, HELMPOW)'
WRITE(FUNIT,'(I8,2X,ES11.4,2X,ES11.4,2X,I6)') VISC%SW, VISC%NU, VISC%NUP, VISC%P
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'NUP_ADJUST'
WRITE(FUNIT,'(A)') '#  ADJSW  ADJINT -(HYPERV ADJUSTMENT SWITCH & FOR EVERY ''ADJINT'' STEPS)'
WRITE(FUNIT,'(2I8)') VISC%ADJSW, VISC%ADJINT
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'BOUSSINESQ'
WRITE(FUNIT,'(A)') '#     BV0    OMEGA    KAPPA   KAPPAP    ABSW ------(USE A-B FOR LINEAR)'
WRITE(FUNIT,'(2F9.3,2ES11.4,I8)') BSNSQ%BV0, BSNSQ%OMEGA, BSNSQ%KAPPA, BSNSQ%KAPPAP, &
                 MERGE(1, 0, BSNSQ%ADAMS)
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'FREESTREAM'
WRITE(FUNIT,'(A)') '#     SW      UX      UY      UZ     INT -(SWITCH, UX, UY, UZ, # STEPS)'
WRITE(FUNIT,'(I8,3F8.3,I8)') ADV%SW, ADV%UX, ADV%UY, ADV%UZ, ADV%INT
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'STRAIN'
WRITE(FUNIT,'(A)') '# STRAIN ---------------------------------------(NONLINEAR STRAIN TERM)'
WRITE(FUNIT,'(F8.3)') NADD%STRAIN
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'REMOVE'
WRITE(FUNIT,'(A)') '#     SW     INT -------(VORTEX REMOVAL SWITCH & FOR EVERY ''INT'' STEPS)'
WRITE(FUNIT,'(2I8)') RMV%SW, RMV%INT
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'SAVEDIR'
WRITE(FUNIT,'(A)') '#      DIRECTORY -------------(DIRECTOR WHERE ALL DAT FILES ARE STORED)'
WRITE(FUNIT,'(A)') '       '//TRIM(FILES%SAVEDIR)
WRITE(FUNIT,'(A)') 'PSI0'
WRITE(FUNIT,'(A)') '#         PSI0_F ---------(FILENAME WHERE PSI0 IS STORED, INITIAL DATA)'
WRITE(FUNIT,'(A)') '        '//TRIM(FILES%PSI0)
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'CHI0'
WRITE(FUNIT,'(A)') '#         CHI0_F ---------(FILENAME WHERE CHI0 IS STORED, INITIAL DATA)'
WRITE(FUNIT,'(A)') '        '//TRIM(FILES%CHI0)
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'B0'
WRITE(FUNIT,'(A)') '#           B0_F ---------(FILENAME WHERE   B0 IS STORED, INITIAL DATA)'
WRITE(FUNIT,'(A)') '          '//TRIM(FILES%B0)
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'PSII'
WRITE(FUNIT,'(A)') '#         PSII_F ---(FILENAME WHERE PSII IS STORED, POSTPROCESSED DATA)'
WRITE(FUNIT,'(A)') '        '//TRIM(FILES%PSII)
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'CHII'
WRITE(FUNIT,'(A)') '#         CHII_F ---(FILENAME WHERE CHII IS STORED, POSTPROCESSED DATA)'
WRITE(FUNIT,'(A)') '        '//TRIM(FILES%CHII)
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'BI'
WRITE(FUNIT,'(A)') '#           BI_F ---(FILENAME WHERE   BI IS STORED, POSTPROCESSED DATA)'
WRITE(FUNIT,'(A)') '          '//TRIM(FILES%BI)
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'OUTPUTS'
WRITE(FUNIT,'(A)') '#     NE --------------------------(NUMBER OF SNAPSHOTS OF PSI AND CHI)'
WRITE(FUNIT,'(I8)') FILES%NE
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'
WRITE(FUNIT,'(A)') '#      T         PSIX_F         CHIX_F         BX_F --(SNAPTIME, FILES)'
WRITE(FUNIT,'(A)') '# (NE LINES. THE LAST SNAPSHOT TIME DETERMINES THE PROGRAM TERMINATION)'

DO I=1,FILES%NE
  IF (TRIM(FILES%B(I)) /= '') THEN
    WRITE(FUNIT,'(F10.1,3A16)') FILES%T(I), TRIM(FILES%PSI(I)), TRIM(FILES%CHI(I)), TRIM(FILES%B(I))
  ELSE
    WRITE(FUNIT,'(F10.1,2A16)') FILES%T(I), TRIM(FILES%PSI(I)), TRIM(FILES%CHI(I))
  ENDIF
ENDDO
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'DIAGNOST'
WRITE(FUNIT,'(A)') '#    IT1     IT2 ----(PERFORM DIAGNOSIS FOR EVERY ''IT1'' OR ''IT2'' STEPS)'
WRITE(FUNIT,'(A)') '#                             (!! IT2 IS CURRENTLY A DUMMY VARIABLE !!)'
WRITE(FUNIT,'(2I8)') DIAGV%IT1, DIAGV%IT2
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

WRITE(FUNIT,'(A)') 'LINEAR'
WRITE(FUNIT,'(A)') '#     MM      KK ------------------(LINEAR TERMS !! CURRENTLY DUMMY !!)'
WRITE(FUNIT,'(2I8)') LIN%MM, LIN%KK
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

IF (ALLOCATED(MONITORDATA%MK)) THEN
  WRITE(FUNIT,'(A)') 'MONITORDATA%MK'
  WRITE(FUNIT,'(A)') '#    NUM --------------------------------- (NUMBER OF MONITORING MODES)'
  WRITE(FUNIT,'(I8)') SIZE(MONITORDATA%MK,1)
  WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'
  WRITE(FUNIT,'(A)') '#     MM      KK --------(AZIMUTHAL & AXIAL WAVENUMBER TO BE MONITORED)'
  WRITE(FUNIT,'(A)') '#     MM = 0,1,2,...; KK = 0,1,2,...;'
  
  DO I=1,SIZE(MONITORDATA%MK,1)
    WRITE(FUNIT,'(2I8)') INT(MONITORDATA%MK(I,1)), INT(MONITORDATA%MK(I,2))
  ENDDO
  WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'
  WRITE(FUNIT,'(A)') '#  START  INTERV -----(MONITORING START & MONITORING INTERVAL IN STEPS)'
  WRITE(FUNIT,'(F8.1,F8.1)') REAL(MONITORDATA%START), REAL(MONITORDATA%INTERVAL)
ENDIF
WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'

IF (ALLOCATED(POSTPROCESS%START)) THEN
  WRITE(FUNIT,'(A)') 'POSTPROCESS'
  WRITE(FUNIT,'(A)') '#    NUM --------------------------------- (NUMBER OF POSTPROCESS JOBS)'
  WRITE(FUNIT,'(I8)') SIZE(POSTPROCESS%START)
  WRITE(FUNIT,'(A)') '#  START  FINISH     JOB   SLICEI --(STARTINT,FINISHINT,JOBTYPE,SLICEI)'
  DO I=1,SIZE(POSTPROCESS%START)
    WRITE(FUNIT,'(4I8)') POSTPROCESS%START(I), POSTPROCESS%FINISH(I), POSTPROCESS%JOB(I), POSTPROCESS%SLICEINT(I)
  ENDDO
  WRITE(FUNIT,'(A)') '# ---------------------------------------------------------------------'
ENDIF

WRITE(FUNIT,'(A)') 'END'

! Close the file
CLOSE(FUNIT)

WRITE(*,*) 'Parameter file saved as: '//TRIM(FILENAME)

RETURN
END SUBROUTINE SAVEDIN
!======================================================================= 

END MODULE MOD_INIT
