MODULE MOD_BOUSSINESQ ! LEVEL 4 MODULE
  USE omp_lib
  USE MPI
  USE MOD_MISC, ONLY: P4,P8,PI,IU,MCAT,MSAVE                         ! LEVEL 0
  USE MOD_EIG                                                        ! LEVEL 1
  USE MOD_SCALAR3                                                    ! LEVEL 2
  USE MOD_FFT                                                        ! LEVEL 2.5
  USE MOD_LEGOPS                                                     ! LEVEL 3
  USE MOD_LAYOUT
  IMPLICIT NONE
  PRIVATE
!=======================================================================
!============================ PARAMETERS ===============================
!=======================================================================
!1> BOUSSINESQ DATA
PUBLIC:: BOUSS_DATA
TYPE BOUSS_DATA
  ! ASYMMETRIC BACKGROUND FLOW
  REAL(P8), ALLOCATABLE, DIMENSION(:) :: RUP0, OZ0
  REAL(P8), ALLOCATABLE, DIMENSION(:) :: SIGMA0 ! ONLY USED FOR ENERGY PRODUCTION
  ! ANGULAR VELOCITY OF THE ROTATING FRAME
  REAL(P8):: OMEGA
  ! UNPERTURBED BRUNT-VAISALA FREQUENCY (LINEAR STRATIFICATION)  
  REAL(P8):: BV0
  ! HYPERDIFFUSIVITY
  REAL(P8):: KAPPA, KAPPAP
  ! NUMERICAL METHOD FOR LINEAR TERMS
  LOGICAL :: ADAMS   ! = .TRUE.: USE ADAMS-BASHFORTH FOR THE LINEAR TERM

  CONTAINS 
    ! ONLY REQUIRE RUP0 AND OZ0:
    PROCEDURE, PASS(THIS):: ANGULAR_VELOCITY
    PROCEDURE, PASS(THIS):: RAYLEIGH_DISCRIMINANT
    PROCEDURE, PASS(THIS):: LOCAL_SHEAR
END TYPE
TYPE(BOUSS_DATA),PUBLIC,ALLOCATABLE:: BSNSQ   
!=======================================================================
!======================== PUBLIC DECLARATION ===========================
!=======================================================================
  ! TIME ADVANCEMENT SCHEMES RELATED
  PUBLIC:: CALC_BOUSSI_FORCE, CALC_BOUSSI_NONLIN
  ! ENERGY ANALYSIS: KE, PE, ENERGY-EXCHANGE
  PUBLIC:: CALC_BOUSSI_ENERGY, CALC_BOUSSI_PE, CALC_BOUSSI_PS
  ! LINEAR OPERATOR DIAGONALIZATION
  PUBLIC:: CALC_BOUSSI_DIAGH, CALC_BOUSSI_DIAGV, CALC_BOUSSI_BASEFLOW
  ! PUBLIC:: CALC_BOUSSI_DIAG (DISABLED)
! ======================================================================

CONTAINS
!=======================================================================
!============================ SUBROUTINES ==============================
!=======================================================================
FUNCTION ANGULAR_VELOCITY(this) RESULT(OMEGA0)
!=======================================================================
  IMPLICIT NONE
  CLASS(BOUSS_DATA), INTENT(IN) :: THIS
  REAL(P8), ALLOCATABLE, DIMENSION(:) :: OMEGA0

  ALLOCATE(OMEGA0(NR))
  OMEGA0 = THIS%RUP0(:NR)/TFM%R(:NR)**2

END FUNCTION ANGULAR_VELOCITY
!=======================================================================

FUNCTION RAYLEIGH_DISCRIMINANT(this) RESULT(RD)
!=======================================================================
  IMPLICIT NONE
  CLASS(BOUSS_DATA), INTENT(IN) :: THIS
  REAL(P8), ALLOCATABLE, DIMENSION(:) :: RD
  REAL(P8) :: OMEGA

  OMEGA = THIS%OMEGA

  ALLOCATE(RD(NR))
  RD = (2.0D0 * (OMEGA + THIS%ANGULAR_VELOCITY())) * &
       (2.0D0 * OMEGA + THIS%OZ0(:NR))

END FUNCTION RAYLEIGH_DISCRIMINANT
!=======================================================================

FUNCTION LOCAL_SHEAR(this, IS_REFACTORED) RESULT(SHEAR)
!=======================================================================
! [USAGE]:
! CALCULATE THE LOCAL SHEAR FROM THE BACKGROUND FLOW
! [PARAMETERS]:
! IS_REFACTORED (OPTIONAL) >> IF .TRUE., DIVIDE BY R^2*(1-X)^2
! SHEAR >> LOCAL SHEAR PROFILE
!=======================================================================

  IMPLICIT NONE
  CLASS(BOUSS_DATA), INTENT(IN) :: THIS
  LOGICAL, OPTIONAL :: IS_REFACTORED
  REAL(P8), ALLOCATABLE, DIMENSION(:) :: SHEAR

  ALLOCATE(SHEAR(NR))
  SHEAR = THIS%OZ0(:NR) - 2.0D0 * THIS%ANGULAR_VELOCITY()

  IF (PRESENT(IS_REFACTORED)) THEN
    IF (IS_REFACTORED) THEN
      ! R^2 = ELL2*(1+X)/(1-X)
      ! R^2*(1-X)^2 = ELL2*(1-X^2)
      SHEAR = SHEAR / (1.0D0-TFM%X(:NR)**2) / ELL2
    ENDIF
  ENDIF

END FUNCTION LOCAL_SHEAR
!=======================================================================

SUBROUTINE CALC_BOUSSI_BASEFLOW(SAVEDIR)
!=======================================================================
  IMPLICIT NONE
  CHARACTER(LEN=*), OPTIONAL :: SAVEDIR
  TYPE(SCALAR):: PSI0, CHI0, RUR0, RUP0, UZ0, ROR0, ROP0, OZ0
  REAL(P8):: OMEGA_BASE = 1.0D-8
  REAL(P8), ALLOCATABLE :: OMEGA0(:), RD(:), TEMP(:,:) ! TEMP USED FOR SAVING

  IF (ALLOCATED(BSNSQ%RUP0)) RETURN

  ALLOCATE(BSNSQ%RUP0(NDIMR), BSNSQ%OZ0(NDIMR), BSNSQ%SIGMA0(NDIMR))
  BSNSQ%RUP0 = 0.0D0
  BSNSQ%OZ0  = 0.0D0
  BSNSQ%SIGMA0 = 0.0D0

  ! OBTAIN PSI AND CHI FIELD FOR Q-VORTEX
  CALL QVORTEX(PSI0, CHI0)

  ! OBTAIN VELOCITY AND VORTICITY FIELDS
  CALL ALLOCATE(RUR0); CALL ALLOCATE(RUP0); CALL ALLOCATE(UZ0)
  CALL ALLOCATE(ROR0); CALL ALLOCATE(ROP0); CALL ALLOCATE(OZ0)
  CALL CHOPSET(3)
  CALL PC2VEL(PSI0, CHI0, RUR0, RUP0, UZ0)
  CALL PC2VOR(PSI0, CHI0, ROR0, ROP0, OZ0)
  CALL DEALLOCATE(PSI0); CALL DEALLOCATE(CHI0)
  CALL DEALLOCATE(RUR0); CALL DEALLOCATE(UZ0)
  CALL DEALLOCATE(ROR0); CALL DEALLOCATE(ROP0)
  CALL CHOPSET(-3)

  ! EXTRACT RUP0 AND OZ0
  CALL RTRAN(RUP0, 1); CALL RTRAN(OZ0, 1)
  IF ((RUP0%INTH.EQ.0).AND.(RUP0%INX.EQ.0)) THEN
    IF (MAXVAL(ABS(AIMAG(RUP0%E(:NR,1,1)))) .GT. 1.0D-14) THEN
      IF (MPI_RANK.EQ.0) THEN
        WRITE(*,*) 'CALC_BOUSSI_BASEFLOW: RUP0 HAS NON-ZERO IMAGINARY PART'
      ENDIF
      CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%BASEFLOW, IERR)
    ENDIF
    BSNSQ%RUP0(:NR) = REAL(RUP0%E(:NR,1,1))
    BSNSQ%OZ0(:NR)  = REAL(OZ0%E(:NR,1,1))
  ENDIF
  CALL DEALLOCATE(RUP0); CALL DEALLOCATE(OZ0)
  CALL MPI_ALLREDUCE(MPI_IN_PLACE, BSNSQ%RUP0, NDIMR, MPI_DOUBLE_PRECISION, &
       & MPI_SUM, MPI_COMM_IVP, IERR)
  CALL MPI_ALLREDUCE(MPI_IN_PLACE, BSNSQ%OZ0, NDIMR, MPI_DOUBLE_PRECISION, &
       & MPI_SUM, MPI_COMM_IVP, IERR)

  ! CALCULATE SIGMA0
  BSNSQ%SIGMA0(:NR) = BSNSQ%LOCAL_SHEAR(IS_REFACTORED=.TRUE.)

  ! REGULARIZE OMEGA IF ZERO, AND CALCULATE RAYLEIGH DISCRIMINANT
  ALLOCATE(OMEGA0(NR), RD(NR))
  OMEGA0 = BSNSQ%ANGULAR_VELOCITY()
  IF (BSNSQ%OMEGA .EQ. 0.D0) THEN ! ADD OMEGA_BASE TO AVOID SINGULARITY
    BSNSQ%OMEGA = SIGN(OMEGA_BASE, OMEGA0(MAXLOC(ABS(OMEGA0),DIM=1)))
  ENDIF
  RD = BSNSQ%RAYLEIGH_DISCRIMINANT()

  IF (PRESENT(SAVEDIR).AND.(MPI_RANK.EQ.0)) THEN
    ALLOCATE(TEMP(NR,5))
    TEMP(:,1) = TFM%R(:NR)
    TEMP(:,2) = BSNSQ%RUP0(:NR)/TFM%R(:NR)
    TEMP(:,3) = BSNSQ%OZ0(:NR)
    TEMP(:,4) = OMEGA0(:NR)
    TEMP(:,5) = RD(:NR)
    CALL MSAVE(TEMP, TRIM(ADJUSTL(SAVEDIR))//'baseflow.dat')
    DEALLOCATE(TEMP)
  ENDIF

  ! CHECK IF RAYLEIGH DISCRIMINANT IS POSITIVE EVERYWHERE
  IF (MINVAL(RD) .LE. 0.D0) THEN
    CALL MPRINT('CALC_BOUSSI_BASEFLOW: RAYLEIGH DISCRIMINANT IS NOT POSITIVE EVERYWHERE!')
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%BASEFLOW, IERR)
  ENDIF

  DEALLOCATE(OMEGA0, RD)
  RETURN
END SUBROUTINE CALC_BOUSSI_BASEFLOW
!=======================================================================

SUBROUTINE CALC_BOUSSI_DIAG(J,S,S_INV,ECHO)
!=======================================================================
! [USAGE]:
! CALCULATE THE DIAGONAL ELEMENTS OF THE BOUSSINESQ OPERATOR FOR
! CONSTANT BACKGROUND STRATIFICATION AND ROTATION
! [PARAMETERS]:
! J >> EIGENVALUE OF THE LINEAR BOUSSINESQ OPERATOR
! S >> RIGHT EIGENMATRIX
! S_INV >> LEFT EIGENMATRIX
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8), DIMENSION(4,4), INTENT(INOUT):: J, S, S_INV
  REAL(P8) :: N_FREQ, OMEGA
  LOGICAL, OPTIONAL :: ECHO

  N_FREQ = BSNSQ%BV0
  OMEGA  = BSNSQ%OMEGA

  IF (N_FREQ .EQ. 0.D0) THEN
    IF (MPI_RANK.EQ.0) THEN
      WRITE(*,*) 'CALC_BOUSSI_DIAG: N_FREQ = 0, CANNOT DIAGONALIZE'
    ENDIF
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SOLVER, IERR)
  ENDIF

  J = CMPLX(0.0D0, 0.0D0, P8)
  J(1,1) = -IU * N_FREQ
  J(2,2) =  IU * N_FREQ
  J(3,3) = -2.0D0 * IU * OMEGA
  J(4,4) =  2.0D0 * IU * OMEGA

  S = CMPLX(0.0D0, 0.0D0, P8)
  S(1,3) = IU
  S(1,4) = -IU
  S(2,3) = 1.0D0
  S(2,4) = 1.0D0
  S(3,1) = -IU / N_FREQ
  S(3,2) =  IU / N_FREQ
  S(4,1) = 1.0D0
  S(4,2) = 1.0D0

  S_INV = CMPLX(0.0D0, 0.0D0, P8)
  S_INV(1,3) =  IU * N_FREQ / 2.0D0
  S_INV(1,4) = 0.5D0
  S_INV(2,3) = -IU * N_FREQ / 2.0D0
  S_INV(2,4) = 0.5D0
  S_INV(3,1) = -IU / 2.0D0
  S_INV(3,2) = 0.5D0
  S_INV(4,1) =  IU / 2.0D0
  S_INV(4,2) = 0.5D0

  IF (PRESENT(ECHO)) THEN
    IF ((MPI_RANK.EQ.0).AND.(ECHO)) THEN
      WRITE(*,*) 'MOD_BOUSSINESQ: L = SJS^-1'
      WRITE(*,*) 'J:'
      CALL MCAT(J)
      WRITE(*,*) 'S:'
      CALL MCAT(S)
      WRITE(*,*) 'S^-1:'
      CALL MCAT(S_INV)
      WRITE(*,*) 'S*S^-1:'
      CALL MCAT(MATMUL(S, S_INV))
      WRITE(*,*) 'S*J*S^-1:'
      CALL MCAT(MATMUL(S, MATMUL(J, S_INV)))
    ENDIF
  ENDIF

  RETURN
END SUBROUTINE CALC_BOUSSI_DIAG
!=======================================================================

SUBROUTINE CALC_BOUSSI_DIAGV(J,S,S_INV,ECHO)
!=======================================================================
! [USAGE]:
! PERFORM THE DIAGONALIZATION OF THE LINEAR BOUSSINESQ OPERATOR FOR THE 
! AXISYMMETRIC (M=0) VERTICAL COMPONENTS UZ AND B.
! [PARAMETERS]:
! J >> EIGENVALUE
! S >> RIGHT EIGENMATRIX
! S_INV >> LEFT EIGENMATRIX
! [NOTES]:
! 1. ONLY FOR M=0 VERTICAL COMPONENTS
! 2. FOR NON-AXISYMMETRIC CASE, EIGENVALUES ARE DOPPLER SHIFTED
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8), DIMENSION(2,2), INTENT(INOUT):: J, S, S_INV
  REAL(P8) :: N_FREQ
  LOGICAL, OPTIONAL :: ECHO

  N_FREQ = BSNSQ%BV0

  IF (N_FREQ .EQ. 0.D0) THEN
    IF (MPI_RANK.EQ.0) THEN
      WRITE(*,*) 'CALC_BOUSSI_DIAG: N_FREQ = 0, CANNOT DIAGONALIZE'
    ENDIF
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SOLVER, IERR)
  ENDIF

  J = CMPLX(0.0D0, 0.0D0, P8)
  J(1,1) = -IU * N_FREQ
  J(2,2) =  IU * N_FREQ

  S = CMPLX(0.0D0, 0.0D0, P8)
  S(1,1) = -IU / N_FREQ
  S(1,2) =  IU / N_FREQ
  S(2,1) = 1.0D0
  S(2,2) = 1.0D0

  S_INV = CMPLX(0.0D0, 0.0D0, P8)
  S_INV(1,1) =  IU * N_FREQ / 2.0D0
  S_INV(1,2) = 0.5D0
  S_INV(2,1) = -IU * N_FREQ / 2.0D0
  S_INV(2,2) = 0.5D0

  IF (PRESENT(ECHO)) THEN
    IF ((MPI_RANK.EQ.0).AND.(ECHO)) THEN
      WRITE(*,*) 'MOD_BOUSSINESQ: LV = SJS^-1'
      WRITE(*,*) 'J:'
      CALL MCAT(J)
      WRITE(*,*) 'S:'
      CALL MCAT(S)
      WRITE(*,*) 'S^-1:'
      CALL MCAT(S_INV)
      WRITE(*,*) 'S*S^-1:'
      CALL MCAT(MATMUL(S, S_INV))
      WRITE(*,*) 'S*J*S^-1:'
      CALL MCAT(MATMUL(S, MATMUL(J, S_INV)))
    ENDIF
  ENDIF

  RETURN
END SUBROUTINE CALC_BOUSSI_DIAGV
!=======================================================================

SUBROUTINE CALC_BOUSSI_DIAGH(J,S,S_INV,ECHO)
!=======================================================================
! [USAGE]:
! PERFORM THE DIAGONALIZATION OF THE LINEAR BOUSSINESQ OPERATOR FOR THE 
! AXISYMMETRIC (M=0) HORIZONTAL COMPONENTS UZ AND B.
! [PARAMETERS]:
! J >> EIGENVALUE
! S >> RIGHT EIGENMATRIX
! S_INV >> LEFT EIGENMATRIX
! [NOTES]:
! 1. ONLY FOR M=0 HORIZONTAL COMPONENTS
! 2. FOR NON-AXISYMMETRIC CASE, EIGENVALUES ARE DOPPLER SHIFTED
!=======================================================================
  IMPLICIT NONE
  COMPLEX(P8), ALLOCATABLE, DIMENSION(:,:,:), INTENT(INOUT) :: J, S, S_INV
  INTEGER:: NN
  REAL(P8) :: OMEGA, SQRT_DELTA, VORT_EFF
  REAL(P8), ALLOCATABLE, DIMENSION(:) :: OMEGA0, DELTA, ZETA
  LOGICAL, OPTIONAL :: ECHO

  OMEGA = BSNSQ%OMEGA

  ALLOCATE(DELTA(NR), ZETA(NR))
  ZETA = BSNSQ%OZ0(:NR) ! AXIAL VORTICITY
  DELTA = BSNSQ%RAYLEIGH_DISCRIMINANT()

  IF (ANY(DELTA .LE. 0.D0)) THEN
    IF (MPI_RANK.EQ.0) THEN
      WRITE(*,*) 'CALC_BOUSSI_DIAGH: RAYLEIGH DISCRIMINANT IS NOT POSITIVE EVERYWHERE'
    ENDIF
    CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%BASEFLOW, IERR)
  ENDIF

  ALLOCATE(J(2,2,NR), S(2,2,NR), S_INV(2,2,NR))
  J = CMPLX(0.0D0, 0.0D0, P8)
  S = CMPLX(0.0D0, 0.0D0, P8)
  S_INV = CMPLX(0.0D0, 0.0D0, P8)

  !$OMP PARALLEL DO DEFAULT(SHARED) PRIVATE(NN, SQRT_DELTA, VORT_EFF)
  DO NN = 1, NR
    
    SQRT_DELTA = SQRT(DELTA(NN))
    VORT_EFF = 2*OMEGA + ZETA(NN)

    J(1,1,NN) = -IU * SQRT_DELTA
    J(2,2,NN) =  IU * SQRT_DELTA

    S(1,1,NN) =  IU * SQRT_DELTA / VORT_EFF
    S(1,2,NN) = -IU * SQRT_DELTA / VORT_EFF
    S(2,1,NN) = 1.0D0
    S(2,2,NN) = 1.0D0

    S_INV(1,1,NN) = -IU * VORT_EFF / (2.0D0*SQRT_DELTA)
    S_INV(1,2,NN) = 0.5D0
    S_INV(2,1,NN) =  IU * VORT_EFF / (2.0D0*SQRT_DELTA)
    S_INV(2,2,NN) = 0.5D0

  ENDDO
  !$OMP END PARALLEL DO

  DEALLOCATE(DELTA, ZETA)

  IF (PRESENT(ECHO)) THEN
    IF ((MPI_RANK.EQ.0).AND.(ECHO)) THEN
      WRITE(*,*) 'MOD_BOUSSINESQ: LH(r=0) = SJS^-1'
      WRITE(*,*) 'J:'
      CALL MCAT(J(:,:,1))
      WRITE(*,*) 'S:'
      CALL MCAT(S(:,:,1))
      WRITE(*,*) 'S^-1:'
      CALL MCAT(S_INV(:,:,1))
      WRITE(*,*) 'S*S^-1:'
      CALL MCAT(MATMUL(S(:,:,1), S_INV(:,:,1)))
      WRITE(*,*) 'S*J*S^-1:'
      CALL MCAT(MATMUL(S(:,:,1), MATMUL(J(:,:,1), S_INV(:,:,1))))
    ENDIF
  ENDIF

  RETURN
END SUBROUTINE CALC_BOUSSI_DIAGH
!=======================================================================

FUNCTION CALC_BOUSSI_PE(B) RESULT(PE)
!=======================================================================
! [USAGE]:
! CALCULATE THE POTENTIAL ENERGY IN THE SYSTEM
! [PARAMETERS]:
! B >> DENSITY TERM IN A SCALAR-TYPE VARIABLE (FFF SPACE)
! PE >> POTENTIAL ENERGY = INT ( B**2  dV )/(2N**2)
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: B
REAL(P8):: PE(NTCHOP,NXCHOP)

TYPE(SCALAR):: WK

CALL ALLOCATE(WK)

WK = B
WK%LN = 0.0_P8
CALL RTRAN(WK,1) ! Convert to PFF space
PE = L2NORM_MK_HALFK(WK) / 2.0D0 / BSNSQ%BV0**2

CALL DEALLOCATE(WK)

END FUNCTION CALC_BOUSSI_PE
!=======================================================================

FUNCTION CALC_BOUSSI_PS(RUR,RUP) RESULT(PS)
!=======================================================================
! [USAGE]:
! CALCULATE THE ENERGY PRODUCTION SPECTRUM FROM THE BACKGROUND SHEAR
! [PARAMETERS]:
! RUR, RUP >> HORIZONTAL VELOCITY COMPONENTS IN A SCALAR-TYPE VARIABLE
! PS >> ENERGY PRODUCTION SPECTRUM
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(INOUT):: RUR,RUP
REAL(P8):: PS(NTCHOP,NXCHOP)
INTEGER:: MM,KK

IF (RUR%SPACE.EQ.FFF_SPACE) THEN
  CALL RTRAN(RUR,1)
  CALL RTRAN(RUP,1)
ENDIF

IF (RUR%SPACE.NE.PFF_SPACE) THEN
  WRITE(*,*) 'CALC_BOUSSI_PS: RUR IS NOT IN PFF SPACE'
  CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%TRANSFORM, IERR)
ENDIF

! MULTIPLY RUR BY SIGMA/(R^2*(1-X)^2)
!$OMP PARALLEL DO DEFAULT(SHARED) PRIVATE(MM,KK)
DO MM = 1, SIZE(RUR%E,2)
  DO KK = 1, SIZE(RUR%E,3)
    RUR%E(:,MM,KK) = RUR%E(:,MM,KK) * BSNSQ%SIGMA0(:NR)
  ENDDO
ENDDO
!$OMP END PARALLEL DO

! INT [ RUR * RUP * SIGMA/R^2 ] dV
! = INT [ UR * UP * SIGMA ] dV
PS = PRODCT_MK_HALFK(RUR,RUP)

END FUNCTION CALC_BOUSSI_PS
!=======================================================================

SUBROUTINE CALC_BOUSSI_ENERGY(PSI,CHI,B,TIME,SAVEDIR)
!=======================================================================
! [USAGE]:
! CALCULATE KINETIC AND POTENTIAL ENERGY IN THE SYSTEM
! D(KE)/DT = DKE
! D(PE)/DT = -DKE
! [PARAMETERS]:
! PSI >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE (FFF SPACE)
! CHI >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE (FFF SPACE)
! B   >> DENSITY TERM IN A SCALAR-TYPE VARIABLE (FFF SPACE)
! TIME >> CURRENT TIME IN THE SIMULATION
! SAVEDIR >> DIRECTORY TO SAVE THE ENERGY DATA
! [DEPENDENCIES]:
! 1. DELSQH(~) @ MOD_LEGOPS <- REQUIRES CHOPSET
! 2. DEL2(~) @ MOD_LEGOPS
! 3. RTRAN(~) @ MOD_FFT
! 4. PRODCT_MK(~) @ MOD_SCALAR3
! 5. INTEG_MK(~) @ MOD_SCALAR3
!==========================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: PSI,CHI,B
TYPE(SCALAR):: W1,W2,W3,RUR,RUP
REAL(P8):: TIME
REAL(P8):: KE(NTCHOP,NXCHOP), DKE(NTCHOP,NXCHOP), PE(NTCHOP,NXCHOP), PS(NTCHOP,NXCHOP)
INTEGER:: MM,KK,FILESTATUS
CHARACTER(LEN=72):: SAVEDIR

IF (B%LN .NE. 0.D0) THEN
! LN TERM IN B IS NOT PHYSICAL, AS B CAN'T BE INFINITE AT FAR FIELD
  WRITE(*,*) 'B has non-zero LN, this is not expected in Boussinesq'
  CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%SCALAR3_LOGTERM, IERR)
ENDIF

CALL ALLOCATE(W1)
CALL ALLOCATE(W2)
CALL ALLOCATE(W3)
CALL CHOPSET(3)

! KINETIC ENERGY:
! ENERGY IN TOROIDAL COMPONENT
W1 = PSI
IF ((PSI%INX.EQ.0).AND.(PSI%INTH.EQ.0)) W1%LN = 2.0_P8*PSI%LN
CALL DELSQH(W1,W2)
W1%LN = 0.0_P8
W2%LN = 0.0_P8
CALL RTRAN(W1,1)
CALL RTRAN(W2,1)
KE = -PRODCT_MK_HALFK(W1,W2)

! ENERGY PRODUCTION FROM BACKGROUND SHEAR
CALL ALLOCATE(RUR)
CALL ALLOCATE(RUP)
CALL PC2VEL(PSI,CHI,RUR,RUP,W2,'H') ! W2 = -DELSQH(CHI)
PS = CALC_BOUSSI_PS(RUR,RUP)
CALL DEALLOCATE(RUR)
CALL DEALLOCATE(RUP)

! ENERGY IN POLOIDAL COMPONENT
CALL DEL2(CHI,W1)
W1%LN = 0.0_P8
W2%LN = 0.0_P8
CALL RTRAN(W1,1)
CALL RTRAN(W2,1)

! TOTAL KINETIC ENERGY: INT ( U**2 dV)/2
KE = KE - PRODCT_MK_HALFK(W1,W2)
KE = KE / 2.0D0
CALL DEALLOCATE(W1)

! ENERGY EXCHANGE: -INT( B * UZ dV )
W3 = B
W3%LN = 0.0_P8
CALL RTRAN(W3,1) ! Convert to PFF space
DKE = -PRODCT_MK_HALFK(W3,W2)  ! W3 = B, W2 = (1-X)^-2*DEL^2_H(CHI) = -(1-X)^-2*UZ

! POTENTIAL ENERGY: INT ( B**2  dV )/(2N**2)
PE = L2NORM_MK_HALFK(W3) / 2.0D0 / BSNSQ%BV0**2

CALL CHOPSET(-3)
CALL DEALLOCATE(W2)
CALL DEALLOCATE(W3)

! Combined PRINTOUT
IF (MPI_RANK.EQ.0) THEN
  
  OPEN(UNIT=667,FILE=TRIM(ADJUSTL(SAVEDIR))//'especData_K.dat',STATUS='UNKNOWN',&
    & IOSTAT=FILESTATUS, POSITION='APPEND')
  WRITE(667, '(" KE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(KE(:,KK)),KK=1,NXCHOP)
  WRITE(667, '(" PE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(PE(:,KK)),KK=1,NXCHOP)
  WRITE(667, '("DKE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(DKE(:,KK)),KK=1,NXCHOP)
  WRITE(667, '(" PS:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(PS(:,KK)),KK=1,NXCHOP)
  CLOSE(667)

  OPEN(UNIT=668,FILE=TRIM(ADJUSTL(SAVEDIR))//'especData_M.dat',STATUS='UNKNOWN',&
    & IOSTAT=FILESTATUS, POSITION='APPEND')
  WRITE(668, '(" KE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(KE(MM,:)),MM=1,NTCHOP)
  WRITE(668, '(" PE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(PE(MM,:)),MM=1,NTCHOP)
  WRITE(668, '("DKE:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(DKE(MM,:)),MM=1,NTCHOP)
  WRITE(668, '(" PS:",F24.16,1X,*(E24.16,1X))') TIME, (SUM(PS(MM,:)),MM=1,NTCHOP)
  CLOSE(668)

ENDIF

END SUBROUTINE CALC_BOUSSI_ENERGY
!=======================================================================

SUBROUTINE CALC_BOUSSI_NONLIN(B, RUR, RUP, UZ, BN, ROR, ROP, OZ)
!=======================================================================
! [USAGE]:
! CALCULATE THE NONLINEAR TERMS IN BOUSSINESQ APPROXIMATION:
! THE ADVECTION TERM (U X OMEGA) AND THE BUOYANCY FORCING -(U.GRAD)B.
!
! [PARAMETERS]:
! B  >> (IN) Density perturbation, must be in FFF space.
! BN >> (OUT) The nonlinear buoyancy tendency -(U.GRAD)B.
! RUR,RUP,UZ >> (INOUT) Velocity components. Updated with freestream.
! ROR,ROP,OZ >> (IN) Vorticity components from PC2VOR.
!            >> (OUT) Overwritten with U x OMEGA
! [NOTES]:
! B IN FFF SPACE
! BN IN PFF SPACE
! RUR, RUP, UZ ARE DEALLOCATED
! ROR, ROP, OZ IN FFF SPACE
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: B
TYPE(SCALAR),INTENT(INOUT):: RUR,RUP,UZ
TYPE(SCALAR),INTENT(INOUT):: ROR,ROP,OZ,BN

TYPE(SCALAR):: RBR,RBP,BZ,PSI,CHI,W
INTEGER:: NI,NJ,NK

IF (B%SPACE .NE. FFF_SPACE) THEN
  CALL MPRINT('CALC_BOUSSI_NONLIN: B SHOULD BE IN FFF SPACE!')
  CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%LEGOPERATOR, IERR)
ENDIF

CALL ALLOCATE(RBR)
CALL ALLOCATE(RBP)
CALL ALLOCATE(BZ)

CALL CHOPSET(1)
CALL GRAD(B,RBR,RBP,BZ)
CALL CHOPSET(-1)

! CONVERT ALL TO PPP SPACE
CALL TOFP(RUR); CALL TOFP(RUP); CALL TOFP(UZ)
CALL TOFP(ROR); CALL TOFP(ROP); CALL TOFP(OZ)
CALL TOFP(RBR); CALL TOFP(RBP); CALL TOFP(BZ)

NI=SIZE(RUR%E,1); NJ=SIZE(RUR%E,2); NK=SIZE(RUR%E,3)

! CALCULATING (U'+U0) X OMEGA'
! NOTE: RUR, RUP, UZ UPDATED WITH FREESTREAM VELOCITY IN PPP SPACE
!       ROR, ROP, OZ BECAME U X OMEGA IN PPP SPACE
CALL VPRODSUB(RUR%E,RUP%E,UZ%E,ROR%E,ROP%E,OZ%E,NI,NJ,NK,RUR%INR)

! CALCULATING -((U'+U0).GRAD)B
! NOTE: RUR, RUP, UZ ALREADY CONTAINS FREESTREAM DUE TO VPRODSUB
IF (ASSOCIATED(BN%E)) CALL DEALLOCATE(BN)
CALL ALLOCATE(BN,PPP_SPACE); BN%LN=0.d0
BN%E = -VDOTPSUB(RUR%E,RUP%E,UZ%E,RBR%E,RBP%E,BZ%E,NI,NJ,NK,RUR%INR,.FALSE.)

CALL DEALLOCATE(RBR); CALL DEALLOCATE(RBP); CALL DEALLOCATE(BZ)
CALL DEALLOCATE(RUR); CALL DEALLOCATE(RUP); CALL DEALLOCATE(UZ)

! MAKE ROR, ROP, OZ DIVERGENCE-FREE AGAIN
CALL ALLOCATE(PSI); CALL ALLOCATE(W)
CALL PROJECT(ROR,ROP,OZ,PSI,W,0.D0)
CALL DEALLOCATE(ROR); CALL DEALLOCATE(ROP); CALL DEALLOCATE(OZ)
CALL ALLOCATE(CHI)
CALL IDEL2(W,CHI)
CALL DEALLOCATE(W)

CALL CHOPSET(3)
CALL ALLOCATE(ROR); CALL ALLOCATE(ROP); CALL ALLOCATE(OZ)
CALL PC2VEL(PSI,CHI,ROR,ROP,OZ)
CALL DEALLOCATE(PSI); CALL DEALLOCATE(CHI)
CALL CHOPSET(-3)

! CONVERT BACK TO FFF SPACE
! CALL TOFF(BN)
CALL PLNFFT(BN,-1) ! TO PFF SPACE

RETURN
END SUBROUTINE CALC_BOUSSI_NONLIN
! ======================================================================

SUBROUTINE CALC_BOUSSI_FORCE(PSI,CHI,B,PSIN,CHIN,BN)
!=======================================================================
! [USAGE]: 
! CALCULATE THE NONLINEAR AND LINEAR TERMS
! INCLUDING ROTATION, STRATIFICATION, AND NONLINEAR ADVECTION
! [PARAMETERS]:
! PSI  >> TOROIDAL TERM IN A SCALAR-TYPE VARIABLE
! CHI  >> POLOIDAL TERM IN A SCALAR-TYPE VARIABLE
! B    >> DENSITY TERM IN A SCALAR-TYPE VARIABLE
! PSIN >> ON EXIT, TOROIDAL TERM FOR TIME ADVANCEMENT
! CHIN >> ON EXIT, POLOIDAL TERM FOR TIME ADVANCEMENT
! BN   >> ON EXIT, DENSITY TERM FOR TIME ADVANCEMENT
! [DEPENDENCIES]:
! 1. GRAD(~), PC2VEL(~), PC2VOR(~) @ MOD_LEGOPS
! 2. VPRODSUB(~), VDOTPSUB(~) @ MOD_LEGOPS
! 3. PROJECT(~), IDEL2(~) @ MOD_LEGOPS
! 4. TOFP(~), TOFF(~) @ MOD_FFT
! [NOTES]:
! 1. UPON COMPLETION, PSIN AND CHIN WILL HAVE LOG TERMS
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: PSI,CHI,B
TYPE(SCALAR),INTENT(INOUT):: PSIN,CHIN,BN

TYPE(SCALAR):: RUR,RUP,UZ
TYPE(SCALAR):: ROR,ROP,OZ
TYPE(SCALAR):: RBR,RBP,BZ
TYPE(SCALAR):: W
INTEGER:: NI,NJ,NK

CALL ALLOCATE( RUR ); CALL ALLOCATE( RUP ); CALL ALLOCATE(  UZ )
CALL ALLOCATE( ROR ); CALL ALLOCATE( ROP ); CALL ALLOCATE(  OZ )
CALL ALLOCATE( RBR ); CALL ALLOCATE( RBP ); CALL ALLOCATE(  BZ )

! DEALIASING
CALL CHOPSET(3)

! OBTAINING GRAD(B)
CALL GRAD(B,RBR,RBP,BZ)                                            ! NOTE: INPUT AND OUTPUTS ARE STILL IN FFF SPACE

! OBTAINING VELOCITY AND VORTICITY
CALL PC2VEL(PSI,CHI,RUR,RUP,UZ)                                    ! NOTE: INPUT AND OUTPUTS ARE STILL IN FFF SPACE
CALL PC2VOR(PSI,CHI,ROR,ROP,OZ)                                    ! NOTE: INPUT AND OUTPUTS ARE STILL IN FFF SPACE

! FFF -> PPP SPACE
CALL TOFP(RUR); CALL TOFP(RUP); CALL TOFP(UZ)
CALL TOFP(ROR); CALL TOFP(ROP); CALL TOFP(OZ)
CALL TOFP(RBR); CALL TOFP(RBP); CALL TOFP(BZ)

! CALCULATE NONLINEAR TERMS
NI=SIZE(RUR%E,1); NJ=SIZE(RUR%E,2); NK=SIZE(RUR%E,3)
!> CALCULATING U X OMEGA
!> NOTE: RUR, RUP, UZ UPDATED WITH FREESTREAM VELOCITY IN PPP SPACE
!>       ROR, ROP, OZ BECAME U X OMEGA IN PPP SPACE
CALL VPRODSUB(RUR%E,RUP%E,UZ%E,ROR%E,ROP%E,OZ%E,NI,NJ,NK,RUR%INR)
!> CALCULATING -(U.GRAD)B
!> NOTE: RUR, RUP, UZ ALREADY CONTAINS FREESTREAM DUE TO VPRODSUB
IF (ASSOCIATED(BN%E)) CALL DEALLOCATE(BN)
CALL ALLOCATE(BN,PPP_SPACE); BN%LN=0
BN%E = -VDOTPSUB(RUR%E,RUP%E,UZ%E,RBR%E,RBP%E,BZ%E,NI,NJ,NK,RUR%INR,.FALSE.)

! END DEALIASING
CALL CHOPSET(-3)

! ADD LINEAR TERMS TO NONLINEAR TERMS
CALL ALLOCATE(W); W = B
CALL TOFP(W)
!> 2OMEGA Z_HAT X U - B Z_HAT
ROR%E = ROR%E + 2*BSNSQ%OMEGA*RUP%E
ROP%E = ROP%E - 2*BSNSQ%OMEGA*RUR%E

OZ%E  = OZ%E - W%E
CALL DEALLOCATE(W)
!> N_BAR^2 * UZ
BN%E = BN%E + BSNSQ%BV0**2*UZ%E

CALL DEALLOCATE( RUR ); CALL DEALLOCATE( RUP ); CALL DEALLOCATE( UZ  )
CALL DEALLOCATE( RBR ); CALL DEALLOCATE( RBP ); CALL DEALLOCATE( BZ  )

!> CALCULATING FINAL TERMS PSIN, CHIN, BN IN FFF SPACE
CALL ALLOCATE(W)
CALL PROJECT(ROR,ROP,OZ,PSIN,W,0.D0)                               ! NOW PSIN = PSI_NONLINEAR AND W = DELSQ(CHI_NONLINEAR)
CALL DEALLOCATE( ROR )
CALL DEALLOCATE( ROP )
CALL DEALLOCATE( OZ  )

! CALL IDEL2(W,CHIN)                                               ! NOW CHIN = CHI_NONLINEAR
CALL IDEL2LN(W,CHIN)
CALL DEALLOCATE( W   )
CALL TOFF(BN)

CALL MPI_BARRIER(MPI_COMM_IVP,IERR)
RETURN
END SUBROUTINE CALC_BOUSSI_FORCE
! ======================================================================

FUNCTION INTEGR_K_FFF(F)
!=======================================================================
! [USAGE]:
! INTEGRATION OF A FUNCTION OVER R FOR EACH K
! CALL IN FFF_SPACE AND PERFORM INTEGRATION IN FFF_SPACE
! INTEGRATED FUNCTION G IS IN THE FORM G = F*(1-MU)^2
! [INPUTS]:
! F >> A FUNTION INPUT FOR INTEGRATION (ACTUAL INTEGRATION IS DONE ON G)
! [OUTPUTS]:
! INTEGR_K_FFF >> INTEGRATION EQUAL TO INT(G(R,PHI,Z) RDR)
!========================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: F
COMPLEX(P8),DIMENSION(NXCHOPDIM):: INTEGR_K_FFF
INTEGER:: KK,COUNT

IF(F%SPACE.NE.FFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
    WRITE(*,*) 'INTEGR_K_FFF: NOT IN FFF_SPACE'
  ENDIF
  STOP
ENDIF

INTEGR_K_FFF = CMPLX(0.D0,0.D0)
IF (F%INTH .EQ. 0) THEN
  DO KK = 1,SIZE(F%E,3) !NXCHOP
    INTEGR_K_FFF(KK+F%INX) = &
      2.0_P8 * ELL2 * F%E(1,1,KK) * TFM%NORM(1,1)
  ENDDO
ENDIF

COUNT = NXCHOPDIM
CALL MPI_ALLREDUCE(MPI_IN_PLACE, INTEGR_K_FFF, COUNT, &
                  MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_IVP, IERR)

RETURN
END FUNCTION INTEGR_K_FFF
!=======================================================================

FUNCTION INTEGR_K_PFF(F)
!=======================================================================
! [USAGE]:
! INTEGRATION OF A FUNCTION OVER R FOR EACH K
! CALL IN FFF_SPACE BUT PERFORM INTEGRATION IN PFF_SPACE
! [NOTES]:
! 1. RDR = L^2 * DX/(1-X)^2
! 2. INTEGRATION OVER X IS BASED ON GAUSS-LEGENDRE QUADRATURE
!========================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: F
TYPE(SCALAR):: F_COPY
COMPLEX(P8),DIMENSION(NXCHOPDIM):: INTEGR_K_PFF
INTEGER:: KK,COUNT
REAL(P8):: DOT_REAL, DOT_IMAG

IF(F%SPACE.NE.FFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
    WRITE(*,*) 'INTEGR_K_PFF: NOT IN FFF_SPACE'
  ENDIF
  STOP
ENDIF

CALL ALLOCATE(F_COPY)
F_COPY = F
CALL RTRAN(F_COPY,1) ! Convert to PFF space

INTEGR_K_PFF = CMPLX(0.D0,0.D0)
IF (F_COPY%INTH .EQ. 0) THEN
  DO KK = 1,SIZE(F_COPY%E,3) !NXCHOP
    DOT_REAL = DOT_PRODUCT(REAL(F_COPY%E(:NR,1,KK))/(1.D0-TFM%X)**2,TFM%W)
    DOT_IMAG = DOT_PRODUCT(AIMAG(F_COPY%E(:NR,1,KK))/(1.D0-TFM%X)**2,TFM%W)
    INTEGR_K_PFF(KK+F_COPY%INX) = ELL2 * (DOT_REAL + IU * DOT_IMAG)
  ENDDO
ENDIF

CALL DEALLOCATE(F_COPY)
COUNT = NXCHOPDIM
CALL MPI_ALLREDUCE(MPI_IN_PLACE, INTEGR_K_PFF, COUNT, &
                  MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_IVP, IERR)

RETURN
END FUNCTION INTEGR_K_PFF
!=======================================================================

END MODULE