MODULE MOD_SCALAR3 ! LEVEL 2 MODULE
! TYPE SETUP: SCALAR & TRANSFORM
USE omp_lib
USE MPI
USE MOD_MISC, ONLY : P4,P8,PI,IU, CP8_SIZE                         ! LEVEL 0
!XUSE USE MOD_FD                                                         ! LEVEL 1
USE MOD_EIG                                                        ! LEVEL 1
USE MOD_LIN_LEGENDRE                                               ! LEVEL 1
USE IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
IMPLICIT NONE
PRIVATE
!=======================================================================
!============================ PARAMETERS ===============================
!=======================================================================
! 1.1> DIMENSIONS
INTEGER, PUBLIC:: NR,NRH                                           ! # OF COLLOCATION POINTS (= SPECTRAL COEFFICIENTS IF IN FUNC. SPACE) IN THE RADIAL DIRECTION R (OR X WHEN UNMAPPED); NRH = NR/2
INTEGER, PUBLIC:: NX                                               ! # OF COLLOCATION POINTS (= SPECTRAL COEFFICIENTS IF IN FUNC. SPACE) IN THE AXIAL DIRECTION Z
INTEGER, PUBLIC:: NTH                                              ! # OF COLLOCATION POINTS (= SPECTRAL COEFFICIENTS IF IN FUNC. SPACE) IN THE AZIMUTHAL DIRECTION THETA
INTEGER, PUBLIC:: NRCHOP,NTCHOP                                    ! CHOP INDICES IN RADIAL AND TH FOR TRUCATION IN ORDER TO LET THE MAIMUM DEGREE OF THE BASIS BE LIMITED.
INTEGER, PUBLIC,DIMENSION(:),ALLOCATABLE:: NRCHOPS,NTCHOPS         ! CHOP INDICES IN RADIAL AND TH FOR EACH N OF P^M_N
INTEGER, PUBLIC:: NXCHOP,NXCHOPH                                   ! CHOP INDEX IN Z DETERMINING THE MAXIMUM DEGREE USED IN THIS SPECTRAL ANALYSIS) ; NXCHOPH = CHOPPING LOCATION FOR THE CONJUGATE SIDE
REAL(P8),PUBLIC:: ZLEN,ZLEN0                                       ! PERIOD IN THE AXIAL DIRECTION (NOTE: Z-PERIODICITY IS ASSUMED SO THAT WE USE FOURIER SPECTRAL METHOD IN Z. THE EVP CODE CHANGES ZLEN FOR FAST CALCULATION, SO THE ORIGINAL ZLEN IS SAVED AS ZLEN0 FOR ENERGY CALCULATION.)
REAL(P8),PUBLIC:: ELL,ELL2                                         ! THE MAP PARAMTER ELL (MATSUSHIMA AND MARCUS, 1997); ELL2 = ELL**2
INTEGER, PUBLIC:: MKLINK                                           ! MKLINK = 1 OR -1 IF M AND K ARE LINKED TOGETHER. OTHERWISE, SET 0 AS DEFAULT.
INTEGER, PUBLIC:: MINC                                             ! THE NUMBER OF SYMMETRY OCCURRING IN THE AZIMUTHAL DIRECTION (E.G., SEEING 4 IDENTICAL PATTERNS IN THETA, THEN MINC = 4). DEFAULT IS 1 (NO INNER SYMMETRY).
INTEGER, PUBLIC:: NDIMR,NDIMTH,NDIMX                               ! # OF DIMENSIONS IN EACH DIRECTION
INTEGER, PUBLIC:: NRCHOPDIM,NTCHOPDIM,NXCHOPDIM                    ! # OF DIMENSIONS IN EACH DIRECTION AFTER CHOPPED
INTEGER, PUBLIC,DIMENSION(:),ALLOCATABLE:: M                       ! ACCESSIBLE AZIMUTHAL WAVENUMBERS
REAL(P8),PUBLIC,DIMENSION(:,:),ALLOCATABLE:: AK                    ! ACCESSIBLE AXIAL WAVENUMBERS GIVEN AZIMUTHAL WAVENUMBER M
! 1.2> MPI-SPECIFIC
INTEGER, PUBLIC:: MPI_RANK, MPI_COMM_IVP, MPI_THREAD_MODE
INTEGER, PUBLIC:: SUBCOMM_1 = 0, SUBCOMM_2 = 0                     ! SUBCOMMUNICATOR GROUPS FOR MPI EXCHANGE
INTEGER, PUBLIC,DIMENSION(:),ALLOCATABLE:: &
                  TYPE_PFP0,TYPE_PFP1,TYPE_PFF0,TYPE_PFF1          ! SUBARRAY DATA TYPES FOR MPI EXCHANGE
INTEGER, PUBLIC,DIMENSION(3):: &
                  SIZE_PFP0,SIZE_PFP1,SIZE_PFF0,SIZE_PFF1          ! SUBARRAY DATA TYPES FOR MPI EXCHANGE
INTEGER, PUBLIC:: IERR                                             ! MPI ERROR STATUS

! 2> TYPES
PUBLIC:: SCALAR                                                    ! ANY PHYSICAL QUANTITY IN INTEREST WILL BE DECLARED THORUGH THIS TYPE (U,V,W,P,ETC.)
TYPE SCALAR
COMPLEX(P8),DIMENSION(:,:,:),POINTER:: E                           ! PHYSICAL QUANTITY (OR FUNCTION COEFFICIENT IF IN FUNCTION SPACE) IN EACH NODE; ORDER CONVENTION = (Z, THETA, X)
REAL(P8)                            :: LN = 0.D0                   ! LOCARITHMIC TERM UTILIZED FOR THE TOROIDAL-POLOIDAL DECOMPOSITION (EQ. 54 OF MATSUSHIMA AND MARCUS (1997))
INTEGER                             :: SPACE = -1                  ! TAG SHOWING IN WHICH SPACE THIS SCALAR-TYPE VALUE IS. SEE 4> SPACE TAG
INTEGER                             :: INR = 0, INTH = 0, INX = 0  ! LOCAL ARRAY STARTING INDEX
LOGICAL                             :: IS_ALLOCATED = .FALSE.      ! TRUE IF E IS ALLOCATED
END TYPE

! 3> TRANSFORM KIT
PUBLIC:: TRANSFORM                                                 ! PHY. -> FUNC. OR FUNC -> PHY. TRANSFORMATION
TYPE TRANSFORM
REAL(P8),   DIMENSION(:),    POINTER:: R,dR                        ! COLLOCATION POINTS IN R (EVALUATED VIA GAUSS-LEGENDRE QUADRATURE)
REAL(P8),   DIMENSION(:),    POINTER:: X                           ! UNMAPPED COLLOCATION POINTS IN R (X=(R^2-ELL^2)/(R^2+ELL^2))
REAL(P8),   DIMENSION(:),    POINTER:: W                           ! GAUSS-LEGENDRE WEIGHT. W(I) IS FOR X(I)
REAL(P8),   DIMENSION(:,:),  POINTER:: NORM,LOGNORM                ! NORMALIZATION FACTORS OF P^M_N
REAL(P8),   DIMENSION(:,:,:),POINTER:: PF                          ! LEGENDRE POLYNOMIAL VALUE TABLE FOR P^M_N(X_I) GIVEN M, N AND I
REAL(P8),   DIMENSION(:),    POINTER:: AT0,AT1                     ! LEGENDRE POLYNOMIAL EVALUATION AT X=-1(R=0 -> AT0) AND X=1(R=INF -> AT1)
REAL(P8),   DIMENSION(:),    POINTER:: LN                          ! MINUS LOG VALUE OF X 
REAL(P8),   DIMENSION(:),    POINTER:: Z                           ! EQUISPACED COLLOCATION POINTS IN Z (FOR FOURIER SPECTRAL ANALYSIS)
REAL(P8),   DIMENSION(:),    POINTER:: THR,THI,TH                  ! EQUISPACED COLLOCATION POINTS IN THETA (FOR FOURIER SPECTRAL ANALYSIS)
! COMPLEX(P8),DIMENSION(:),    POINTER:: EX                          ! STORES EXP((I*2*PI/N)*J) FOR FFT
! INTEGER(P8):: NMAX                                                 ! SET TO BE MAX(NTH,NX)*2
END TYPE
TYPE(TRANSFORM),PUBLIC:: TFM                                       ! UNIVERSAL TRANSFORM KIT DECLARED IN THIS CLASS ACROSS THE CODE

! 4> SPACE TAG (KIT)
TYPE SPACE_MAP_ENTRY
    CHARACTER(LEN=20) :: NAME
    INTEGER :: ID
END TYPE
TYPE SPACE_MAP
    TYPE(SPACE_MAP_ENTRY), DIMENSION(4) :: ENTRIES
    LOGICAL :: INITIALIZED = .FALSE.
CONTAINS
    PROCEDURE :: INIT => SPACE_MAP_INIT
    PROCEDURE :: GET_ID => SPACE_MAP_GET_ID
    PROCEDURE :: GET_NAME => SPACE_MAP_GET_NAME
    PROCEDURE :: HAS_KEY => SPACE_MAP_HAS_KEY
    PROCEDURE :: SIZE => SPACE_MAP_SIZE
END TYPE
TYPE(SPACE_MAP), PUBLIC :: SPACE_MAPPER
INTEGER,PUBLIC,PARAMETER:: PPP_SPACE=0                             ! (X (OR R), THETA, Z) = (PHYS.          , PHYS.          , PHYS.          )
INTEGER,PUBLIC,PARAMETER:: FFF_SPACE=1                             ! (X (OR R), THETA, Z) = (FUNC. (MAP_LEG), FUNC. (FOURIER), FUNC. (FOURIER))
INTEGER,PUBLIC,PARAMETER:: PFP_SPACE=2                             ! (X (OR R), THETA, Z) = (PHYS.          , FUNC. (FOURIER), PHYS.          )
INTEGER,PUBLIC,PARAMETER:: PFF_SPACE=3                             ! (X (OR R), THETA, Z) = (PHYS.          , FUNC. (FOURIER), FUNC. (FOURIER))

! 5> ERROR FLAGS
TYPE ERROR_FLAGS
  INTEGER :: SCALAR3 = 1
  INTEGER :: SCALAR3_ISNAN = 10
  INTEGER :: SCALAR3_DEALIASING = 11
  INTEGER :: SCALAR3_DIVERGENCE = 12
  INTEGER :: SCALAR3_LOGTERM = 13

  INTEGER :: TRANSFORM = 2

  INTEGER :: LEGOPERATOR = 3
  INTEGER :: DEPRECATED = 30
  INTEGER :: CALCULATION = 31
  INTEGER :: DIMMISMATCH = 32

  INTEGER :: SOLVER = 4
END TYPE
TYPE(ERROR_FLAGS), PUBLIC :: ERR_FLAGS

!=======================================================================
!======================== PUBLIC DECLARATION ===========================
!=======================================================================
! CHOP BASED ON THE INITIALZED CHOP VALUES IN EACH DIRECTION
PUBLIC:: CHOPSET
PUBLIC:: CHOPDO
! RETURNS THE FUNCTION VALUE AT INFINITY(CALCAT1) OR ORIGIN(0) (ONLY BE CALLED BY ROOT PROC)
PUBLIC:: CALCAT1,CALCAT0                                           ! A VALUE IS RETURNED FOR EACH K.
! INTEGRATION OF A FUNCTION OVER A FULL-(~) OR HALF-(~H) DOMAIN (ONLY BE CALLED BY ROOT PROC)
PUBLIC:: INTEG                                                     ! AVAILABLE ONLY WHEN SPACE = FFF
PUBLIC:: INTEGH                                                    ! AVAILABLE ONLY WHEN SPACE = PFF
PUBLIC:: INTEG_MK                                                  ! AVAILABLE ONLY WHEN SPACE = PFF
! PRODUCT & INTEGRATE F=A*B*(1-X)**2. OVER THE DOMAIN
PUBLIC:: PRODCT                                                    ! AVAILABLE ONLY WHEN SPACE = PFF
PUBLIC:: PRODCT_M, PRODCT_K
PUBLIC:: PRODCT_MK, PRODCT_MK_ALLK, PRODCT_MK_HALFK                ! AVAILABLE ONLY WHEN SPACE = PFF
PUBLIC:: L2NORM_MK_ALLK, L2NORM_MK_HALFK                           ! AVAILABLE ONLY WHEN SPACE = PFF
! CHECK IF A SCALAR CONTAINS NAN
PUBLIC:: ANYNAN

INTERFACE PRODCT_MK
  MODULE PROCEDURE PRODCT_MK_ALLK
END INTERFACE PRODCT_MK

CONTAINS
!=======================================================================
!============================ SUBROUTINES ==============================
!=======================================================================
SUBROUTINE EXSET(EX, NPTS)
!=======================================================================
! [USAGE]: 
! CALCULATE EXP((i*2*PI/NPTS)*J) INTENSIVELY USED FOR FOURIER SPACE
! WHERE J RANGES FROM -NPTS/2 TO NPTS/2
! [PARAMETERS]:
! EX >> AN ARRAY WHERE THE EXPONENTS ARE STORED
! NPTS >> THE SIZE OF THE ARRAY EX
! [UPDATES]:
! RE-CODED IN MODERN FORTRAN FORMAT BY SANGJOON LEE @ NOV 11 2020
!=======================================================================
IMPLICIT NONE
INTEGER(P8):: NPTS
COMPLEX(P8),DIMENSION(1:NPTS):: EX

INTEGER(P8):: NH,J
REAL(P8)   :: W

W = 2*PI/FLOAT(NPTS)
NH = NPTS/2

DO J = 1,NH
  EX(J) = EXP(CMPLX(0.D0,DFLOAT(J-1)*W))
  EX(J+NH) = EXP(CMPLX(0.D0,DFLOAT(1-J)*W))
ENDDO

RETURN
END SUBROUTINE EXSET
!=======================================================================
SUBROUTINE CHOPSET(IOF)
!=======================================================================
! [USAGE]: 
! SETTING UP THE CHOP LOCATIONS FOR AZIMUTHAL AND AXIAL FUNCTION COEFFS.
! [PARAMETERS]:
! IOF >> OFFSET OF NRCHOP
! [NOTES]:
! SEE THE BELOW DIAGRAM TO UNDERSTAND HOW CHOPPING IS DONE.
!     NR-> +----------------------------------------+---------+
! NRCHOP-> +--+                                     +         +
! (NRDEG)  +  +-----+              INACTIVE         +    I    +
!          +        +-----+                         +    N    +
!          +              +-----+                   +    A    +
!          +                    +-----+ GRAD=-1     +    C    +
!          +                          +-----+       +    T    +
!          +                                +-----+ +    I    +
!          +         ACTIVE COEFFICIENTS          +-+    V    +
!          +                                        +    E    +
!          +                                        +         +
!          +----------------------------------------+---------+
!                                                   ↑         ↑ 
! [UPDATES]:                                   NTCHOP       NTH
! RE-CODED BY SANGJOON LEE @ NOV 11 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
INTEGER:: IOF
INTEGER:: MM,NN,NRDEG
NRCHOP = NRCHOP + IOF
NRDEG  = NRCHOP 
IF(NRCHOP.GT.NRCHOPDIM) THEN
  IF (MPI_RANK.EQ.0) THEN
  WRITE(*,*) 'CHOPSET: NRCHOP TOO LARGE.'
  WRITE(*,*) '  NRCHOP=',NRCHOP,'  NRCHOPDIM=',NRCHOPDIM
  ENDIF
STOP
ENDIF

DO MM=1,NTCHOPDIM
  NRCHOPS(MM) = MAX(MIN(NRCHOP,NRDEG-M(MM)),0)
ENDDO
NRCHOPS(NTCHOPDIM+1:)=0
DO NN=1,NR
  NTCHOPS(NN) = MAX(MIN(NTCHOP,(NRDEG-NN+MINC)/MINC),0)
ENDDO

RETURN
END SUBROUTINE CHOPSET
!=======================================================================
SUBROUTINE CHOPDO(A)
!=======================================================================
! [USAGE]: 
! PERFORM CHOPPING FUNCTION SPACE COEFFFICIENTS.
! [PARAMETERS]:
! A >> TYPE(SCALAR) VARIABLE CONTAIN FUNCTION SPACE INFORMATION
!      HENCE, EXPECTED TO BE A%SPACE = FFF_SPACE
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 11 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
TYPE(SCALAR):: A
INTEGER::MM,NTCHOP_LOC,NR_LOC

! FFF_SPACE:
IF (A%SPACE.EQ.FFF_SPACE) THEN
  NTCHOP_LOC = NTCHOP-A%INTH
  ! IF (NTCHOP_LOC.GT.0) THEN
  DO MM = 1,MIN(SIZE(A%E,2),NTCHOP_LOC)
    A%E(NRCHOPS(A%INTH+MM)+1:,MM,:) = CMPLX(0.D0,0.D0)
  ENDDO
  ! ENDIF
  A%E(:,MAX(1,NTCHOP_LOC+1):,:) = CMPLX(0.D0,0.D0)
  ! DO MM=1,NTCHOP
  !   A%E(NRCHOPS(MM)+1:,MM,:)= CMPLX(0.D0,0.D0)
  ! ENDDO
  ! A%E(:,NTCHOP+1:,:) = CMPLX(0.D0,0.D0)

! PFF_SPACE:
ELSEIF (A%SPACE.EQ.PFF_SPACE) THEN
  A%E(NR+1:,:,:)  = 0.D0

! PPP_SPACE OR PFP_SPACE:
ELSE
  IF (A%SPACE.EQ.PPP_SPACE) A%E(:,NTH+1,:) = 0.D0
  NR_LOC = MAX(NR - A%INR,0)
  IF (NR_LOC .LT. SIZE(A%E,1)) THEN
    A%E(NR_LOC+1:,:,:) = 0.D0
  ENDIF
  ! A%E(:,NTH+1,:) = 0.D0
  ! A%E(NR+1,:,:)  = 0.D0
ENDIF

RETURN
END SUBROUTINE CHOPDO

!=======================================================================
!============================ FUNCTIONS ================================
!=======================================================================
FUNCTION CALCAT0(A)
!=======================================================================
! [USAGE]:
! RETURNS THE FUNCTION VALUE AT ORIGIN (R = 0)
! [INPUTS]:
! A >> TYPE(SCALAR) VARIABLE CONTAIN (X,THETA,Z) VALUES IN FFF SPACE
! [OUTPUTS]:
! CALCAT0 >> FUNCTION VALUE AT ORIGIN (R = 0)
! [NOTE]:
! SHOULD ONLY CALLED BY PROCS THAT HAVE M=0 MODE
!=======================================================================
TYPE(SCALAR),INTENT(IN):: A

COMPLEX(P8),DIMENSION(SIZE(A%E,3)):: CALCAT0

IF (A%INTH.NE.0) THEN
  WRITE(*,*) 'CALCAT0: INPUT MUST CONTAIN M=0 MODE'
ENDIF

CALCAT0 = TRANSPOSE(A%E(:NRCHOP,1,:)).MUL. TFM%AT0(:NRCHOP)

RETURN
END FUNCTION CALCAT0
!=======================================================================
FUNCTION CALCAT1(A)
!=======================================================================
! [USAGE]:
! RETURNS THE FUNCTION VALUE AT INFINITY (R = INF)
! [INPUTS]:
! A >> TYPE(SCALAR) VARIABLE CONTAIN (X,THETA,Z) VALUES IN FFF SPACE
! [OUTPUTS]:
! CALCAT0 >> FUNCTION VALUE AT ORIGIN (R = INF)
! [NOTE]:
! SHOULD ONLY CALLED BY PROCS THAT HAVE M=0 MODE
! SAFE TO CALL IN EA LOCALARRAY WITH INTH = 0
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
TYPE(SCALAR),INTENT(IN):: A

COMPLEX(P8),DIMENSION(SIZE(A%E,3)):: CALCAT1

IF (A%INTH.NE.0) THEN
  WRITE(*,*) 'CALCAT1: INPUT MUST CONTAIN M=0 MODE'
ENDIF

CALCAT1 = TRANSPOSE(A%E(:NRCHOP,1,:)) .MUL. TFM%AT1(:NRCHOP)

RETURN
END FUNCTION CALCAT1
!=======================================================================
FUNCTION INTEG(F)
!=======================================================================
! [USAGE]:
! INTEGRATION OF A FUNCTION OVER A DOMAIN 
!     0  <  R   < INFTY
!     0  <  PHI < 2*PI
!     0  <  Z   < ZLEN
! CALL IN F/F SPACE
! INTEGRATED FUNCTION G IS IN THE FORM G = F*(1-MU)^2
! [INPUTS]:
! F >> A FUNTION INPUT FOR INTEGRATION (ACTUAL INTEGRATION IS DONE ON G)
! [OUTPUTS]:
! INTEG >> INTEGRATION EQUAL TO INT_[FULL_RANGE](G(R,PHI,Z) DR DPHI DZ)
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 18 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: F
REAL(P8)::INTEG

IF(F%SPACE.NE.FFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) WRITE(*,*) 'INTEG: NOT IN FFF_SPACE'
  STOP
ENDIF      

IF ((F%INTH.EQ.0).AND.(F%INX.EQ.0)) THEN
  ! INTEGRATION OF R*LOGTERM GOES TO INFINITY
  IF(F%LN.NE.0.0) THEN
    WRITE(*,*) 'INTEG: LOGTERM NOT ZERO'
    WRITE(*,*) 'LOGTERM=',F%LN
  ENDIF
  ! ADDITIONAL FACTOR OF 2 COMES FROM (N^0_0)^2 = 2
  INTEG = 4.0_P8*PI*ZLEN*ELL2*REAL(F%E(1,1,1))*TFM%NORM(1,1)
ELSE
  INTEG = 0
ENDIF
CALL MPI_ALLREDUCE(MPI_IN_PLACE, INTEG, 1, MPI_DOUBLE_PRECISION, &
      MPI_SUM, MPI_COMM_IVP, IERR)

RETURN
END FUNCTION INTEG
!=======================================================================
FUNCTION INTEG_MK(F)
!=======================================================================
! [USAGE]:
! INTEGRATION OF A FUNCTION OVER R FOR EACH M AND K
! CALL IN PFF_SPACE
! INTEGRATED FUNCTION G IS IN THE FORM G = F*(1-MU)^2
! [INPUTS]:
! F >> A FUNTION INPUT FOR INTEGRATION (ACTUAL INTEGRATION IS DONE ON G)
! [OUTPUTS]:
! INTEG_MK >> INTEGRATION EQUAL TO INT(G(R,PHI,Z) RDR)
!========================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: F
COMPLEX(P8),DIMENSION(NTCHOP,NXCHOPDIM):: INTEG_MK
INTEGER:: MM,KK,COUNT
REAL(P8):: DOT_REAL, DOT_IMAG

IF(F%SPACE.NE.PFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
    WRITE(*,*) 'INTEG_MK: NOT IN PFF_SPACE'
  ENDIF
  STOP
ENDIF

INTEG_MK = CMPLX(0.D0,0.D0)
!$OMP PARALLEL DO COLLAPSE(2) PRIVATE(DOT_REAL,DOT_IMAG) SCHEDULE(STATIC)
DO KK = 1,SIZE(F%E,3) !NXCHOP
  DO MM = 1,SIZE(F%E,2) !NTCHOP
    DOT_REAL = DOT_PRODUCT(REAL(F%E(:NR,MM,KK)),TFM%W)
    DOT_IMAG = DOT_PRODUCT(AIMAG(F%E(:NR,MM,KK)),TFM%W)
    INTEG_MK(MM+F%INTH,KK+F%INX) = &
      ELL2 * (DOT_REAL + IU*DOT_IMAG)
  ENDDO
ENDDO
!$OMP END PARALLEL DO

COUNT = NTCHOP*NXCHOPDIM
CALL MPI_ALLREDUCE(MPI_IN_PLACE, INTEG_MK, COUNT, &
                  MPI_DOUBLE_COMPLEX, MPI_SUM, MPI_COMM_IVP, IERR)

RETURN
END FUNCTION INTEG_MK
!=======================================================================
FUNCTION PRODCT(A,B)
!=======================================================================
! [USAGE]:
! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE
! WHAT IS ACTUALLY INTEGRATED IS G = A*B*(1-MU)^2
! [INPUTS]:
! A >> FIRST SCALAR-TYPE VARIABLE FOR INTEGRATION
! B >> SECOND SCALAR-TYPE VARIABLE FOR INTEGRATION
! [OUTPUTS]:
! PRODCT >> INTEGRATION EQUAL TO INT_[FULL_RANGE](G(R,PHI,Z) DR DPHI DZ)
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: A,B
REAL(P8):: PRODCT

COMPLEX(P8):: PROD(NR)
INTEGER:: MM,KK

IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
    WRITE(*,*) 'PRODCT:NOT IN PFF_SPACE'
    WRITE(*,*) 'A%SPACE,B%SPACE=',A%SPACE,B%SPACE
  ENDIF
  STOP
ENDIF

! IF EITHER OR BOTH A AND B CONTAINS LOGTERM, THE INTEGRATION WILL ALWAYS
! DIVERGE TO INFINITY. SO, WE CHECK IF THE LOGTERM IS ZERO.
! NOTE: FOR G(R), INT[LOGTERM*G(R)*R]DR DIVERGES WHENEVER G(R) DECAYS SLOWER
! THAN 1/(R*LN(R)) AS R -> INFINITY. SINCE THE PHYSICAL SPACE FUNCTION 
! DECAYS ALGEBRAICALLY (I.E. R^-|M|), THE INTEGRATION WILL DIVERGE WHENEVER
! THE FUNCTION CONTAINS |M|<=2 MODES, WHICH IS ALMOST ALWAYS THE CASE.
IF(A%LN.NE.0.0 .OR. B%LN.NE.0.0) THEN
  WRITE(*,*) 'PRODCT:LOGTERM NOT ZERO'
ENDIF

! PROD=0
! DO KK = 1,NX
!   IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
!   PROD = PROD+A%E(:NR,1,KK)*CONJG(B%E(:NR,1,KK))
! ENDDO

! DO KK = 1,NX
!   IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
!   DO MM = 2,NTCHOP
!     PROD = PROD + 2*(REAL(A%E(:NR,MM,KK))*REAL(B%E(:NR,MM,KK)) &
!                 + AIMAG(A%E(:NR,MM,KK))*AIMAG(B%E(:NR,MM,KK)))
!   ENDDO
! ENDDO

PROD=0
!$OMP PARALLEL DO COLLAPSE(2) PRIVATE(MM,KK) SCHEDULE(STATIC) REDUCTION(+:PROD)
DO KK = 1,SIZE(A%E,3)
  DO MM = 1,SIZE(A%E,2) !NTCHOP
    IF (MM+A%INTH.EQ.1) THEN ! M(1) = 0
    PROD = PROD+A%E(:NR,1,KK)*CONJG(B%E(:NR,1,KK))
    ELSE
    PROD = PROD + 2.0_P8*(REAL(A%E(:NR,MM,KK))*REAL(B%E(:NR,MM,KK)) &
                + AIMAG(A%E(:NR,MM,KK))*AIMAG(B%E(:NR,MM,KK)))
    ENDIF
  ENDDO
ENDDO
!$OMP END PARALLEL DO
PRODCT = SUM(PROD*TFM%W)

CALL MPI_ALLREDUCE(MPI_IN_PLACE, PRODCT, 1, MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_IVP, IERR)
PRODCT = 2*PI*ZLEN*ELL2*PRODCT

RETURN
END FUNCTION PRODCT
!=======================================================================
FUNCTION PRODCT_MK_ALLK(A,B)
! ======================================================================
! [USAGE]:
! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN FOR EACH M AND K
! CALL IN R PHYSICAL / PHI,Z-FOURIER SPACE
! WHAT IS ACTUALLY INTEGRATED IS G = A*B*(1-MU)^2
! [INPUTS]:
! A >> FIRST SCALAR-TYPE VARIABLE FOR INTEGRATION
! B >> SECOND SCALAR-TYPE VARIABLE FOR INTEGRATION
! [OUTPUTS]:
! PRODCT_MK >> INTEGRATION EQUAL TO INT(G(R,PHI,Z) RDR DPHI DZ)
! DISTRIBUTED OVER M AND K BASED ON THE PARSEVAL'S THEOREM
! ======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: A,B
REAL(P8):: WK1(NR)
REAL(P8):: PRODCT_MK_ALLK(NTCHOP,NXCHOPDIM) !NX)
INTEGER:: MM,KK,COUNT

IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
      PRINT *,'ERROR: PRODCT_MK() -- NOT IN PFF_SPACE.'
      PRINT *,'A%SPACE, B%SPACE = ',A%SPACE,B%SPACE
  ENDIF
  STOP
ENDIF

IF ((A%INTH.EQ.0).AND.(A%INX.EQ.0)) THEN
  IF(ABS(A%LN)>1.0E-8 .OR. ABS(B%LN)>1.0E-8) THEN
      PRINT *,'WARNING: PRODCT_MK() -- LOGTERM NOT ZERO.'
      PRINT *,'A%LN, B%LN = ',A%LN,B%LN
  ENDIF
ENDIF

PRODCT_MK_ALLK = 0.D0
!$OMP PARALLEL DO COLLAPSE(2) PRIVATE(WK1) SCHEDULE(STATIC)
DO KK=1,SIZE(A%E,3) !NXCHOP
  DO MM=1,SIZE(A%E,2) !NTCHOP
      WK1 = REAL( A%E(:NR,MM,KK)*CONJG(B%E(:NR,MM,KK)) )
      ! {MM,KK}&{-MM,-KK} combined
      ! note: We save non-negative M's, but all K's.
      !       So, for {0,KK}, we should not add {0,-KK} during the calculation,
      !       as {0,-KK} is actually saved. Hence, all MM = 0 modes' product is
      !       off by a factor of 2.
      PRODCT_MK_ALLK(MM+A%INTH,KK+A%INX) = &
              4.0_P8*PI*ZLEN0*ELL2*DOT_PRODUCT(WK1,TFM%W)
  END DO
END DO
!$OMP END PARALLEL DO

COUNT = NTCHOP*NXCHOPDIM
CALL MPI_ALLREDUCE(MPI_IN_PLACE, PRODCT_MK_ALLK, COUNT, &
                  MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_IVP, IERR)
PRODCT_MK_ALLK(1,:) = 0.5_P8*PRODCT_MK_ALLK(1,:)

RETURN
END FUNCTION PRODCT_MK_ALLK
! ======================================================================
FUNCTION PRODCT_MK_HALFK(A,B)
! ======================================================================
! [USAGE]:
! COMPUTE INT (1-X^2)*A*B RDR D(PHI) DZ OVER THE ENTIRE DOMAIN AND FOLD
! THE CONTRIBUTIONS INTO NON-NEGATIVE M AND K MODES.
! [PARAMETERS]:
! A, B >> SCALAR TYPE VARIABLES IN PFF_SPACE.
! [NOTES]:
! THIS FUNCTION COMPUTES THE DOT PRODUCT FOR ALL MODES BUT STORE THEM
! INTO NON-NEGATIVE M AND K MODES ONLY. 
! ======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: A,B
REAL(P8):: PRODCT_MK_HALFK(NTCHOP,NXCHOP), PRODCT_MK_ALL(NTCHOP,NXCHOPDIM)
INTEGER:: KK,KC

PRODCT_MK_ALL = PRODCT_MK_ALLK(A,B)

PRODCT_MK_HALFK = 0.D0
PRODCT_MK_HALFK(:,1) = PRODCT_MK_ALL(:,1) ! K = 0
DO KK=2,NXCHOP
  KC = NXCHOPDIM+2-KK
  PRODCT_MK_HALFK(:,KK) = PRODCT_MK_ALL(:,KC)+PRODCT_MK_ALL(:,KK)
ENDDO

RETURN
END FUNCTION PRODCT_MK_HALFK
! ======================================================================
  FUNCTION PRODCT_M(A,B)
!=======================================================================
! [USAGE]: 
! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! FOR EACH AZIMUTHAL WAVENUMBER.
! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! [PARAMETERS]:
! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR), INTENT(IN):: A,B
  REAL(P8):: PRODCT_M(NTCHOP),PRODCTMK(NTCHOP,NXCHOP)
  INTEGER:: MM,KK

  PRODCTMK = PRODCT_MK_HALFK(A,B)
  PRODCT_M = 0.D0
  PRODCT_M = SUM(PRODCTMK, DIM=2)

  RETURN
  END FUNCTION PRODCT_M
!=======================================================================
  FUNCTION PRODCT_K(A,B)
!=======================================================================
! [USAGE]: 
! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! FOR EACH AXIAL WAVENUMBER.
! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! [PARAMETERS]:
! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
!=======================================================================
  IMPLICIT NONE
  TYPE(SCALAR), INTENT(IN):: A,B
  REAL(P8):: PRODCT_K(NXCHOP),PRODCTMK(NTCHOP,NXCHOP)

  PRODCTMK = PRODCT_MK_HALFK(A,B)
  PRODCT_K = 0.D0
  PRODCT_K = SUM(PRODCTMK, DIM=1)

  RETURN
  END FUNCTION PRODCT_K
!=======================================================================
!   FUNCTION PRODCT_M(A,B)
! !=======================================================================
! ! [USAGE]: 
! ! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! ! FOR EACH AZIMUTHAL WAVENUMBER.
! ! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! ! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! ! [PARAMETERS]:
! ! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! [UPDATES]:
! ! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! !=======================================================================
!   IMPLICIT NONE
!   TYPE(SCALAR):: A,B

!   COMPLEX(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NTCHOP)
!   REAL(P8),DIMENSION(NTCHOP):: PRODCT_M
!   INTEGER:: MM,KK

!   IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
!     IF (MPI_RANK.EQ.0) THEN
!       WRITE(*,*) 'PRODCT:NOT IN PFF_SPACE'
!       WRITE(*,*) 'A%SPACE,B%SPACE=',A%SPACE,B%SPACE
!     ENDIF
!     STOP
!   ENDIF

!   IF(A%LN.NE.0.0 .OR. B%LN.NE.0.0) THEN
!     IF (MPI_RANK.EQ.0) WRITE(*,*) 'PRODCT:LOGTERM NOT ZERO'
!   ENDIF

!   ALLOCATE(PROD(NR,SIZE(A%E,2)))
!   PROD=0

!   DO KK = 1,SIZE(A%E,3) !NX
!     !IF(KK.GT.NXCHOP .AND. KK.LT.NXCHOPH) CYCLE
!     DO MM = 1,SIZE(A%E,2) !NTCHOP
!       ! M = 0
!       IF (MM+A%INTH.EQ.1) THEN
!         PROD(:,1) = PROD(:,1)+A%E(:NR,1,KK)*CONJG(B%E(:NR,1,KK))
!       ! M > 0
!       ELSE
!       PROD(:,MM) = PROD(:,MM)+2*(REAL(A%E(:NR,MM,KK)) &
!                                 *REAL(B%E(:NR,MM,KK)) &
!                                 +AIMAG(A%E(:NR,MM,KK))&
!                                 *AIMAG(B%E(:NR,MM,KK)))
!       ENDIF
!     ENDDO
!   ENDDO

!   PRODCT_M = 0.D0
!   DO MM=1,SIZE(A%E,2) !NTCHOP
!     ! NOTE:
!     ! PRODCT_M IS CALCULATED DIRECTLY USING GAUSS-LEGENDRE QUADRATURE
!     ! THERE IS NO REASON BEHIND *TFM%PF(1,1,1)*TFM%NORM(1,1)
!     ! PRODCT_M(MM+A%INTH) = SUM((PROD(:,MM)*TFM%W)*TFM%PF(1,1,1))
!     ! PRODCT_M(MM+A%INTH) = 4*PI*ZLEN0*ELL2*PRODCT_M(MM+A%INTH)*TFM%NORM(1,1)
!     PRODCT_M(MM+A%INTH) = SUM(PROD(:,MM)*TFM%W)
!     PRODCT_M(MM+A%INTH) = 2*PI*ZLEN0*ELL2*PRODCT_M(MM+A%INTH)
!   ENDDO
!   CALL MPI_ALLREDUCE(MPI_IN_PLACE,PRODCT_M,NTCHOP,MPI_DOUBLE_PRECISION, &
!                   MPI_SUM, MPI_COMM_IVP, IERR)

!   DEALLOCATE(PROD)
!   RETURN
!   END FUNCTION PRODCT_M
! !=======================================================================
!   FUNCTION PRODCT_K(A,B)
! !=======================================================================
! ! [USAGE]: 
! ! CALCULATE THE PRODUCT AND INTEGRATE OVER THE DOMAIN
! ! FOR EACH AXIAL WAVENUMBER.
! ! CALL IN R-PHYSICAL / PHI,Z-FOURIER SPACE (PFF SPACE)
! ! WHAT'S INTEGRATED IS F=A*B*(1-MU)^2
! ! [PARAMETERS]:
! ! A >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! B >> SCALAR-TYPE VARIABLE IN A PFF SPACE
! ! [UPDATES]:
! ! RE-CODED BY SANGJOON LEE @ NOV 20 2020
! !=======================================================================
!   IMPLICIT NONE
!   TYPE(SCALAR):: A,B

!   ! COMPLEX(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NXCHOP)
!   REAL(P8),DIMENSION(:,:),ALLOCATABLE:: PROD !(NR,NXCHOP)
!   REAL(P8),DIMENSION(NXCHOPDIM):: PRODCTK_TEMP
!   REAL(P8),DIMENSION(NXCHOP):: PRODCT_K
!   INTEGER:: MM,KK,KH,CK,CM

!   IF(A%SPACE.NE.PFF_SPACE .OR. B%SPACE.NE.PFF_SPACE) THEN
!     IF (MPI_RANK.EQ.0) THEN
!       WRITE(*,*) 'PRODCT:NOT IN PFF_SPACE'
!       WRITE(*,*) 'A%SPACE,B%SPACE=',A%SPACE,B%SPACE
!     ENDIF
!     STOP
!   ENDIF

!   IF(A%LN.NE.0.0 .OR. B%LN.NE.0.0) THEN
!     IF (MPI_RANK.EQ.0) WRITE(*,*) 'PRODCT:LOGTERM NOT ZERO'
!   ENDIF

!   ALLOCATE(PROD(NR,SIZE(A%E,3)))
!   PROD=0

!   DO KK = 1,SIZE(A%E,3) !NXCHOP
!     IF(KK+A%INX.EQ.1) THEN
!       CK=2
!       KH=1
!     ELSE
!       CK=1
!       !KH=NX-KK+2
!     ENDIF

!     DO MM = 1,SIZE(A%E,2) !NTCHOP
!       CM=1
!       IF(MM+A%INTH.EQ.1) CM=2
!       ! PROD(:,KK)=PROD(:,KK)+1.0D0/CK/CM* & 
!       !            2*REAL(A%E(:NR,MM,KK)*CONJG(B%E(:NR,MM,KK)) &
!       !                   +B%E(:NR,MM,KH)*CONJG(A%E(:NR,MM,KH)))
!       PROD(:,KK)=PROD(:,KK)+1.0D0/CK/CM* & 
!                   2*REAL(A%E(:NR,MM,KK)*CONJG(B%E(:NR,MM,KK))) 
!                         !+B%E(:NR,MM,KH)*CONJG(A%E(:NR,MM,KH)))
!     ENDDO
!   ENDDO

!   PRODCTK_TEMP = 0.D0
!   DO KK=1,SIZE(A%E,3) !NXCHOP
!     ! NOTE:
!     ! THERE IS NO POINT OF *TFM%PF(1,1,1)*TFM*NORM(1,1)
!     ! PRODCT IS CALCULATED DIRECTLY USING GAUSS-LEGENDRE QUADRATURE
!     ! PRODCTK_TEMP(KK+A%INX) = SUM((PROD(:,KK)*TFM%W)*TFM%PF(1,1,1))
!     ! PRODCTK_TEMP(KK+A%INX) = 4*PI*ZLEN0*ELL2*PRODCTK_TEMP(KK+A%INX)*TFM%NORM(1,1)
!     PRODCTK_TEMP(KK+A%INX) = SUM(PROD(:,KK)*TFM%W)
!     PRODCTK_TEMP(KK+A%INX) = 2*PI*ZLEN0*ELL2*PRODCTK_TEMP(KK+A%INX)
!   ENDDO
!   CALL MPI_ALLREDUCE(MPI_IN_PLACE,PRODCTK_TEMP,NXCHOPDIM,MPI_DOUBLE_PRECISION, &
!                   MPI_SUM, MPI_COMM_IVP, IERR)

!   DO KK = 1,NXCHOP
!     KH = NXCHOPDIM - KK + 2
!     IF (KK.EQ.1) KH = 1
!     PRODCT_K(KK) = PRODCTK_TEMP(KK) + PRODCTK_TEMP(KH)
!   ENDDO

!   DEALLOCATE(PROD)
!   RETURN
!   END FUNCTION PRODCT_K
!=======================================================================
FUNCTION L2NORM_MK_ALLK(A)
! ======================================================================
! [USAGE]:
! COMPUTES THE L2 NORM SQUARED OF A SCALAR FIELD A, WITH THE RESULT
! DISTRIBUTED OVER NON-NEGATIVE AZIMUTHAL (M) AND ALL AXIAL (K) WAVENUMBERS.
! THE L2 NORM SQUARED IS DEFINED AS INT |A|^2 R DR D(PHI) DZ OVER THE
! ENTIRE DOMAIN.
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE IN PFF_SPACE.
! [RETURNS]:
! A 2D REAL ARRAY OF SIZE (NTCHOP, NXCHOPDIM) CONTAINING THE L2 NORM
! SQUARED CONTRIBUTION FROM EACH (M >= 0, K) MODE.
! ======================================================================
IMPLICIT NONE
TYPE(SCALAR), INTENT(IN):: A
REAL(P8):: WK1(NR)
REAL(P8):: L2NORM_MK_ALLK(NTCHOP,NXCHOPDIM) !NX)
INTEGER:: MM,KK,COUNT

IF(A%SPACE.NE.PFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) THEN
      PRINT *,'ERROR: L2NORM_MK() -- NOT IN PFF_SPACE.'
      PRINT *,'A%SPACE = ',A%SPACE
  ENDIF
  STOP
ENDIF

IF ((A%INTH.EQ.0).AND.(A%INX.EQ.0)) THEN
  IF(ABS(A%LN)>1.0E-8) THEN
      PRINT *,'WARNING: L2NORM_MK() -- LOGTERM NOT ZERO.'
      PRINT *,'A%LN = ',A%LN
  ENDIF
ENDIF

L2NORM_MK_ALLK = 0.D0
!$OMP PARALLEL DO COLLAPSE(2) PRIVATE(WK1) SCHEDULE(STATIC)
DO KK=1,SIZE(A%E,3) !NXCHOP
  DO MM=1,SIZE(A%E,2) !NTCHOP
      WK1 = ABS(A%E(:NR,MM,KK))**2/(1-TFM%X(:NR))**2
      ! {MM,KK}&{-MM,-KK} combined
      ! note: We save non-negative M's, but all K's.
      !       So, for {0,KK}, we should not add {0,-KK} during the calculation,
      !       as {0,-KK} is actually saved. Hence, all MM = 0 modes' product is
      !       off by a factor of 2.
      L2NORM_MK_ALLK(MM+A%INTH,KK+A%INX) = &
              4.0_P8*PI*ZLEN0*ELL2*DOT_PRODUCT(WK1,TFM%W)
  END DO
END DO
!$OMP END PARALLEL DO

COUNT = NTCHOP*NXCHOPDIM
CALL MPI_ALLREDUCE(MPI_IN_PLACE, L2NORM_MK_ALLK, COUNT, &
                  MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_IVP, IERR)
L2NORM_MK_ALLK(1,:) = 0.5_P8*L2NORM_MK_ALLK(1,:)

RETURN
END FUNCTION L2NORM_MK_ALLK
! ======================================================================
FUNCTION L2NORM_MK_HALFK(A)
! ======================================================================
! [USAGE]:
! COMPUTES THE L2 NORM SQUARED OF A SCALAR FIELD A, WITH THE RESULT
! DISTRIBUTED OVER NON-NEGATIVE AZIMUTHAL (M) AND AXIAL (K) WAVENUMBERS.
! THE L2 NORM SQUARED IS DEFINED AS INT |A|^2 R DR D(PHI) DZ OVER THE
! ENTIRE DOMAIN.
! [PARAMETERS]:
! A >> A SCALAR-TYPE VARIABLE IN PFF_SPACE.
! [RETURNS]:
! A 2D REAL ARRAY OF SIZE (NTCHOP, NXCHOP) CONTAINING THE L2 NORM
! SQUARED CONTRIBUTION FROM EACH NON-NEGATIVE (M, K) MODE.
! [NOTES]:
! THIS FUNCTION FIRST CALLS L2NORM_MK_ALLK TO COMPUTE THE NORM FOR ALL
! K MODES, AND THEN FOLDS THE CONTRIBUTIONS FROM NEGATIVE K MODES
! INTO THE CORRESPONDING POSITIVE K MODES. FOR A REAL PHYSICAL FIELD,
! THE CONTRIBUTION FROM K AND -K ARE EQUAL.
! ======================================================================
IMPLICIT NONE
TYPE(SCALAR), INTENT(IN):: A
REAL(P8):: L2NORM_MK_HALFK(NTCHOP,NXCHOP), L2NORM_MK_ALL(NTCHOP,NXCHOPDIM)
INTEGER:: KK,KC

L2NORM_MK_ALL = L2NORM_MK_ALLK(A)

L2NORM_MK_HALFK = 0.D0
L2NORM_MK_HALFK(:,1) = L2NORM_MK_ALL(:,1) ! K = 0
DO KK=2,NXCHOP
  KC = NXCHOPDIM+2-KK
  L2NORM_MK_HALFK(:,KK) = L2NORM_MK_ALL(:,KC)+L2NORM_MK_ALL(:,KK)
ENDDO

RETURN
END FUNCTION L2NORM_MK_HALFK
! ======================================================================
FUNCTION INTEGH(F,AIN,BIN)
!=======================================================================
! [USAGE]:
! INTEGRATION OF A FUNCTION OVER A PART OF THE FULL DOMAIN 
!     0   <  R   < INFTY
!     AIN <  PHI < BIN
!     0   <  Z   < ZLEN
! CALL IN P/F SPACE, MEANING THAT F IS IN HAT FORM
! INTEGRATED FUNCTION G IS IN THE FORM G = F*(1-MU)^2
! [INPUTS]:
! F >> A FUNTION INPUT FOR INTEGRATION (ACTUAL INTEGRATION IS DONE ON G)
! AIN >> (OPTIONAL) INFIMUM OF PHI. DEFAULT IS -PI/2.
! BIN >> (OPTIONAL) SUPREMUM OF PHI. DEFAULT IS PI/2.
! [OUTPUTS]:
! INTEGH >> INTEGRATION EQUAL TO INT_[PART_RANGE](G(R,PHI,Z) DR DPHI DZ)
! [UPDATES]:
! RE-CODED BY SANGJOON LEE @ NOV 18 2020
! MPI-ED BY JINGE WANG @ SEP 29 2021
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: F
REAL(P8),INTENT(IN),OPTIONAL:: AIN, BIN
REAL(P8):: INTEGH

COMPLEX(P8):: FAB
! COMPLEX(P8),PARAMETER:: IU = (0.0D0,1.0D0) !Declared in mod_misc.f90
REAL(P8):: A,B
INTEGER:: MM,M0

IF(F%SPACE.NE.PFF_SPACE) THEN
  IF (MPI_RANK.EQ.0) WRITE(*,*) 'INTEGH: NOT IN PFF_SPACE'
  STOP
ENDIF

IF(PRESENT(AIN)) THEN
  A=AIN
ELSE
  A=-PI/2                                                          ! DEFAULT: RIGHT HAND SIDE HALF PLANE
ENDIF

IF(PRESENT(BIN)) THEN
  B=BIN
ELSE
  B=PI/2
ENDIF

! INTEGH = (B-A)*SUM(TFM%W*F%E(:NR,1,1))

! DO MM=2,NTCHOP
!   M0=M(MM)
!   FAB = (EXP(IU*M0*B)-EXP(IU*M0*A))/(IU*M0)
!   INTEGH = INTEGH+2*REAL(FAB*SUM(TFM%W*F%E(:NR,MM,1)))
! ENDDO

! INTEGH = INTEGH*ZLEN*ELL2

INTEGH = 0.D0
IF (F%INX.EQ.0) THEN
  !INTEGH = (B-A)*SUM(TFM%W*F%E(:NR,1,1))
  DO MM=1,SIZE(F%E,2) !NTCHOP
    M0=M(MM+F%INTH) ! M(1) = 0
    IF (M0.EQ.0) THEN
      INTEGH = INTEGH + (B-A)*SUM(TFM%W*F%E(:NR,1,1))
    ELSE
      FAB = (EXP(IU*M0*B)-EXP(IU*M0*A))/(IU*M0)
      INTEGH = INTEGH + 2*REAL(FAB*SUM(TFM%W*F%E(:NR,MM,1)))
    ENDIF
  ENDDO
ENDIF

CALL MPI_ALLREDUCE(MPI_IN_PLACE, INTEGH, 1, MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_IVP, IERR)
INTEGH = INTEGH*ZLEN*ELL2

RETURN
END FUNCTION INTEGH
!=======================================================================
SUBROUTINE SPACE_MAP_INIT(THIS)
!=======================================================================
! [USAGE]: Initialize the space map with name-ID pairs
!=======================================================================
CLASS(SPACE_MAP), INTENT(INOUT) :: THIS

THIS%ENTRIES(1) = SPACE_MAP_ENTRY('PPP_SPACE', PPP_SPACE)
THIS%ENTRIES(2) = SPACE_MAP_ENTRY('FFF_SPACE', FFF_SPACE)
THIS%ENTRIES(3) = SPACE_MAP_ENTRY('PFP_SPACE', PFP_SPACE)
THIS%ENTRIES(4) = SPACE_MAP_ENTRY('PFF_SPACE', PFF_SPACE)
THIS%INITIALIZED = .TRUE.

END SUBROUTINE SPACE_MAP_INIT
!=======================================================================
FUNCTION SPACE_MAP_GET_ID(THIS, NAME) RESULT(ID)
!=======================================================================
! [USAGE]: Get space ID from name (like map[key] in C++)
!=======================================================================
CLASS(SPACE_MAP), INTENT(INOUT) :: THIS
CHARACTER(LEN=*), INTENT(IN) :: NAME
INTEGER :: ID
INTEGER :: I

IF (.NOT. THIS%INITIALIZED) CALL THIS%INIT()

ID = -1  ! Default: not found
DO I = 1, SIZE(THIS%ENTRIES)
IF (TRIM(ADJUSTL(THIS%ENTRIES(I)%NAME)) == TRIM(ADJUSTL(NAME))) THEN
  ID = THIS%ENTRIES(I)%ID
  EXIT
ENDIF
ENDDO

END FUNCTION SPACE_MAP_GET_ID
!=======================================================================
FUNCTION SPACE_MAP_GET_NAME(THIS, ID) RESULT(NAME)
!=======================================================================
! [USAGE]: Get space name from ID
!=======================================================================
CLASS(SPACE_MAP), INTENT(INOUT) :: THIS
INTEGER, INTENT(IN) :: ID
CHARACTER(LEN=20) :: NAME
INTEGER :: I

IF (.NOT. THIS%INITIALIZED) CALL THIS%INIT()

NAME = 'UNKNOWN'  ! Default: not found
DO I = 1, SIZE(THIS%ENTRIES)
IF (THIS%ENTRIES(I)%ID == ID) THEN
  NAME = THIS%ENTRIES(I)%NAME
  EXIT
ENDIF
ENDDO

END FUNCTION SPACE_MAP_GET_NAME
!=======================================================================
FUNCTION SPACE_MAP_HAS_KEY(THIS, NAME) RESULT(HAS_KEY)
!=======================================================================
! [USAGE]: Check if space name exists in map
!=======================================================================
CLASS(SPACE_MAP), INTENT(INOUT) :: THIS
CHARACTER(LEN=*), INTENT(IN) :: NAME
LOGICAL :: HAS_KEY

HAS_KEY = (THIS%GET_ID(NAME) /= -1)

END FUNCTION SPACE_MAP_HAS_KEY
!=======================================================================
FUNCTION SPACE_MAP_SIZE(THIS) RESULT(MAP_SIZE)
!=======================================================================
! [USAGE]: Return number of entries in map
!=======================================================================
CLASS(SPACE_MAP), INTENT(IN) :: THIS
INTEGER :: MAP_SIZE

MAP_SIZE = SIZE(THIS%ENTRIES)

END FUNCTION SPACE_MAP_SIZE
!=======================================================================
SUBROUTINE ANYNAN(A,VAR_NAME)
!=======================================================================
! [USAGE]:
! CHECK FOR NAN/INF VALUES IN A SCALAR FIELD AND REPORT DETAILS
! [PARAMETERS]:
! A >> SCALAR FIELD TO CHECK
! VAR_NAME >> OPTIONAL NAME OF THE VARIABLE FOR ERROR REPORTING
!=======================================================================
IMPLICIT NONE
TYPE(SCALAR),INTENT(IN):: A
CHARACTER(LEN=*),OPTIONAL,INTENT(IN):: VAR_NAME
INTEGER:: NN,MM,KK
LOGICAL:: FOUND_NAN

FOUND_NAN = .FALSE.

! CHECK FOR NAN VALUES AND REPORT THE FIRST OCCURRENCE
DO KK = 1,SIZE(A%E,3)
  DO MM = 1,SIZE(A%E,2) 
    DO NN = 1,SIZE(A%E,1)
      IF (.NOT. IEEE_IS_FINITE(REAL(A%E(NN,MM,KK))) .OR. &
          .NOT. IEEE_IS_FINITE(AIMAG(A%E(NN,MM,KK)))) THEN

        IF (PRESENT(VAR_NAME)) THEN
          WRITE(*,'("ERROR: NON-FINITE VALUES IN FIELD ",A," ON RANK ",I0," AT (",I0,",",I0,",",I0,")")') &
          TRIM(ADJUSTL(VAR_NAME)), MPI_RANK, NN, MM, KK
        ELSE
          WRITE(*,'("ERROR: NON-FINITE VALUES IN SCALAR FIELD ON RANK ",I0," AT (",I0,",",I0,",",I0,")")') &
          MPI_RANK, NN, MM, KK
        ENDIF
        WRITE(*,'("VALUE=",2ES12.4," DIMS=",3I0," SPACE=",I0," INTH=",I0," INX=",I0," INR=",I0," LN=",ES12.4)') &
              REAL(A%E(NN,MM,KK)), AIMAG(A%E(NN,MM,KK)), SIZE(A%E,1), SIZE(A%E,2), SIZE(A%E,3), A%SPACE, A%INTH, A%INX, A%INR, A%LN
        FOUND_NAN = .TRUE.
        EXIT
      ENDIF
    ENDDO
    IF (FOUND_NAN) EXIT
  ENDDO
  IF (FOUND_NAN) EXIT
ENDDO

CALL MPI_BARRIER(MPI_COMM_IVP,IERR)
IF (FOUND_NAN) THEN
  CALL MPI_ABORT(MPI_COMM_IVP, ERR_FLAGS%CALCULATION, IERR)
ENDIF

RETURN
END SUBROUTINE ANYNAN
!=======================================================================

END MODULE MOD_SCALAR3